
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CityMission` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CityMission
 * 
 */
export type CityMissionModel = runtime.Types.Result.DefaultSelection<Prisma.$CityMissionPayload>

export type AggregateCityMission = {
  _count: CityMissionCountAggregateOutputType | null
  _avg: CityMissionAvgAggregateOutputType | null
  _sum: CityMissionSumAggregateOutputType | null
  _min: CityMissionMinAggregateOutputType | null
  _max: CityMissionMaxAggregateOutputType | null
}

export type CityMissionAvgAggregateOutputType = {
  budget: number | null
  latitude: number | null
  longitude: number | null
}

export type CityMissionSumAggregateOutputType = {
  budget: number | null
  latitude: number | null
  longitude: number | null
}

export type CityMissionMinAggregateOutputType = {
  id: string | null
  city: string | null
  startLocation: string | null
  destination: string | null
  interests: string | null
  budget: number | null
  currency: string | null
  duration: string | null
  transport: string | null
  accessibility: string | null
  priorities: string | null
  latitude: number | null
  longitude: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CityMissionMaxAggregateOutputType = {
  id: string | null
  city: string | null
  startLocation: string | null
  destination: string | null
  interests: string | null
  budget: number | null
  currency: string | null
  duration: string | null
  transport: string | null
  accessibility: string | null
  priorities: string | null
  latitude: number | null
  longitude: number | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CityMissionCountAggregateOutputType = {
  id: number
  city: number
  startLocation: number
  destination: number
  interests: number
  budget: number
  currency: number
  duration: number
  transport: number
  accessibility: number
  priorities: number
  latitude: number
  longitude: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type CityMissionAvgAggregateInputType = {
  budget?: true
  latitude?: true
  longitude?: true
}

export type CityMissionSumAggregateInputType = {
  budget?: true
  latitude?: true
  longitude?: true
}

export type CityMissionMinAggregateInputType = {
  id?: true
  city?: true
  startLocation?: true
  destination?: true
  interests?: true
  budget?: true
  currency?: true
  duration?: true
  transport?: true
  accessibility?: true
  priorities?: true
  latitude?: true
  longitude?: true
  createdAt?: true
  updatedAt?: true
}

export type CityMissionMaxAggregateInputType = {
  id?: true
  city?: true
  startLocation?: true
  destination?: true
  interests?: true
  budget?: true
  currency?: true
  duration?: true
  transport?: true
  accessibility?: true
  priorities?: true
  latitude?: true
  longitude?: true
  createdAt?: true
  updatedAt?: true
}

export type CityMissionCountAggregateInputType = {
  id?: true
  city?: true
  startLocation?: true
  destination?: true
  interests?: true
  budget?: true
  currency?: true
  duration?: true
  transport?: true
  accessibility?: true
  priorities?: true
  latitude?: true
  longitude?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type CityMissionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CityMission to aggregate.
   */
  where?: Prisma.CityMissionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CityMissions to fetch.
   */
  orderBy?: Prisma.CityMissionOrderByWithRelationInput | Prisma.CityMissionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CityMissionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CityMissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CityMissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CityMissions
  **/
  _count?: true | CityMissionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CityMissionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CityMissionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CityMissionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CityMissionMaxAggregateInputType
}

export type GetCityMissionAggregateType<T extends CityMissionAggregateArgs> = {
      [P in keyof T & keyof AggregateCityMission]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCityMission[P]>
    : Prisma.GetScalarType<T[P], AggregateCityMission[P]>
}




export type CityMissionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CityMissionWhereInput
  orderBy?: Prisma.CityMissionOrderByWithAggregationInput | Prisma.CityMissionOrderByWithAggregationInput[]
  by: Prisma.CityMissionScalarFieldEnum[] | Prisma.CityMissionScalarFieldEnum
  having?: Prisma.CityMissionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CityMissionCountAggregateInputType | true
  _avg?: CityMissionAvgAggregateInputType
  _sum?: CityMissionSumAggregateInputType
  _min?: CityMissionMinAggregateInputType
  _max?: CityMissionMaxAggregateInputType
}

export type CityMissionGroupByOutputType = {
  id: string
  city: string
  startLocation: string | null
  destination: string | null
  interests: string
  budget: number
  currency: string
  duration: string
  transport: string
  accessibility: string | null
  priorities: string
  latitude: number | null
  longitude: number | null
  createdAt: Date
  updatedAt: Date
  _count: CityMissionCountAggregateOutputType | null
  _avg: CityMissionAvgAggregateOutputType | null
  _sum: CityMissionSumAggregateOutputType | null
  _min: CityMissionMinAggregateOutputType | null
  _max: CityMissionMaxAggregateOutputType | null
}

type GetCityMissionGroupByPayload<T extends CityMissionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CityMissionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CityMissionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CityMissionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CityMissionGroupByOutputType[P]>
      }
    >
  >



export type CityMissionWhereInput = {
  AND?: Prisma.CityMissionWhereInput | Prisma.CityMissionWhereInput[]
  OR?: Prisma.CityMissionWhereInput[]
  NOT?: Prisma.CityMissionWhereInput | Prisma.CityMissionWhereInput[]
  id?: Prisma.StringFilter<"CityMission"> | string
  city?: Prisma.StringFilter<"CityMission"> | string
  startLocation?: Prisma.StringNullableFilter<"CityMission"> | string | null
  destination?: Prisma.StringNullableFilter<"CityMission"> | string | null
  interests?: Prisma.StringFilter<"CityMission"> | string
  budget?: Prisma.FloatFilter<"CityMission"> | number
  currency?: Prisma.StringFilter<"CityMission"> | string
  duration?: Prisma.StringFilter<"CityMission"> | string
  transport?: Prisma.StringFilter<"CityMission"> | string
  accessibility?: Prisma.StringNullableFilter<"CityMission"> | string | null
  priorities?: Prisma.StringFilter<"CityMission"> | string
  latitude?: Prisma.FloatNullableFilter<"CityMission"> | number | null
  longitude?: Prisma.FloatNullableFilter<"CityMission"> | number | null
  createdAt?: Prisma.DateTimeFilter<"CityMission"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CityMission"> | Date | string
}

export type CityMissionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  city?: Prisma.SortOrder
  startLocation?: Prisma.SortOrderInput | Prisma.SortOrder
  destination?: Prisma.SortOrderInput | Prisma.SortOrder
  interests?: Prisma.SortOrder
  budget?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  transport?: Prisma.SortOrder
  accessibility?: Prisma.SortOrderInput | Prisma.SortOrder
  priorities?: Prisma.SortOrder
  latitude?: Prisma.SortOrderInput | Prisma.SortOrder
  longitude?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CityMissionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.CityMissionWhereInput | Prisma.CityMissionWhereInput[]
  OR?: Prisma.CityMissionWhereInput[]
  NOT?: Prisma.CityMissionWhereInput | Prisma.CityMissionWhereInput[]
  city?: Prisma.StringFilter<"CityMission"> | string
  startLocation?: Prisma.StringNullableFilter<"CityMission"> | string | null
  destination?: Prisma.StringNullableFilter<"CityMission"> | string | null
  interests?: Prisma.StringFilter<"CityMission"> | string
  budget?: Prisma.FloatFilter<"CityMission"> | number
  currency?: Prisma.StringFilter<"CityMission"> | string
  duration?: Prisma.StringFilter<"CityMission"> | string
  transport?: Prisma.StringFilter<"CityMission"> | string
  accessibility?: Prisma.StringNullableFilter<"CityMission"> | string | null
  priorities?: Prisma.StringFilter<"CityMission"> | string
  latitude?: Prisma.FloatNullableFilter<"CityMission"> | number | null
  longitude?: Prisma.FloatNullableFilter<"CityMission"> | number | null
  createdAt?: Prisma.DateTimeFilter<"CityMission"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CityMission"> | Date | string
}, "id">

export type CityMissionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  city?: Prisma.SortOrder
  startLocation?: Prisma.SortOrderInput | Prisma.SortOrder
  destination?: Prisma.SortOrderInput | Prisma.SortOrder
  interests?: Prisma.SortOrder
  budget?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  transport?: Prisma.SortOrder
  accessibility?: Prisma.SortOrderInput | Prisma.SortOrder
  priorities?: Prisma.SortOrder
  latitude?: Prisma.SortOrderInput | Prisma.SortOrder
  longitude?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.CityMissionCountOrderByAggregateInput
  _avg?: Prisma.CityMissionAvgOrderByAggregateInput
  _max?: Prisma.CityMissionMaxOrderByAggregateInput
  _min?: Prisma.CityMissionMinOrderByAggregateInput
  _sum?: Prisma.CityMissionSumOrderByAggregateInput
}

export type CityMissionScalarWhereWithAggregatesInput = {
  AND?: Prisma.CityMissionScalarWhereWithAggregatesInput | Prisma.CityMissionScalarWhereWithAggregatesInput[]
  OR?: Prisma.CityMissionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CityMissionScalarWhereWithAggregatesInput | Prisma.CityMissionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CityMission"> | string
  city?: Prisma.StringWithAggregatesFilter<"CityMission"> | string
  startLocation?: Prisma.StringNullableWithAggregatesFilter<"CityMission"> | string | null
  destination?: Prisma.StringNullableWithAggregatesFilter<"CityMission"> | string | null
  interests?: Prisma.StringWithAggregatesFilter<"CityMission"> | string
  budget?: Prisma.FloatWithAggregatesFilter<"CityMission"> | number
  currency?: Prisma.StringWithAggregatesFilter<"CityMission"> | string
  duration?: Prisma.StringWithAggregatesFilter<"CityMission"> | string
  transport?: Prisma.StringWithAggregatesFilter<"CityMission"> | string
  accessibility?: Prisma.StringNullableWithAggregatesFilter<"CityMission"> | string | null
  priorities?: Prisma.StringWithAggregatesFilter<"CityMission"> | string
  latitude?: Prisma.FloatNullableWithAggregatesFilter<"CityMission"> | number | null
  longitude?: Prisma.FloatNullableWithAggregatesFilter<"CityMission"> | number | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CityMission"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"CityMission"> | Date | string
}

export type CityMissionCreateInput = {
  id?: string
  city: string
  startLocation?: string | null
  destination?: string | null
  interests: string
  budget: number
  currency?: string
  duration: string
  transport: string
  accessibility?: string | null
  priorities: string
  latitude?: number | null
  longitude?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CityMissionUncheckedCreateInput = {
  id?: string
  city: string
  startLocation?: string | null
  destination?: string | null
  interests: string
  budget: number
  currency?: string
  duration: string
  transport: string
  accessibility?: string | null
  priorities: string
  latitude?: number | null
  longitude?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CityMissionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  startLocation?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  destination?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  interests?: Prisma.StringFieldUpdateOperationsInput | string
  budget?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.StringFieldUpdateOperationsInput | string
  transport?: Prisma.StringFieldUpdateOperationsInput | string
  accessibility?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  priorities?: Prisma.StringFieldUpdateOperationsInput | string
  latitude?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  longitude?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CityMissionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  startLocation?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  destination?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  interests?: Prisma.StringFieldUpdateOperationsInput | string
  budget?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.StringFieldUpdateOperationsInput | string
  transport?: Prisma.StringFieldUpdateOperationsInput | string
  accessibility?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  priorities?: Prisma.StringFieldUpdateOperationsInput | string
  latitude?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  longitude?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CityMissionCreateManyInput = {
  id?: string
  city: string
  startLocation?: string | null
  destination?: string | null
  interests: string
  budget: number
  currency?: string
  duration: string
  transport: string
  accessibility?: string | null
  priorities: string
  latitude?: number | null
  longitude?: number | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CityMissionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  startLocation?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  destination?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  interests?: Prisma.StringFieldUpdateOperationsInput | string
  budget?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.StringFieldUpdateOperationsInput | string
  transport?: Prisma.StringFieldUpdateOperationsInput | string
  accessibility?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  priorities?: Prisma.StringFieldUpdateOperationsInput | string
  latitude?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  longitude?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CityMissionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  startLocation?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  destination?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  interests?: Prisma.StringFieldUpdateOperationsInput | string
  budget?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  duration?: Prisma.StringFieldUpdateOperationsInput | string
  transport?: Prisma.StringFieldUpdateOperationsInput | string
  accessibility?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  priorities?: Prisma.StringFieldUpdateOperationsInput | string
  latitude?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  longitude?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CityMissionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  city?: Prisma.SortOrder
  startLocation?: Prisma.SortOrder
  destination?: Prisma.SortOrder
  interests?: Prisma.SortOrder
  budget?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  transport?: Prisma.SortOrder
  accessibility?: Prisma.SortOrder
  priorities?: Prisma.SortOrder
  latitude?: Prisma.SortOrder
  longitude?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CityMissionAvgOrderByAggregateInput = {
  budget?: Prisma.SortOrder
  latitude?: Prisma.SortOrder
  longitude?: Prisma.SortOrder
}

export type CityMissionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  city?: Prisma.SortOrder
  startLocation?: Prisma.SortOrder
  destination?: Prisma.SortOrder
  interests?: Prisma.SortOrder
  budget?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  transport?: Prisma.SortOrder
  accessibility?: Prisma.SortOrder
  priorities?: Prisma.SortOrder
  latitude?: Prisma.SortOrder
  longitude?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CityMissionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  city?: Prisma.SortOrder
  startLocation?: Prisma.SortOrder
  destination?: Prisma.SortOrder
  interests?: Prisma.SortOrder
  budget?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  transport?: Prisma.SortOrder
  accessibility?: Prisma.SortOrder
  priorities?: Prisma.SortOrder
  latitude?: Prisma.SortOrder
  longitude?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CityMissionSumOrderByAggregateInput = {
  budget?: Prisma.SortOrder
  latitude?: Prisma.SortOrder
  longitude?: Prisma.SortOrder
}

export type FloatFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableFloatFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type CityMissionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  city?: boolean
  startLocation?: boolean
  destination?: boolean
  interests?: boolean
  budget?: boolean
  currency?: boolean
  duration?: boolean
  transport?: boolean
  accessibility?: boolean
  priorities?: boolean
  latitude?: boolean
  longitude?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["cityMission"]>

export type CityMissionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  city?: boolean
  startLocation?: boolean
  destination?: boolean
  interests?: boolean
  budget?: boolean
  currency?: boolean
  duration?: boolean
  transport?: boolean
  accessibility?: boolean
  priorities?: boolean
  latitude?: boolean
  longitude?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["cityMission"]>

export type CityMissionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  city?: boolean
  startLocation?: boolean
  destination?: boolean
  interests?: boolean
  budget?: boolean
  currency?: boolean
  duration?: boolean
  transport?: boolean
  accessibility?: boolean
  priorities?: boolean
  latitude?: boolean
  longitude?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["cityMission"]>

export type CityMissionSelectScalar = {
  id?: boolean
  city?: boolean
  startLocation?: boolean
  destination?: boolean
  interests?: boolean
  budget?: boolean
  currency?: boolean
  duration?: boolean
  transport?: boolean
  accessibility?: boolean
  priorities?: boolean
  latitude?: boolean
  longitude?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type CityMissionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "city" | "startLocation" | "destination" | "interests" | "budget" | "currency" | "duration" | "transport" | "accessibility" | "priorities" | "latitude" | "longitude" | "createdAt" | "updatedAt", ExtArgs["result"]["cityMission"]>

export type $CityMissionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CityMission"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    city: string
    startLocation: string | null
    destination: string | null
    interests: string
    budget: number
    currency: string
    duration: string
    transport: string
    accessibility: string | null
    priorities: string
    latitude: number | null
    longitude: number | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["cityMission"]>
  composites: {}
}

export type CityMissionGetPayload<S extends boolean | null | undefined | CityMissionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CityMissionPayload, S>

export type CityMissionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CityMissionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CityMissionCountAggregateInputType | true
  }

export interface CityMissionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CityMission'], meta: { name: 'CityMission' } }
  /**
   * Find zero or one CityMission that matches the filter.
   * @param {CityMissionFindUniqueArgs} args - Arguments to find a CityMission
   * @example
   * // Get one CityMission
   * const cityMission = await prisma.cityMission.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CityMissionFindUniqueArgs>(args: Prisma.SelectSubset<T, CityMissionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CityMissionClient<runtime.Types.Result.GetResult<Prisma.$CityMissionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CityMission that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CityMissionFindUniqueOrThrowArgs} args - Arguments to find a CityMission
   * @example
   * // Get one CityMission
   * const cityMission = await prisma.cityMission.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CityMissionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CityMissionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CityMissionClient<runtime.Types.Result.GetResult<Prisma.$CityMissionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CityMission that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CityMissionFindFirstArgs} args - Arguments to find a CityMission
   * @example
   * // Get one CityMission
   * const cityMission = await prisma.cityMission.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CityMissionFindFirstArgs>(args?: Prisma.SelectSubset<T, CityMissionFindFirstArgs<ExtArgs>>): Prisma.Prisma__CityMissionClient<runtime.Types.Result.GetResult<Prisma.$CityMissionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CityMission that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CityMissionFindFirstOrThrowArgs} args - Arguments to find a CityMission
   * @example
   * // Get one CityMission
   * const cityMission = await prisma.cityMission.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CityMissionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CityMissionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CityMissionClient<runtime.Types.Result.GetResult<Prisma.$CityMissionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CityMissions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CityMissionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CityMissions
   * const cityMissions = await prisma.cityMission.findMany()
   * 
   * // Get first 10 CityMissions
   * const cityMissions = await prisma.cityMission.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const cityMissionWithIdOnly = await prisma.cityMission.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CityMissionFindManyArgs>(args?: Prisma.SelectSubset<T, CityMissionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CityMissionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CityMission.
   * @param {CityMissionCreateArgs} args - Arguments to create a CityMission.
   * @example
   * // Create one CityMission
   * const CityMission = await prisma.cityMission.create({
   *   data: {
   *     // ... data to create a CityMission
   *   }
   * })
   * 
   */
  create<T extends CityMissionCreateArgs>(args: Prisma.SelectSubset<T, CityMissionCreateArgs<ExtArgs>>): Prisma.Prisma__CityMissionClient<runtime.Types.Result.GetResult<Prisma.$CityMissionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CityMissions.
   * @param {CityMissionCreateManyArgs} args - Arguments to create many CityMissions.
   * @example
   * // Create many CityMissions
   * const cityMission = await prisma.cityMission.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CityMissionCreateManyArgs>(args?: Prisma.SelectSubset<T, CityMissionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CityMissions and returns the data saved in the database.
   * @param {CityMissionCreateManyAndReturnArgs} args - Arguments to create many CityMissions.
   * @example
   * // Create many CityMissions
   * const cityMission = await prisma.cityMission.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CityMissions and only return the `id`
   * const cityMissionWithIdOnly = await prisma.cityMission.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CityMissionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CityMissionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CityMissionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CityMission.
   * @param {CityMissionDeleteArgs} args - Arguments to delete one CityMission.
   * @example
   * // Delete one CityMission
   * const CityMission = await prisma.cityMission.delete({
   *   where: {
   *     // ... filter to delete one CityMission
   *   }
   * })
   * 
   */
  delete<T extends CityMissionDeleteArgs>(args: Prisma.SelectSubset<T, CityMissionDeleteArgs<ExtArgs>>): Prisma.Prisma__CityMissionClient<runtime.Types.Result.GetResult<Prisma.$CityMissionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CityMission.
   * @param {CityMissionUpdateArgs} args - Arguments to update one CityMission.
   * @example
   * // Update one CityMission
   * const cityMission = await prisma.cityMission.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CityMissionUpdateArgs>(args: Prisma.SelectSubset<T, CityMissionUpdateArgs<ExtArgs>>): Prisma.Prisma__CityMissionClient<runtime.Types.Result.GetResult<Prisma.$CityMissionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CityMissions.
   * @param {CityMissionDeleteManyArgs} args - Arguments to filter CityMissions to delete.
   * @example
   * // Delete a few CityMissions
   * const { count } = await prisma.cityMission.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CityMissionDeleteManyArgs>(args?: Prisma.SelectSubset<T, CityMissionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CityMissions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CityMissionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CityMissions
   * const cityMission = await prisma.cityMission.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CityMissionUpdateManyArgs>(args: Prisma.SelectSubset<T, CityMissionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CityMissions and returns the data updated in the database.
   * @param {CityMissionUpdateManyAndReturnArgs} args - Arguments to update many CityMissions.
   * @example
   * // Update many CityMissions
   * const cityMission = await prisma.cityMission.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CityMissions and only return the `id`
   * const cityMissionWithIdOnly = await prisma.cityMission.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CityMissionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CityMissionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CityMissionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CityMission.
   * @param {CityMissionUpsertArgs} args - Arguments to update or create a CityMission.
   * @example
   * // Update or create a CityMission
   * const cityMission = await prisma.cityMission.upsert({
   *   create: {
   *     // ... data to create a CityMission
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CityMission we want to update
   *   }
   * })
   */
  upsert<T extends CityMissionUpsertArgs>(args: Prisma.SelectSubset<T, CityMissionUpsertArgs<ExtArgs>>): Prisma.Prisma__CityMissionClient<runtime.Types.Result.GetResult<Prisma.$CityMissionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CityMissions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CityMissionCountArgs} args - Arguments to filter CityMissions to count.
   * @example
   * // Count the number of CityMissions
   * const count = await prisma.cityMission.count({
   *   where: {
   *     // ... the filter for the CityMissions we want to count
   *   }
   * })
  **/
  count<T extends CityMissionCountArgs>(
    args?: Prisma.Subset<T, CityMissionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CityMissionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CityMission.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CityMissionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CityMissionAggregateArgs>(args: Prisma.Subset<T, CityMissionAggregateArgs>): Prisma.PrismaPromise<GetCityMissionAggregateType<T>>

  /**
   * Group by CityMission.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CityMissionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CityMissionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CityMissionGroupByArgs['orderBy'] }
      : { orderBy?: CityMissionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CityMissionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCityMissionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CityMission model
 */
readonly fields: CityMissionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CityMission.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CityMissionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CityMission model
 */
export interface CityMissionFieldRefs {
  readonly id: Prisma.FieldRef<"CityMission", 'String'>
  readonly city: Prisma.FieldRef<"CityMission", 'String'>
  readonly startLocation: Prisma.FieldRef<"CityMission", 'String'>
  readonly destination: Prisma.FieldRef<"CityMission", 'String'>
  readonly interests: Prisma.FieldRef<"CityMission", 'String'>
  readonly budget: Prisma.FieldRef<"CityMission", 'Float'>
  readonly currency: Prisma.FieldRef<"CityMission", 'String'>
  readonly duration: Prisma.FieldRef<"CityMission", 'String'>
  readonly transport: Prisma.FieldRef<"CityMission", 'String'>
  readonly accessibility: Prisma.FieldRef<"CityMission", 'String'>
  readonly priorities: Prisma.FieldRef<"CityMission", 'String'>
  readonly latitude: Prisma.FieldRef<"CityMission", 'Float'>
  readonly longitude: Prisma.FieldRef<"CityMission", 'Float'>
  readonly createdAt: Prisma.FieldRef<"CityMission", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"CityMission", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CityMission findUnique
 */
export type CityMissionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CityMission
   */
  select?: Prisma.CityMissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CityMission
   */
  omit?: Prisma.CityMissionOmit<ExtArgs> | null
  /**
   * Filter, which CityMission to fetch.
   */
  where: Prisma.CityMissionWhereUniqueInput
}

/**
 * CityMission findUniqueOrThrow
 */
export type CityMissionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CityMission
   */
  select?: Prisma.CityMissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CityMission
   */
  omit?: Prisma.CityMissionOmit<ExtArgs> | null
  /**
   * Filter, which CityMission to fetch.
   */
  where: Prisma.CityMissionWhereUniqueInput
}

/**
 * CityMission findFirst
 */
export type CityMissionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CityMission
   */
  select?: Prisma.CityMissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CityMission
   */
  omit?: Prisma.CityMissionOmit<ExtArgs> | null
  /**
   * Filter, which CityMission to fetch.
   */
  where?: Prisma.CityMissionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CityMissions to fetch.
   */
  orderBy?: Prisma.CityMissionOrderByWithRelationInput | Prisma.CityMissionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CityMissions.
   */
  cursor?: Prisma.CityMissionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CityMissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CityMissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CityMissions.
   */
  distinct?: Prisma.CityMissionScalarFieldEnum | Prisma.CityMissionScalarFieldEnum[]
}

/**
 * CityMission findFirstOrThrow
 */
export type CityMissionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CityMission
   */
  select?: Prisma.CityMissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CityMission
   */
  omit?: Prisma.CityMissionOmit<ExtArgs> | null
  /**
   * Filter, which CityMission to fetch.
   */
  where?: Prisma.CityMissionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CityMissions to fetch.
   */
  orderBy?: Prisma.CityMissionOrderByWithRelationInput | Prisma.CityMissionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CityMissions.
   */
  cursor?: Prisma.CityMissionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CityMissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CityMissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CityMissions.
   */
  distinct?: Prisma.CityMissionScalarFieldEnum | Prisma.CityMissionScalarFieldEnum[]
}

/**
 * CityMission findMany
 */
export type CityMissionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CityMission
   */
  select?: Prisma.CityMissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CityMission
   */
  omit?: Prisma.CityMissionOmit<ExtArgs> | null
  /**
   * Filter, which CityMissions to fetch.
   */
  where?: Prisma.CityMissionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CityMissions to fetch.
   */
  orderBy?: Prisma.CityMissionOrderByWithRelationInput | Prisma.CityMissionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CityMissions.
   */
  cursor?: Prisma.CityMissionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CityMissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CityMissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CityMissions.
   */
  distinct?: Prisma.CityMissionScalarFieldEnum | Prisma.CityMissionScalarFieldEnum[]
}

/**
 * CityMission create
 */
export type CityMissionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CityMission
   */
  select?: Prisma.CityMissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CityMission
   */
  omit?: Prisma.CityMissionOmit<ExtArgs> | null
  /**
   * The data needed to create a CityMission.
   */
  data: Prisma.XOR<Prisma.CityMissionCreateInput, Prisma.CityMissionUncheckedCreateInput>
}

/**
 * CityMission createMany
 */
export type CityMissionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CityMissions.
   */
  data: Prisma.CityMissionCreateManyInput | Prisma.CityMissionCreateManyInput[]
}

/**
 * CityMission createManyAndReturn
 */
export type CityMissionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CityMission
   */
  select?: Prisma.CityMissionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CityMission
   */
  omit?: Prisma.CityMissionOmit<ExtArgs> | null
  /**
   * The data used to create many CityMissions.
   */
  data: Prisma.CityMissionCreateManyInput | Prisma.CityMissionCreateManyInput[]
}

/**
 * CityMission update
 */
export type CityMissionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CityMission
   */
  select?: Prisma.CityMissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CityMission
   */
  omit?: Prisma.CityMissionOmit<ExtArgs> | null
  /**
   * The data needed to update a CityMission.
   */
  data: Prisma.XOR<Prisma.CityMissionUpdateInput, Prisma.CityMissionUncheckedUpdateInput>
  /**
   * Choose, which CityMission to update.
   */
  where: Prisma.CityMissionWhereUniqueInput
}

/**
 * CityMission updateMany
 */
export type CityMissionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CityMissions.
   */
  data: Prisma.XOR<Prisma.CityMissionUpdateManyMutationInput, Prisma.CityMissionUncheckedUpdateManyInput>
  /**
   * Filter which CityMissions to update
   */
  where?: Prisma.CityMissionWhereInput
  /**
   * Limit how many CityMissions to update.
   */
  limit?: number
}

/**
 * CityMission updateManyAndReturn
 */
export type CityMissionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CityMission
   */
  select?: Prisma.CityMissionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CityMission
   */
  omit?: Prisma.CityMissionOmit<ExtArgs> | null
  /**
   * The data used to update CityMissions.
   */
  data: Prisma.XOR<Prisma.CityMissionUpdateManyMutationInput, Prisma.CityMissionUncheckedUpdateManyInput>
  /**
   * Filter which CityMissions to update
   */
  where?: Prisma.CityMissionWhereInput
  /**
   * Limit how many CityMissions to update.
   */
  limit?: number
}

/**
 * CityMission upsert
 */
export type CityMissionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CityMission
   */
  select?: Prisma.CityMissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CityMission
   */
  omit?: Prisma.CityMissionOmit<ExtArgs> | null
  /**
   * The filter to search for the CityMission to update in case it exists.
   */
  where: Prisma.CityMissionWhereUniqueInput
  /**
   * In case the CityMission found by the `where` argument doesn't exist, create a new CityMission with this data.
   */
  create: Prisma.XOR<Prisma.CityMissionCreateInput, Prisma.CityMissionUncheckedCreateInput>
  /**
   * In case the CityMission was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CityMissionUpdateInput, Prisma.CityMissionUncheckedUpdateInput>
}

/**
 * CityMission delete
 */
export type CityMissionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CityMission
   */
  select?: Prisma.CityMissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CityMission
   */
  omit?: Prisma.CityMissionOmit<ExtArgs> | null
  /**
   * Filter which CityMission to delete.
   */
  where: Prisma.CityMissionWhereUniqueInput
}

/**
 * CityMission deleteMany
 */
export type CityMissionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CityMissions to delete
   */
  where?: Prisma.CityMissionWhereInput
  /**
   * Limit how many CityMissions to delete.
   */
  limit?: number
}

/**
 * CityMission without action
 */
export type CityMissionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CityMission
   */
  select?: Prisma.CityMissionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CityMission
   */
  omit?: Prisma.CityMissionOmit<ExtArgs> | null
}
