
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CommunityReport` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CommunityReport
 * 
 */
export type CommunityReportModel = runtime.Types.Result.DefaultSelection<Prisma.$CommunityReportPayload>

export type AggregateCommunityReport = {
  _count: CommunityReportCountAggregateOutputType | null
  _avg: CommunityReportAvgAggregateOutputType | null
  _sum: CommunityReportSumAggregateOutputType | null
  _min: CommunityReportMinAggregateOutputType | null
  _max: CommunityReportMaxAggregateOutputType | null
}

export type CommunityReportAvgAggregateOutputType = {
  latitude: number | null
  longitude: number | null
  corroborations: number | null
}

export type CommunityReportSumAggregateOutputType = {
  latitude: number | null
  longitude: number | null
  corroborations: number | null
}

export type CommunityReportMinAggregateOutputType = {
  id: string | null
  city: string | null
  category: string | null
  description: string | null
  latitude: number | null
  longitude: number | null
  address: string | null
  reportTime: Date | null
  status: string | null
  corroborations: number | null
  imageUrl: string | null
  audioUrl: string | null
  submittedBy: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CommunityReportMaxAggregateOutputType = {
  id: string | null
  city: string | null
  category: string | null
  description: string | null
  latitude: number | null
  longitude: number | null
  address: string | null
  reportTime: Date | null
  status: string | null
  corroborations: number | null
  imageUrl: string | null
  audioUrl: string | null
  submittedBy: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CommunityReportCountAggregateOutputType = {
  id: number
  city: number
  category: number
  description: number
  latitude: number
  longitude: number
  address: number
  reportTime: number
  status: number
  corroborations: number
  imageUrl: number
  audioUrl: number
  submittedBy: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type CommunityReportAvgAggregateInputType = {
  latitude?: true
  longitude?: true
  corroborations?: true
}

export type CommunityReportSumAggregateInputType = {
  latitude?: true
  longitude?: true
  corroborations?: true
}

export type CommunityReportMinAggregateInputType = {
  id?: true
  city?: true
  category?: true
  description?: true
  latitude?: true
  longitude?: true
  address?: true
  reportTime?: true
  status?: true
  corroborations?: true
  imageUrl?: true
  audioUrl?: true
  submittedBy?: true
  createdAt?: true
  updatedAt?: true
}

export type CommunityReportMaxAggregateInputType = {
  id?: true
  city?: true
  category?: true
  description?: true
  latitude?: true
  longitude?: true
  address?: true
  reportTime?: true
  status?: true
  corroborations?: true
  imageUrl?: true
  audioUrl?: true
  submittedBy?: true
  createdAt?: true
  updatedAt?: true
}

export type CommunityReportCountAggregateInputType = {
  id?: true
  city?: true
  category?: true
  description?: true
  latitude?: true
  longitude?: true
  address?: true
  reportTime?: true
  status?: true
  corroborations?: true
  imageUrl?: true
  audioUrl?: true
  submittedBy?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type CommunityReportAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CommunityReport to aggregate.
   */
  where?: Prisma.CommunityReportWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CommunityReports to fetch.
   */
  orderBy?: Prisma.CommunityReportOrderByWithRelationInput | Prisma.CommunityReportOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CommunityReportWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CommunityReports from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CommunityReports.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CommunityReports
  **/
  _count?: true | CommunityReportCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CommunityReportAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CommunityReportSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CommunityReportMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CommunityReportMaxAggregateInputType
}

export type GetCommunityReportAggregateType<T extends CommunityReportAggregateArgs> = {
      [P in keyof T & keyof AggregateCommunityReport]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCommunityReport[P]>
    : Prisma.GetScalarType<T[P], AggregateCommunityReport[P]>
}




export type CommunityReportGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CommunityReportWhereInput
  orderBy?: Prisma.CommunityReportOrderByWithAggregationInput | Prisma.CommunityReportOrderByWithAggregationInput[]
  by: Prisma.CommunityReportScalarFieldEnum[] | Prisma.CommunityReportScalarFieldEnum
  having?: Prisma.CommunityReportScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CommunityReportCountAggregateInputType | true
  _avg?: CommunityReportAvgAggregateInputType
  _sum?: CommunityReportSumAggregateInputType
  _min?: CommunityReportMinAggregateInputType
  _max?: CommunityReportMaxAggregateInputType
}

export type CommunityReportGroupByOutputType = {
  id: string
  city: string
  category: string
  description: string
  latitude: number
  longitude: number
  address: string | null
  reportTime: Date
  status: string
  corroborations: number
  imageUrl: string | null
  audioUrl: string | null
  submittedBy: string
  createdAt: Date
  updatedAt: Date
  _count: CommunityReportCountAggregateOutputType | null
  _avg: CommunityReportAvgAggregateOutputType | null
  _sum: CommunityReportSumAggregateOutputType | null
  _min: CommunityReportMinAggregateOutputType | null
  _max: CommunityReportMaxAggregateOutputType | null
}

type GetCommunityReportGroupByPayload<T extends CommunityReportGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CommunityReportGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CommunityReportGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CommunityReportGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CommunityReportGroupByOutputType[P]>
      }
    >
  >



export type CommunityReportWhereInput = {
  AND?: Prisma.CommunityReportWhereInput | Prisma.CommunityReportWhereInput[]
  OR?: Prisma.CommunityReportWhereInput[]
  NOT?: Prisma.CommunityReportWhereInput | Prisma.CommunityReportWhereInput[]
  id?: Prisma.StringFilter<"CommunityReport"> | string
  city?: Prisma.StringFilter<"CommunityReport"> | string
  category?: Prisma.StringFilter<"CommunityReport"> | string
  description?: Prisma.StringFilter<"CommunityReport"> | string
  latitude?: Prisma.FloatFilter<"CommunityReport"> | number
  longitude?: Prisma.FloatFilter<"CommunityReport"> | number
  address?: Prisma.StringNullableFilter<"CommunityReport"> | string | null
  reportTime?: Prisma.DateTimeFilter<"CommunityReport"> | Date | string
  status?: Prisma.StringFilter<"CommunityReport"> | string
  corroborations?: Prisma.IntFilter<"CommunityReport"> | number
  imageUrl?: Prisma.StringNullableFilter<"CommunityReport"> | string | null
  audioUrl?: Prisma.StringNullableFilter<"CommunityReport"> | string | null
  submittedBy?: Prisma.StringFilter<"CommunityReport"> | string
  createdAt?: Prisma.DateTimeFilter<"CommunityReport"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CommunityReport"> | Date | string
}

export type CommunityReportOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  city?: Prisma.SortOrder
  category?: Prisma.SortOrder
  description?: Prisma.SortOrder
  latitude?: Prisma.SortOrder
  longitude?: Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  reportTime?: Prisma.SortOrder
  status?: Prisma.SortOrder
  corroborations?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  audioUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  submittedBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CommunityReportWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.CommunityReportWhereInput | Prisma.CommunityReportWhereInput[]
  OR?: Prisma.CommunityReportWhereInput[]
  NOT?: Prisma.CommunityReportWhereInput | Prisma.CommunityReportWhereInput[]
  city?: Prisma.StringFilter<"CommunityReport"> | string
  category?: Prisma.StringFilter<"CommunityReport"> | string
  description?: Prisma.StringFilter<"CommunityReport"> | string
  latitude?: Prisma.FloatFilter<"CommunityReport"> | number
  longitude?: Prisma.FloatFilter<"CommunityReport"> | number
  address?: Prisma.StringNullableFilter<"CommunityReport"> | string | null
  reportTime?: Prisma.DateTimeFilter<"CommunityReport"> | Date | string
  status?: Prisma.StringFilter<"CommunityReport"> | string
  corroborations?: Prisma.IntFilter<"CommunityReport"> | number
  imageUrl?: Prisma.StringNullableFilter<"CommunityReport"> | string | null
  audioUrl?: Prisma.StringNullableFilter<"CommunityReport"> | string | null
  submittedBy?: Prisma.StringFilter<"CommunityReport"> | string
  createdAt?: Prisma.DateTimeFilter<"CommunityReport"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CommunityReport"> | Date | string
}, "id">

export type CommunityReportOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  city?: Prisma.SortOrder
  category?: Prisma.SortOrder
  description?: Prisma.SortOrder
  latitude?: Prisma.SortOrder
  longitude?: Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  reportTime?: Prisma.SortOrder
  status?: Prisma.SortOrder
  corroborations?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  audioUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  submittedBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.CommunityReportCountOrderByAggregateInput
  _avg?: Prisma.CommunityReportAvgOrderByAggregateInput
  _max?: Prisma.CommunityReportMaxOrderByAggregateInput
  _min?: Prisma.CommunityReportMinOrderByAggregateInput
  _sum?: Prisma.CommunityReportSumOrderByAggregateInput
}

export type CommunityReportScalarWhereWithAggregatesInput = {
  AND?: Prisma.CommunityReportScalarWhereWithAggregatesInput | Prisma.CommunityReportScalarWhereWithAggregatesInput[]
  OR?: Prisma.CommunityReportScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CommunityReportScalarWhereWithAggregatesInput | Prisma.CommunityReportScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CommunityReport"> | string
  city?: Prisma.StringWithAggregatesFilter<"CommunityReport"> | string
  category?: Prisma.StringWithAggregatesFilter<"CommunityReport"> | string
  description?: Prisma.StringWithAggregatesFilter<"CommunityReport"> | string
  latitude?: Prisma.FloatWithAggregatesFilter<"CommunityReport"> | number
  longitude?: Prisma.FloatWithAggregatesFilter<"CommunityReport"> | number
  address?: Prisma.StringNullableWithAggregatesFilter<"CommunityReport"> | string | null
  reportTime?: Prisma.DateTimeWithAggregatesFilter<"CommunityReport"> | Date | string
  status?: Prisma.StringWithAggregatesFilter<"CommunityReport"> | string
  corroborations?: Prisma.IntWithAggregatesFilter<"CommunityReport"> | number
  imageUrl?: Prisma.StringNullableWithAggregatesFilter<"CommunityReport"> | string | null
  audioUrl?: Prisma.StringNullableWithAggregatesFilter<"CommunityReport"> | string | null
  submittedBy?: Prisma.StringWithAggregatesFilter<"CommunityReport"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CommunityReport"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"CommunityReport"> | Date | string
}

export type CommunityReportCreateInput = {
  id?: string
  city: string
  category: string
  description: string
  latitude: number
  longitude: number
  address?: string | null
  reportTime: Date | string
  status?: string
  corroborations?: number
  imageUrl?: string | null
  audioUrl?: string | null
  submittedBy?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CommunityReportUncheckedCreateInput = {
  id?: string
  city: string
  category: string
  description: string
  latitude: number
  longitude: number
  address?: string | null
  reportTime: Date | string
  status?: string
  corroborations?: number
  imageUrl?: string | null
  audioUrl?: string | null
  submittedBy?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CommunityReportUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  latitude?: Prisma.FloatFieldUpdateOperationsInput | number
  longitude?: Prisma.FloatFieldUpdateOperationsInput | number
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reportTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  corroborations?: Prisma.IntFieldUpdateOperationsInput | number
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  audioUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  submittedBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CommunityReportUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  latitude?: Prisma.FloatFieldUpdateOperationsInput | number
  longitude?: Prisma.FloatFieldUpdateOperationsInput | number
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reportTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  corroborations?: Prisma.IntFieldUpdateOperationsInput | number
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  audioUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  submittedBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CommunityReportCreateManyInput = {
  id?: string
  city: string
  category: string
  description: string
  latitude: number
  longitude: number
  address?: string | null
  reportTime: Date | string
  status?: string
  corroborations?: number
  imageUrl?: string | null
  audioUrl?: string | null
  submittedBy?: string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CommunityReportUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  latitude?: Prisma.FloatFieldUpdateOperationsInput | number
  longitude?: Prisma.FloatFieldUpdateOperationsInput | number
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reportTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  corroborations?: Prisma.IntFieldUpdateOperationsInput | number
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  audioUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  submittedBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CommunityReportUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  latitude?: Prisma.FloatFieldUpdateOperationsInput | number
  longitude?: Prisma.FloatFieldUpdateOperationsInput | number
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reportTime?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  corroborations?: Prisma.IntFieldUpdateOperationsInput | number
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  audioUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  submittedBy?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CommunityReportCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  city?: Prisma.SortOrder
  category?: Prisma.SortOrder
  description?: Prisma.SortOrder
  latitude?: Prisma.SortOrder
  longitude?: Prisma.SortOrder
  address?: Prisma.SortOrder
  reportTime?: Prisma.SortOrder
  status?: Prisma.SortOrder
  corroborations?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  audioUrl?: Prisma.SortOrder
  submittedBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CommunityReportAvgOrderByAggregateInput = {
  latitude?: Prisma.SortOrder
  longitude?: Prisma.SortOrder
  corroborations?: Prisma.SortOrder
}

export type CommunityReportMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  city?: Prisma.SortOrder
  category?: Prisma.SortOrder
  description?: Prisma.SortOrder
  latitude?: Prisma.SortOrder
  longitude?: Prisma.SortOrder
  address?: Prisma.SortOrder
  reportTime?: Prisma.SortOrder
  status?: Prisma.SortOrder
  corroborations?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  audioUrl?: Prisma.SortOrder
  submittedBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CommunityReportMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  city?: Prisma.SortOrder
  category?: Prisma.SortOrder
  description?: Prisma.SortOrder
  latitude?: Prisma.SortOrder
  longitude?: Prisma.SortOrder
  address?: Prisma.SortOrder
  reportTime?: Prisma.SortOrder
  status?: Prisma.SortOrder
  corroborations?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  audioUrl?: Prisma.SortOrder
  submittedBy?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CommunityReportSumOrderByAggregateInput = {
  latitude?: Prisma.SortOrder
  longitude?: Prisma.SortOrder
  corroborations?: Prisma.SortOrder
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}



export type CommunityReportSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  city?: boolean
  category?: boolean
  description?: boolean
  latitude?: boolean
  longitude?: boolean
  address?: boolean
  reportTime?: boolean
  status?: boolean
  corroborations?: boolean
  imageUrl?: boolean
  audioUrl?: boolean
  submittedBy?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["communityReport"]>

export type CommunityReportSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  city?: boolean
  category?: boolean
  description?: boolean
  latitude?: boolean
  longitude?: boolean
  address?: boolean
  reportTime?: boolean
  status?: boolean
  corroborations?: boolean
  imageUrl?: boolean
  audioUrl?: boolean
  submittedBy?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["communityReport"]>

export type CommunityReportSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  city?: boolean
  category?: boolean
  description?: boolean
  latitude?: boolean
  longitude?: boolean
  address?: boolean
  reportTime?: boolean
  status?: boolean
  corroborations?: boolean
  imageUrl?: boolean
  audioUrl?: boolean
  submittedBy?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["communityReport"]>

export type CommunityReportSelectScalar = {
  id?: boolean
  city?: boolean
  category?: boolean
  description?: boolean
  latitude?: boolean
  longitude?: boolean
  address?: boolean
  reportTime?: boolean
  status?: boolean
  corroborations?: boolean
  imageUrl?: boolean
  audioUrl?: boolean
  submittedBy?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type CommunityReportOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "city" | "category" | "description" | "latitude" | "longitude" | "address" | "reportTime" | "status" | "corroborations" | "imageUrl" | "audioUrl" | "submittedBy" | "createdAt" | "updatedAt", ExtArgs["result"]["communityReport"]>

export type $CommunityReportPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CommunityReport"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    city: string
    category: string
    description: string
    latitude: number
    longitude: number
    address: string | null
    reportTime: Date
    status: string
    corroborations: number
    imageUrl: string | null
    audioUrl: string | null
    submittedBy: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["communityReport"]>
  composites: {}
}

export type CommunityReportGetPayload<S extends boolean | null | undefined | CommunityReportDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CommunityReportPayload, S>

export type CommunityReportCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CommunityReportFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CommunityReportCountAggregateInputType | true
  }

export interface CommunityReportDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CommunityReport'], meta: { name: 'CommunityReport' } }
  /**
   * Find zero or one CommunityReport that matches the filter.
   * @param {CommunityReportFindUniqueArgs} args - Arguments to find a CommunityReport
   * @example
   * // Get one CommunityReport
   * const communityReport = await prisma.communityReport.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CommunityReportFindUniqueArgs>(args: Prisma.SelectSubset<T, CommunityReportFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CommunityReportClient<runtime.Types.Result.GetResult<Prisma.$CommunityReportPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CommunityReport that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CommunityReportFindUniqueOrThrowArgs} args - Arguments to find a CommunityReport
   * @example
   * // Get one CommunityReport
   * const communityReport = await prisma.communityReport.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CommunityReportFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CommunityReportFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CommunityReportClient<runtime.Types.Result.GetResult<Prisma.$CommunityReportPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CommunityReport that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CommunityReportFindFirstArgs} args - Arguments to find a CommunityReport
   * @example
   * // Get one CommunityReport
   * const communityReport = await prisma.communityReport.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CommunityReportFindFirstArgs>(args?: Prisma.SelectSubset<T, CommunityReportFindFirstArgs<ExtArgs>>): Prisma.Prisma__CommunityReportClient<runtime.Types.Result.GetResult<Prisma.$CommunityReportPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CommunityReport that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CommunityReportFindFirstOrThrowArgs} args - Arguments to find a CommunityReport
   * @example
   * // Get one CommunityReport
   * const communityReport = await prisma.communityReport.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CommunityReportFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CommunityReportFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CommunityReportClient<runtime.Types.Result.GetResult<Prisma.$CommunityReportPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CommunityReports that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CommunityReportFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CommunityReports
   * const communityReports = await prisma.communityReport.findMany()
   * 
   * // Get first 10 CommunityReports
   * const communityReports = await prisma.communityReport.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const communityReportWithIdOnly = await prisma.communityReport.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CommunityReportFindManyArgs>(args?: Prisma.SelectSubset<T, CommunityReportFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CommunityReportPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CommunityReport.
   * @param {CommunityReportCreateArgs} args - Arguments to create a CommunityReport.
   * @example
   * // Create one CommunityReport
   * const CommunityReport = await prisma.communityReport.create({
   *   data: {
   *     // ... data to create a CommunityReport
   *   }
   * })
   * 
   */
  create<T extends CommunityReportCreateArgs>(args: Prisma.SelectSubset<T, CommunityReportCreateArgs<ExtArgs>>): Prisma.Prisma__CommunityReportClient<runtime.Types.Result.GetResult<Prisma.$CommunityReportPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CommunityReports.
   * @param {CommunityReportCreateManyArgs} args - Arguments to create many CommunityReports.
   * @example
   * // Create many CommunityReports
   * const communityReport = await prisma.communityReport.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CommunityReportCreateManyArgs>(args?: Prisma.SelectSubset<T, CommunityReportCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CommunityReports and returns the data saved in the database.
   * @param {CommunityReportCreateManyAndReturnArgs} args - Arguments to create many CommunityReports.
   * @example
   * // Create many CommunityReports
   * const communityReport = await prisma.communityReport.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CommunityReports and only return the `id`
   * const communityReportWithIdOnly = await prisma.communityReport.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CommunityReportCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CommunityReportCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CommunityReportPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CommunityReport.
   * @param {CommunityReportDeleteArgs} args - Arguments to delete one CommunityReport.
   * @example
   * // Delete one CommunityReport
   * const CommunityReport = await prisma.communityReport.delete({
   *   where: {
   *     // ... filter to delete one CommunityReport
   *   }
   * })
   * 
   */
  delete<T extends CommunityReportDeleteArgs>(args: Prisma.SelectSubset<T, CommunityReportDeleteArgs<ExtArgs>>): Prisma.Prisma__CommunityReportClient<runtime.Types.Result.GetResult<Prisma.$CommunityReportPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CommunityReport.
   * @param {CommunityReportUpdateArgs} args - Arguments to update one CommunityReport.
   * @example
   * // Update one CommunityReport
   * const communityReport = await prisma.communityReport.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CommunityReportUpdateArgs>(args: Prisma.SelectSubset<T, CommunityReportUpdateArgs<ExtArgs>>): Prisma.Prisma__CommunityReportClient<runtime.Types.Result.GetResult<Prisma.$CommunityReportPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CommunityReports.
   * @param {CommunityReportDeleteManyArgs} args - Arguments to filter CommunityReports to delete.
   * @example
   * // Delete a few CommunityReports
   * const { count } = await prisma.communityReport.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CommunityReportDeleteManyArgs>(args?: Prisma.SelectSubset<T, CommunityReportDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CommunityReports.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CommunityReportUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CommunityReports
   * const communityReport = await prisma.communityReport.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CommunityReportUpdateManyArgs>(args: Prisma.SelectSubset<T, CommunityReportUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CommunityReports and returns the data updated in the database.
   * @param {CommunityReportUpdateManyAndReturnArgs} args - Arguments to update many CommunityReports.
   * @example
   * // Update many CommunityReports
   * const communityReport = await prisma.communityReport.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CommunityReports and only return the `id`
   * const communityReportWithIdOnly = await prisma.communityReport.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CommunityReportUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CommunityReportUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CommunityReportPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CommunityReport.
   * @param {CommunityReportUpsertArgs} args - Arguments to update or create a CommunityReport.
   * @example
   * // Update or create a CommunityReport
   * const communityReport = await prisma.communityReport.upsert({
   *   create: {
   *     // ... data to create a CommunityReport
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CommunityReport we want to update
   *   }
   * })
   */
  upsert<T extends CommunityReportUpsertArgs>(args: Prisma.SelectSubset<T, CommunityReportUpsertArgs<ExtArgs>>): Prisma.Prisma__CommunityReportClient<runtime.Types.Result.GetResult<Prisma.$CommunityReportPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CommunityReports.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CommunityReportCountArgs} args - Arguments to filter CommunityReports to count.
   * @example
   * // Count the number of CommunityReports
   * const count = await prisma.communityReport.count({
   *   where: {
   *     // ... the filter for the CommunityReports we want to count
   *   }
   * })
  **/
  count<T extends CommunityReportCountArgs>(
    args?: Prisma.Subset<T, CommunityReportCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CommunityReportCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CommunityReport.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CommunityReportAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CommunityReportAggregateArgs>(args: Prisma.Subset<T, CommunityReportAggregateArgs>): Prisma.PrismaPromise<GetCommunityReportAggregateType<T>>

  /**
   * Group by CommunityReport.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CommunityReportGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CommunityReportGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CommunityReportGroupByArgs['orderBy'] }
      : { orderBy?: CommunityReportGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CommunityReportGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCommunityReportGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CommunityReport model
 */
readonly fields: CommunityReportFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CommunityReport.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CommunityReportClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CommunityReport model
 */
export interface CommunityReportFieldRefs {
  readonly id: Prisma.FieldRef<"CommunityReport", 'String'>
  readonly city: Prisma.FieldRef<"CommunityReport", 'String'>
  readonly category: Prisma.FieldRef<"CommunityReport", 'String'>
  readonly description: Prisma.FieldRef<"CommunityReport", 'String'>
  readonly latitude: Prisma.FieldRef<"CommunityReport", 'Float'>
  readonly longitude: Prisma.FieldRef<"CommunityReport", 'Float'>
  readonly address: Prisma.FieldRef<"CommunityReport", 'String'>
  readonly reportTime: Prisma.FieldRef<"CommunityReport", 'DateTime'>
  readonly status: Prisma.FieldRef<"CommunityReport", 'String'>
  readonly corroborations: Prisma.FieldRef<"CommunityReport", 'Int'>
  readonly imageUrl: Prisma.FieldRef<"CommunityReport", 'String'>
  readonly audioUrl: Prisma.FieldRef<"CommunityReport", 'String'>
  readonly submittedBy: Prisma.FieldRef<"CommunityReport", 'String'>
  readonly createdAt: Prisma.FieldRef<"CommunityReport", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"CommunityReport", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CommunityReport findUnique
 */
export type CommunityReportFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommunityReport
   */
  select?: Prisma.CommunityReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommunityReport
   */
  omit?: Prisma.CommunityReportOmit<ExtArgs> | null
  /**
   * Filter, which CommunityReport to fetch.
   */
  where: Prisma.CommunityReportWhereUniqueInput
}

/**
 * CommunityReport findUniqueOrThrow
 */
export type CommunityReportFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommunityReport
   */
  select?: Prisma.CommunityReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommunityReport
   */
  omit?: Prisma.CommunityReportOmit<ExtArgs> | null
  /**
   * Filter, which CommunityReport to fetch.
   */
  where: Prisma.CommunityReportWhereUniqueInput
}

/**
 * CommunityReport findFirst
 */
export type CommunityReportFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommunityReport
   */
  select?: Prisma.CommunityReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommunityReport
   */
  omit?: Prisma.CommunityReportOmit<ExtArgs> | null
  /**
   * Filter, which CommunityReport to fetch.
   */
  where?: Prisma.CommunityReportWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CommunityReports to fetch.
   */
  orderBy?: Prisma.CommunityReportOrderByWithRelationInput | Prisma.CommunityReportOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CommunityReports.
   */
  cursor?: Prisma.CommunityReportWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CommunityReports from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CommunityReports.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CommunityReports.
   */
  distinct?: Prisma.CommunityReportScalarFieldEnum | Prisma.CommunityReportScalarFieldEnum[]
}

/**
 * CommunityReport findFirstOrThrow
 */
export type CommunityReportFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommunityReport
   */
  select?: Prisma.CommunityReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommunityReport
   */
  omit?: Prisma.CommunityReportOmit<ExtArgs> | null
  /**
   * Filter, which CommunityReport to fetch.
   */
  where?: Prisma.CommunityReportWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CommunityReports to fetch.
   */
  orderBy?: Prisma.CommunityReportOrderByWithRelationInput | Prisma.CommunityReportOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CommunityReports.
   */
  cursor?: Prisma.CommunityReportWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CommunityReports from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CommunityReports.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CommunityReports.
   */
  distinct?: Prisma.CommunityReportScalarFieldEnum | Prisma.CommunityReportScalarFieldEnum[]
}

/**
 * CommunityReport findMany
 */
export type CommunityReportFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommunityReport
   */
  select?: Prisma.CommunityReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommunityReport
   */
  omit?: Prisma.CommunityReportOmit<ExtArgs> | null
  /**
   * Filter, which CommunityReports to fetch.
   */
  where?: Prisma.CommunityReportWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CommunityReports to fetch.
   */
  orderBy?: Prisma.CommunityReportOrderByWithRelationInput | Prisma.CommunityReportOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CommunityReports.
   */
  cursor?: Prisma.CommunityReportWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CommunityReports from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CommunityReports.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CommunityReports.
   */
  distinct?: Prisma.CommunityReportScalarFieldEnum | Prisma.CommunityReportScalarFieldEnum[]
}

/**
 * CommunityReport create
 */
export type CommunityReportCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommunityReport
   */
  select?: Prisma.CommunityReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommunityReport
   */
  omit?: Prisma.CommunityReportOmit<ExtArgs> | null
  /**
   * The data needed to create a CommunityReport.
   */
  data: Prisma.XOR<Prisma.CommunityReportCreateInput, Prisma.CommunityReportUncheckedCreateInput>
}

/**
 * CommunityReport createMany
 */
export type CommunityReportCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CommunityReports.
   */
  data: Prisma.CommunityReportCreateManyInput | Prisma.CommunityReportCreateManyInput[]
}

/**
 * CommunityReport createManyAndReturn
 */
export type CommunityReportCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommunityReport
   */
  select?: Prisma.CommunityReportSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CommunityReport
   */
  omit?: Prisma.CommunityReportOmit<ExtArgs> | null
  /**
   * The data used to create many CommunityReports.
   */
  data: Prisma.CommunityReportCreateManyInput | Prisma.CommunityReportCreateManyInput[]
}

/**
 * CommunityReport update
 */
export type CommunityReportUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommunityReport
   */
  select?: Prisma.CommunityReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommunityReport
   */
  omit?: Prisma.CommunityReportOmit<ExtArgs> | null
  /**
   * The data needed to update a CommunityReport.
   */
  data: Prisma.XOR<Prisma.CommunityReportUpdateInput, Prisma.CommunityReportUncheckedUpdateInput>
  /**
   * Choose, which CommunityReport to update.
   */
  where: Prisma.CommunityReportWhereUniqueInput
}

/**
 * CommunityReport updateMany
 */
export type CommunityReportUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CommunityReports.
   */
  data: Prisma.XOR<Prisma.CommunityReportUpdateManyMutationInput, Prisma.CommunityReportUncheckedUpdateManyInput>
  /**
   * Filter which CommunityReports to update
   */
  where?: Prisma.CommunityReportWhereInput
  /**
   * Limit how many CommunityReports to update.
   */
  limit?: number
}

/**
 * CommunityReport updateManyAndReturn
 */
export type CommunityReportUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommunityReport
   */
  select?: Prisma.CommunityReportSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CommunityReport
   */
  omit?: Prisma.CommunityReportOmit<ExtArgs> | null
  /**
   * The data used to update CommunityReports.
   */
  data: Prisma.XOR<Prisma.CommunityReportUpdateManyMutationInput, Prisma.CommunityReportUncheckedUpdateManyInput>
  /**
   * Filter which CommunityReports to update
   */
  where?: Prisma.CommunityReportWhereInput
  /**
   * Limit how many CommunityReports to update.
   */
  limit?: number
}

/**
 * CommunityReport upsert
 */
export type CommunityReportUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommunityReport
   */
  select?: Prisma.CommunityReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommunityReport
   */
  omit?: Prisma.CommunityReportOmit<ExtArgs> | null
  /**
   * The filter to search for the CommunityReport to update in case it exists.
   */
  where: Prisma.CommunityReportWhereUniqueInput
  /**
   * In case the CommunityReport found by the `where` argument doesn't exist, create a new CommunityReport with this data.
   */
  create: Prisma.XOR<Prisma.CommunityReportCreateInput, Prisma.CommunityReportUncheckedCreateInput>
  /**
   * In case the CommunityReport was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CommunityReportUpdateInput, Prisma.CommunityReportUncheckedUpdateInput>
}

/**
 * CommunityReport delete
 */
export type CommunityReportDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommunityReport
   */
  select?: Prisma.CommunityReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommunityReport
   */
  omit?: Prisma.CommunityReportOmit<ExtArgs> | null
  /**
   * Filter which CommunityReport to delete.
   */
  where: Prisma.CommunityReportWhereUniqueInput
}

/**
 * CommunityReport deleteMany
 */
export type CommunityReportDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CommunityReports to delete
   */
  where?: Prisma.CommunityReportWhereInput
  /**
   * Limit how many CommunityReports to delete.
   */
  limit?: number
}

/**
 * CommunityReport without action
 */
export type CommunityReportDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommunityReport
   */
  select?: Prisma.CommunityReportSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommunityReport
   */
  omit?: Prisma.CommunityReportOmit<ExtArgs> | null
}
