// SPDX-License-Identifier: MIT
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Auto-generated Domain Store
 *
 * MobX-State-Tree store with collections for each model.
 * Generated by `shogo generate` - DO NOT EDIT
 */

import { makeAutoObservable, runInAction } from 'mobx'
import {
  getUserList,
  getUserById,
  createUser,
  updateUser,
  deleteUser,
  getCityMissionList,
  getCityMissionById,
  createCityMission,
  updateCityMission,
  deleteCityMission,
  getPlaceList,
  getPlaceById,
  createPlace,
  updatePlace,
  deletePlace,
  getCommunityReportList,
  getCommunityReportById,
  createCommunityReport,
  updateCommunityReport,
  deleteCommunityReport,
  getHeritageTrailList,
  getHeritageTrailById,
  createHeritageTrail,
  updateHeritageTrail,
  deleteHeritageTrail,
  getRouteRecommendationList,
  getRouteRecommendationById,
  createRouteRecommendation,
  updateRouteRecommendation,
  deleteRouteRecommendation,
} from './server-functions'

import type {
  UserType,
  UserCreateInput,
  UserUpdateInput,
  CityMissionType,
  CityMissionCreateInput,
  CityMissionUpdateInput,
  PlaceType,
  PlaceCreateInput,
  PlaceUpdateInput,
  CommunityReportType,
  CommunityReportCreateInput,
  CommunityReportUpdateInput,
  HeritageTrailType,
  HeritageTrailCreateInput,
  HeritageTrailUpdateInput,
  RouteRecommendationType,
  RouteRecommendationCreateInput,
  RouteRecommendationUpdateInput,
} from './types'

// ============================================================================
// User Store
// ============================================================================

export class UserStore {
  items: Map<string, UserType> = new Map()
  isLoading = false
  error: string | null = null

  // Track pending operations for optimistic updates
  private pendingDeletes = new Set<string>()
  private pendingUpdates = new Set<string>()

  constructor() {
    makeAutoObservable(this, {
      pendingDeletes: false,
      pendingUpdates: false,
    })
  }

  // === Getters ===

  /** Get all items as array */
  get all(): UserType[] {
    return Array.from(this.items.values())
  }

  /** Get item by ID */
  get(id: string): UserType | undefined {
    return this.items.get(id)
  }

  /** Check if item has pending operation */
  isPending(id: string): boolean {
    return this.pendingDeletes.has(id) || this.pendingUpdates.has(id)
  }

  // === Actions ===

  /** Load all items from server */
  async loadAll(userId?: string, where?: Record<string, unknown>) {
    runInAction(() => {
      this.isLoading = true
      this.error = null
    })

    try {
      const items = await getUserList({ data: { userId, where } })

      runInAction(() => {
        this.items.clear()
        for (const item of items) {
          this.items.set(item.id, item)
        }
        this.isLoading = false
      })
    } catch (e) {
      runInAction(() => {
        this.error = e instanceof Error ? e.message : 'Failed to load'
        this.isLoading = false
      })
      throw e
    }
  }

  /** Load single item by ID */
  async loadById(id: string, userId?: string) {
    try {
      const item = await getUserById({ data: { id, userId } })

      runInAction(() => {
        this.items.set(item.id, item)
      })

      return item
    } catch (e) {
      runInAction(() => {
        this.error = e instanceof Error ? e.message : 'Failed to load'
      })
      throw e
    }
  }

  /** Create new item with optimistic update */
  async create(input: UserCreateInput, userId?: string) {
    // Create optimistic item
    const tempId = `temp-${crypto.randomUUID()}`
    const optimisticItem: UserType = {
      id: tempId,
      ...input,
      createdAt: new Date(),
      updatedAt: new Date(),
    } as UserType

    // Add optimistically
    runInAction(() => {
      this.items.set(tempId, optimisticItem)
    })

    try {
      const item = await createUser({ data: { input, userId } })

      runInAction(() => {
        // Remove temp, add real
        this.items.delete(tempId)
        this.items.set(item.id, item)
      })

      return item
    } catch (e) {
      runInAction(() => {
        // Rollback
        this.items.delete(tempId)
        this.error = e instanceof Error ? e.message : 'Failed to create'
      })
      throw e
    }
  }

  /** Update item with optimistic update */
  async update(id: string, input: UserUpdateInput, userId?: string) {
    // Validate id to prevent undefined from reaching the API
    if (!id || typeof id !== 'string') {
      console.error('[UserStore] update called with invalid id:', id)
      return
    }
    const existing = this.items.get(id)
    if (!existing || this.pendingUpdates.has(id)) return

    const previousState = { ...existing }
    this.pendingUpdates.add(id)

    // Optimistically update
    runInAction(() => {
      this.items.set(id, {
        ...existing,
        ...input,
        updatedAt: new Date(),
      } as UserType)
    })

    try {
      const item = await updateUser({ data: { id, input, userId } })

      runInAction(() => {
        this.items.set(id, item)
        this.pendingUpdates.delete(id)
      })

      return item
    } catch (e) {
      runInAction(() => {
        // Rollback
        this.items.set(id, previousState)
        this.pendingUpdates.delete(id)
        this.error = e instanceof Error ? e.message : 'Failed to update'
      })
      throw e
    }
  }

  /** Delete item with optimistic update */
  async delete(id: string, userId?: string) {
    // Validate id to prevent undefined from reaching the API
    if (!id || typeof id !== 'string') {
      console.error('[UserStore] delete called with invalid id:', id)
      return
    }
    const existing = this.items.get(id)
    if (!existing || this.pendingDeletes.has(id)) return

    this.pendingDeletes.add(id)

    // Optimistically remove
    runInAction(() => {
      this.items.delete(id)
    })

    try {
      await deleteUser({ data: { id, userId } })

      runInAction(() => {
        this.pendingDeletes.delete(id)
      })
    } catch (e) {
      runInAction(() => {
        // Rollback
        this.items.set(id, existing)
        this.pendingDeletes.delete(id)
        this.error = e instanceof Error ? e.message : 'Failed to delete'
      })
      throw e
    }
  }

  /** Clear error state */
  clearError() {
    this.error = null
  }

  /** Clear all data */
  clear() {
    this.items.clear()
    this.error = null
    this.isLoading = false
  }
}

// ============================================================================
// CityMission Store
// ============================================================================

export class CityMissionStore {
  items: Map<string, CityMissionType> = new Map()
  isLoading = false
  error: string | null = null

  // Track pending operations for optimistic updates
  private pendingDeletes = new Set<string>()
  private pendingUpdates = new Set<string>()

  constructor() {
    makeAutoObservable(this, {
      pendingDeletes: false,
      pendingUpdates: false,
    })
  }

  // === Getters ===

  /** Get all items as array */
  get all(): CityMissionType[] {
    return Array.from(this.items.values())
  }

  /** Get item by ID */
  get(id: string): CityMissionType | undefined {
    return this.items.get(id)
  }

  /** Check if item has pending operation */
  isPending(id: string): boolean {
    return this.pendingDeletes.has(id) || this.pendingUpdates.has(id)
  }

  // === Actions ===

  /** Load all items from server */
  async loadAll(userId?: string, where?: Record<string, unknown>) {
    runInAction(() => {
      this.isLoading = true
      this.error = null
    })

    try {
      const items = await getCityMissionList({ data: { userId, where } })

      runInAction(() => {
        this.items.clear()
        for (const item of items) {
          this.items.set(item.id, item)
        }
        this.isLoading = false
      })
    } catch (e) {
      runInAction(() => {
        this.error = e instanceof Error ? e.message : 'Failed to load'
        this.isLoading = false
      })
      throw e
    }
  }

  /** Load single item by ID */
  async loadById(id: string, userId?: string) {
    try {
      const item = await getCityMissionById({ data: { id, userId } })

      runInAction(() => {
        this.items.set(item.id, item)
      })

      return item
    } catch (e) {
      runInAction(() => {
        this.error = e instanceof Error ? e.message : 'Failed to load'
      })
      throw e
    }
  }

  /** Create new item with optimistic update */
  async create(input: CityMissionCreateInput, userId?: string) {
    // Create optimistic item
    const tempId = `temp-${crypto.randomUUID()}`
    const optimisticItem: CityMissionType = {
      id: tempId,
      ...input,
      createdAt: new Date(),
      updatedAt: new Date(),
    } as CityMissionType

    // Add optimistically
    runInAction(() => {
      this.items.set(tempId, optimisticItem)
    })

    try {
      const item = await createCityMission({ data: { input, userId } })

      runInAction(() => {
        // Remove temp, add real
        this.items.delete(tempId)
        this.items.set(item.id, item)
      })

      return item
    } catch (e) {
      runInAction(() => {
        // Rollback
        this.items.delete(tempId)
        this.error = e instanceof Error ? e.message : 'Failed to create'
      })
      throw e
    }
  }

  /** Update item with optimistic update */
  async update(id: string, input: CityMissionUpdateInput, userId?: string) {
    // Validate id to prevent undefined from reaching the API
    if (!id || typeof id !== 'string') {
      console.error('[CityMissionStore] update called with invalid id:', id)
      return
    }
    const existing = this.items.get(id)
    if (!existing || this.pendingUpdates.has(id)) return

    const previousState = { ...existing }
    this.pendingUpdates.add(id)

    // Optimistically update
    runInAction(() => {
      this.items.set(id, {
        ...existing,
        ...input,
        updatedAt: new Date(),
      } as CityMissionType)
    })

    try {
      const item = await updateCityMission({ data: { id, input, userId } })

      runInAction(() => {
        this.items.set(id, item)
        this.pendingUpdates.delete(id)
      })

      return item
    } catch (e) {
      runInAction(() => {
        // Rollback
        this.items.set(id, previousState)
        this.pendingUpdates.delete(id)
        this.error = e instanceof Error ? e.message : 'Failed to update'
      })
      throw e
    }
  }

  /** Delete item with optimistic update */
  async delete(id: string, userId?: string) {
    // Validate id to prevent undefined from reaching the API
    if (!id || typeof id !== 'string') {
      console.error('[CityMissionStore] delete called with invalid id:', id)
      return
    }
    const existing = this.items.get(id)
    if (!existing || this.pendingDeletes.has(id)) return

    this.pendingDeletes.add(id)

    // Optimistically remove
    runInAction(() => {
      this.items.delete(id)
    })

    try {
      await deleteCityMission({ data: { id, userId } })

      runInAction(() => {
        this.pendingDeletes.delete(id)
      })
    } catch (e) {
      runInAction(() => {
        // Rollback
        this.items.set(id, existing)
        this.pendingDeletes.delete(id)
        this.error = e instanceof Error ? e.message : 'Failed to delete'
      })
      throw e
    }
  }

  /** Clear error state */
  clearError() {
    this.error = null
  }

  /** Clear all data */
  clear() {
    this.items.clear()
    this.error = null
    this.isLoading = false
  }
}

// ============================================================================
// Place Store
// ============================================================================

export class PlaceStore {
  items: Map<string, PlaceType> = new Map()
  isLoading = false
  error: string | null = null

  // Track pending operations for optimistic updates
  private pendingDeletes = new Set<string>()
  private pendingUpdates = new Set<string>()

  constructor() {
    makeAutoObservable(this, {
      pendingDeletes: false,
      pendingUpdates: false,
    })
  }

  // === Getters ===

  /** Get all items as array */
  get all(): PlaceType[] {
    return Array.from(this.items.values())
  }

  /** Get item by ID */
  get(id: string): PlaceType | undefined {
    return this.items.get(id)
  }

  /** Check if item has pending operation */
  isPending(id: string): boolean {
    return this.pendingDeletes.has(id) || this.pendingUpdates.has(id)
  }

  // === Actions ===

  /** Load all items from server */
  async loadAll(userId?: string, where?: Record<string, unknown>) {
    runInAction(() => {
      this.isLoading = true
      this.error = null
    })

    try {
      const items = await getPlaceList({ data: { userId, where } })

      runInAction(() => {
        this.items.clear()
        for (const item of items) {
          this.items.set(item.id, item)
        }
        this.isLoading = false
      })
    } catch (e) {
      runInAction(() => {
        this.error = e instanceof Error ? e.message : 'Failed to load'
        this.isLoading = false
      })
      throw e
    }
  }

  /** Load single item by ID */
  async loadById(id: string, userId?: string) {
    try {
      const item = await getPlaceById({ data: { id, userId } })

      runInAction(() => {
        this.items.set(item.id, item)
      })

      return item
    } catch (e) {
      runInAction(() => {
        this.error = e instanceof Error ? e.message : 'Failed to load'
      })
      throw e
    }
  }

  /** Create new item with optimistic update */
  async create(input: PlaceCreateInput, userId?: string) {
    // Create optimistic item
    const tempId = `temp-${crypto.randomUUID()}`
    const optimisticItem: PlaceType = {
      id: tempId,
      ...input,
      createdAt: new Date(),
      updatedAt: new Date(),
    } as PlaceType

    // Add optimistically
    runInAction(() => {
      this.items.set(tempId, optimisticItem)
    })

    try {
      const item = await createPlace({ data: { input, userId } })

      runInAction(() => {
        // Remove temp, add real
        this.items.delete(tempId)
        this.items.set(item.id, item)
      })

      return item
    } catch (e) {
      runInAction(() => {
        // Rollback
        this.items.delete(tempId)
        this.error = e instanceof Error ? e.message : 'Failed to create'
      })
      throw e
    }
  }

  /** Update item with optimistic update */
  async update(id: string, input: PlaceUpdateInput, userId?: string) {
    // Validate id to prevent undefined from reaching the API
    if (!id || typeof id !== 'string') {
      console.error('[PlaceStore] update called with invalid id:', id)
      return
    }
    const existing = this.items.get(id)
    if (!existing || this.pendingUpdates.has(id)) return

    const previousState = { ...existing }
    this.pendingUpdates.add(id)

    // Optimistically update
    runInAction(() => {
      this.items.set(id, {
        ...existing,
        ...input,
        updatedAt: new Date(),
      } as PlaceType)
    })

    try {
      const item = await updatePlace({ data: { id, input, userId } })

      runInAction(() => {
        this.items.set(id, item)
        this.pendingUpdates.delete(id)
      })

      return item
    } catch (e) {
      runInAction(() => {
        // Rollback
        this.items.set(id, previousState)
        this.pendingUpdates.delete(id)
        this.error = e instanceof Error ? e.message : 'Failed to update'
      })
      throw e
    }
  }

  /** Delete item with optimistic update */
  async delete(id: string, userId?: string) {
    // Validate id to prevent undefined from reaching the API
    if (!id || typeof id !== 'string') {
      console.error('[PlaceStore] delete called with invalid id:', id)
      return
    }
    const existing = this.items.get(id)
    if (!existing || this.pendingDeletes.has(id)) return

    this.pendingDeletes.add(id)

    // Optimistically remove
    runInAction(() => {
      this.items.delete(id)
    })

    try {
      await deletePlace({ data: { id, userId } })

      runInAction(() => {
        this.pendingDeletes.delete(id)
      })
    } catch (e) {
      runInAction(() => {
        // Rollback
        this.items.set(id, existing)
        this.pendingDeletes.delete(id)
        this.error = e instanceof Error ? e.message : 'Failed to delete'
      })
      throw e
    }
  }

  /** Clear error state */
  clearError() {
    this.error = null
  }

  /** Clear all data */
  clear() {
    this.items.clear()
    this.error = null
    this.isLoading = false
  }
}

// ============================================================================
// CommunityReport Store
// ============================================================================

export class CommunityReportStore {
  items: Map<string, CommunityReportType> = new Map()
  isLoading = false
  error: string | null = null

  // Track pending operations for optimistic updates
  private pendingDeletes = new Set<string>()
  private pendingUpdates = new Set<string>()

  constructor() {
    makeAutoObservable(this, {
      pendingDeletes: false,
      pendingUpdates: false,
    })
  }

  // === Getters ===

  /** Get all items as array */
  get all(): CommunityReportType[] {
    return Array.from(this.items.values())
  }

  /** Get item by ID */
  get(id: string): CommunityReportType | undefined {
    return this.items.get(id)
  }

  /** Check if item has pending operation */
  isPending(id: string): boolean {
    return this.pendingDeletes.has(id) || this.pendingUpdates.has(id)
  }

  // === Actions ===

  /** Load all items from server */
  async loadAll(userId?: string, where?: Record<string, unknown>) {
    runInAction(() => {
      this.isLoading = true
      this.error = null
    })

    try {
      const items = await getCommunityReportList({ data: { userId, where } })

      runInAction(() => {
        this.items.clear()
        for (const item of items) {
          this.items.set(item.id, item)
        }
        this.isLoading = false
      })
    } catch (e) {
      runInAction(() => {
        this.error = e instanceof Error ? e.message : 'Failed to load'
        this.isLoading = false
      })
      throw e
    }
  }

  /** Load single item by ID */
  async loadById(id: string, userId?: string) {
    try {
      const item = await getCommunityReportById({ data: { id, userId } })

      runInAction(() => {
        this.items.set(item.id, item)
      })

      return item
    } catch (e) {
      runInAction(() => {
        this.error = e instanceof Error ? e.message : 'Failed to load'
      })
      throw e
    }
  }

  /** Create new item with optimistic update */
  async create(input: CommunityReportCreateInput, userId?: string) {
    // Create optimistic item
    const tempId = `temp-${crypto.randomUUID()}`
    const optimisticItem: CommunityReportType = {
      id: tempId,
      ...input,
      createdAt: new Date(),
      updatedAt: new Date(),
    } as CommunityReportType

    // Add optimistically
    runInAction(() => {
      this.items.set(tempId, optimisticItem)
    })

    try {
      const item = await createCommunityReport({ data: { input, userId } })

      runInAction(() => {
        // Remove temp, add real
        this.items.delete(tempId)
        this.items.set(item.id, item)
      })

      return item
    } catch (e) {
      runInAction(() => {
        // Rollback
        this.items.delete(tempId)
        this.error = e instanceof Error ? e.message : 'Failed to create'
      })
      throw e
    }
  }

  /** Update item with optimistic update */
  async update(id: string, input: CommunityReportUpdateInput, userId?: string) {
    // Validate id to prevent undefined from reaching the API
    if (!id || typeof id !== 'string') {
      console.error('[CommunityReportStore] update called with invalid id:', id)
      return
    }
    const existing = this.items.get(id)
    if (!existing || this.pendingUpdates.has(id)) return

    const previousState = { ...existing }
    this.pendingUpdates.add(id)

    // Optimistically update
    runInAction(() => {
      this.items.set(id, {
        ...existing,
        ...input,
        updatedAt: new Date(),
      } as CommunityReportType)
    })

    try {
      const item = await updateCommunityReport({ data: { id, input, userId } })

      runInAction(() => {
        this.items.set(id, item)
        this.pendingUpdates.delete(id)
      })

      return item
    } catch (e) {
      runInAction(() => {
        // Rollback
        this.items.set(id, previousState)
        this.pendingUpdates.delete(id)
        this.error = e instanceof Error ? e.message : 'Failed to update'
      })
      throw e
    }
  }

  /** Delete item with optimistic update */
  async delete(id: string, userId?: string) {
    // Validate id to prevent undefined from reaching the API
    if (!id || typeof id !== 'string') {
      console.error('[CommunityReportStore] delete called with invalid id:', id)
      return
    }
    const existing = this.items.get(id)
    if (!existing || this.pendingDeletes.has(id)) return

    this.pendingDeletes.add(id)

    // Optimistically remove
    runInAction(() => {
      this.items.delete(id)
    })

    try {
      await deleteCommunityReport({ data: { id, userId } })

      runInAction(() => {
        this.pendingDeletes.delete(id)
      })
    } catch (e) {
      runInAction(() => {
        // Rollback
        this.items.set(id, existing)
        this.pendingDeletes.delete(id)
        this.error = e instanceof Error ? e.message : 'Failed to delete'
      })
      throw e
    }
  }

  /** Clear error state */
  clearError() {
    this.error = null
  }

  /** Clear all data */
  clear() {
    this.items.clear()
    this.error = null
    this.isLoading = false
  }
}

// ============================================================================
// HeritageTrail Store
// ============================================================================

export class HeritageTrailStore {
  items: Map<string, HeritageTrailType> = new Map()
  isLoading = false
  error: string | null = null

  // Track pending operations for optimistic updates
  private pendingDeletes = new Set<string>()
  private pendingUpdates = new Set<string>()

  constructor() {
    makeAutoObservable(this, {
      pendingDeletes: false,
      pendingUpdates: false,
    })
  }

  // === Getters ===

  /** Get all items as array */
  get all(): HeritageTrailType[] {
    return Array.from(this.items.values())
  }

  /** Get item by ID */
  get(id: string): HeritageTrailType | undefined {
    return this.items.get(id)
  }

  /** Check if item has pending operation */
  isPending(id: string): boolean {
    return this.pendingDeletes.has(id) || this.pendingUpdates.has(id)
  }

  // === Actions ===

  /** Load all items from server */
  async loadAll(userId?: string, where?: Record<string, unknown>) {
    runInAction(() => {
      this.isLoading = true
      this.error = null
    })

    try {
      const items = await getHeritageTrailList({ data: { userId, where } })

      runInAction(() => {
        this.items.clear()
        for (const item of items) {
          this.items.set(item.id, item)
        }
        this.isLoading = false
      })
    } catch (e) {
      runInAction(() => {
        this.error = e instanceof Error ? e.message : 'Failed to load'
        this.isLoading = false
      })
      throw e
    }
  }

  /** Load single item by ID */
  async loadById(id: string, userId?: string) {
    try {
      const item = await getHeritageTrailById({ data: { id, userId } })

      runInAction(() => {
        this.items.set(item.id, item)
      })

      return item
    } catch (e) {
      runInAction(() => {
        this.error = e instanceof Error ? e.message : 'Failed to load'
      })
      throw e
    }
  }

  /** Create new item with optimistic update */
  async create(input: HeritageTrailCreateInput, userId?: string) {
    // Create optimistic item
    const tempId = `temp-${crypto.randomUUID()}`
    const optimisticItem: HeritageTrailType = {
      id: tempId,
      ...input,
      createdAt: new Date(),
      updatedAt: new Date(),
    } as HeritageTrailType

    // Add optimistically
    runInAction(() => {
      this.items.set(tempId, optimisticItem)
    })

    try {
      const item = await createHeritageTrail({ data: { input, userId } })

      runInAction(() => {
        // Remove temp, add real
        this.items.delete(tempId)
        this.items.set(item.id, item)
      })

      return item
    } catch (e) {
      runInAction(() => {
        // Rollback
        this.items.delete(tempId)
        this.error = e instanceof Error ? e.message : 'Failed to create'
      })
      throw e
    }
  }

  /** Update item with optimistic update */
  async update(id: string, input: HeritageTrailUpdateInput, userId?: string) {
    // Validate id to prevent undefined from reaching the API
    if (!id || typeof id !== 'string') {
      console.error('[HeritageTrailStore] update called with invalid id:', id)
      return
    }
    const existing = this.items.get(id)
    if (!existing || this.pendingUpdates.has(id)) return

    const previousState = { ...existing }
    this.pendingUpdates.add(id)

    // Optimistically update
    runInAction(() => {
      this.items.set(id, {
        ...existing,
        ...input,
        updatedAt: new Date(),
      } as HeritageTrailType)
    })

    try {
      const item = await updateHeritageTrail({ data: { id, input, userId } })

      runInAction(() => {
        this.items.set(id, item)
        this.pendingUpdates.delete(id)
      })

      return item
    } catch (e) {
      runInAction(() => {
        // Rollback
        this.items.set(id, previousState)
        this.pendingUpdates.delete(id)
        this.error = e instanceof Error ? e.message : 'Failed to update'
      })
      throw e
    }
  }

  /** Delete item with optimistic update */
  async delete(id: string, userId?: string) {
    // Validate id to prevent undefined from reaching the API
    if (!id || typeof id !== 'string') {
      console.error('[HeritageTrailStore] delete called with invalid id:', id)
      return
    }
    const existing = this.items.get(id)
    if (!existing || this.pendingDeletes.has(id)) return

    this.pendingDeletes.add(id)

    // Optimistically remove
    runInAction(() => {
      this.items.delete(id)
    })

    try {
      await deleteHeritageTrail({ data: { id, userId } })

      runInAction(() => {
        this.pendingDeletes.delete(id)
      })
    } catch (e) {
      runInAction(() => {
        // Rollback
        this.items.set(id, existing)
        this.pendingDeletes.delete(id)
        this.error = e instanceof Error ? e.message : 'Failed to delete'
      })
      throw e
    }
  }

  /** Clear error state */
  clearError() {
    this.error = null
  }

  /** Clear all data */
  clear() {
    this.items.clear()
    this.error = null
    this.isLoading = false
  }
}

// ============================================================================
// RouteRecommendation Store
// ============================================================================

export class RouteRecommendationStore {
  items: Map<string, RouteRecommendationType> = new Map()
  isLoading = false
  error: string | null = null

  // Track pending operations for optimistic updates
  private pendingDeletes = new Set<string>()
  private pendingUpdates = new Set<string>()

  constructor() {
    makeAutoObservable(this, {
      pendingDeletes: false,
      pendingUpdates: false,
    })
  }

  // === Getters ===

  /** Get all items as array */
  get all(): RouteRecommendationType[] {
    return Array.from(this.items.values())
  }

  /** Get item by ID */
  get(id: string): RouteRecommendationType | undefined {
    return this.items.get(id)
  }

  /** Check if item has pending operation */
  isPending(id: string): boolean {
    return this.pendingDeletes.has(id) || this.pendingUpdates.has(id)
  }

  // === Actions ===

  /** Load all items from server */
  async loadAll(userId?: string, where?: Record<string, unknown>) {
    runInAction(() => {
      this.isLoading = true
      this.error = null
    })

    try {
      const items = await getRouteRecommendationList({ data: { userId, where } })

      runInAction(() => {
        this.items.clear()
        for (const item of items) {
          this.items.set(item.id, item)
        }
        this.isLoading = false
      })
    } catch (e) {
      runInAction(() => {
        this.error = e instanceof Error ? e.message : 'Failed to load'
        this.isLoading = false
      })
      throw e
    }
  }

  /** Load single item by ID */
  async loadById(id: string, userId?: string) {
    try {
      const item = await getRouteRecommendationById({ data: { id, userId } })

      runInAction(() => {
        this.items.set(item.id, item)
      })

      return item
    } catch (e) {
      runInAction(() => {
        this.error = e instanceof Error ? e.message : 'Failed to load'
      })
      throw e
    }
  }

  /** Create new item with optimistic update */
  async create(input: RouteRecommendationCreateInput, userId?: string) {
    // Create optimistic item
    const tempId = `temp-${crypto.randomUUID()}`
    const optimisticItem: RouteRecommendationType = {
      id: tempId,
      ...input,
      createdAt: new Date(),
      updatedAt: new Date(),
    } as RouteRecommendationType

    // Add optimistically
    runInAction(() => {
      this.items.set(tempId, optimisticItem)
    })

    try {
      const item = await createRouteRecommendation({ data: { input, userId } })

      runInAction(() => {
        // Remove temp, add real
        this.items.delete(tempId)
        this.items.set(item.id, item)
      })

      return item
    } catch (e) {
      runInAction(() => {
        // Rollback
        this.items.delete(tempId)
        this.error = e instanceof Error ? e.message : 'Failed to create'
      })
      throw e
    }
  }

  /** Update item with optimistic update */
  async update(id: string, input: RouteRecommendationUpdateInput, userId?: string) {
    // Validate id to prevent undefined from reaching the API
    if (!id || typeof id !== 'string') {
      console.error('[RouteRecommendationStore] update called with invalid id:', id)
      return
    }
    const existing = this.items.get(id)
    if (!existing || this.pendingUpdates.has(id)) return

    const previousState = { ...existing }
    this.pendingUpdates.add(id)

    // Optimistically update
    runInAction(() => {
      this.items.set(id, {
        ...existing,
        ...input,
        updatedAt: new Date(),
      } as RouteRecommendationType)
    })

    try {
      const item = await updateRouteRecommendation({ data: { id, input, userId } })

      runInAction(() => {
        this.items.set(id, item)
        this.pendingUpdates.delete(id)
      })

      return item
    } catch (e) {
      runInAction(() => {
        // Rollback
        this.items.set(id, previousState)
        this.pendingUpdates.delete(id)
        this.error = e instanceof Error ? e.message : 'Failed to update'
      })
      throw e
    }
  }

  /** Delete item with optimistic update */
  async delete(id: string, userId?: string) {
    // Validate id to prevent undefined from reaching the API
    if (!id || typeof id !== 'string') {
      console.error('[RouteRecommendationStore] delete called with invalid id:', id)
      return
    }
    const existing = this.items.get(id)
    if (!existing || this.pendingDeletes.has(id)) return

    this.pendingDeletes.add(id)

    // Optimistically remove
    runInAction(() => {
      this.items.delete(id)
    })

    try {
      await deleteRouteRecommendation({ data: { id, userId } })

      runInAction(() => {
        this.pendingDeletes.delete(id)
      })
    } catch (e) {
      runInAction(() => {
        // Rollback
        this.items.set(id, existing)
        this.pendingDeletes.delete(id)
        this.error = e instanceof Error ? e.message : 'Failed to delete'
      })
      throw e
    }
  }

  /** Clear error state */
  clearError() {
    this.error = null
  }

  /** Clear all data */
  clear() {
    this.items.clear()
    this.error = null
    this.isLoading = false
  }
}

// ============================================================================
// Root Store
// ============================================================================

export class RootStore {
  user: UserStore
  cityMission: CityMissionStore
  place: PlaceStore
  communityReport: CommunityReportStore
  heritageTrail: HeritageTrailStore
  routeRecommendation: RouteRecommendationStore

  constructor() {
    this.user = new UserStore()
    this.cityMission = new CityMissionStore()
    this.place = new PlaceStore()
    this.communityReport = new CommunityReportStore()
    this.heritageTrail = new HeritageTrailStore()
    this.routeRecommendation = new RouteRecommendationStore()
    makeAutoObservable(this)
  }

  /** Clear all stores */
  clearAll() {
    this.user.clear()
    this.cityMission.clear()
    this.place.clear()
    this.communityReport.clear()
    this.heritageTrail.clear()
    this.routeRecommendation.clear()
  }
}

// ============================================================================
// Factory & Singleton
// ============================================================================

let rootStore: RootStore | null = null

/**
 * Get or create the root store singleton
 */
export function getStore(): RootStore {
  if (!rootStore) {
    rootStore = new RootStore()
  }
  return rootStore
}

/**
 * Create a new root store (for testing or SSR)
 */
export function createStore(): RootStore {
  return new RootStore()
}

/**
 * Reset the singleton store
 */
export function resetStore(): void {
  rootStore = null
}
