
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `HeritageTrail` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model HeritageTrail
 * 
 */
export type HeritageTrailModel = runtime.Types.Result.DefaultSelection<Prisma.$HeritageTrailPayload>

export type AggregateHeritageTrail = {
  _count: HeritageTrailCountAggregateOutputType | null
  _avg: HeritageTrailAvgAggregateOutputType | null
  _sum: HeritageTrailSumAggregateOutputType | null
  _min: HeritageTrailMinAggregateOutputType | null
  _max: HeritageTrailMaxAggregateOutputType | null
}

export type HeritageTrailAvgAggregateOutputType = {
  distance: number | null
}

export type HeritageTrailSumAggregateOutputType = {
  distance: number | null
}

export type HeritageTrailMinAggregateOutputType = {
  id: string | null
  city: string | null
  name: string | null
  description: string | null
  sites: string | null
  distance: number | null
  duration: string | null
  culturalContext: string | null
  source: string | null
  sourceUrl: string | null
  createdAt: Date | null
}

export type HeritageTrailMaxAggregateOutputType = {
  id: string | null
  city: string | null
  name: string | null
  description: string | null
  sites: string | null
  distance: number | null
  duration: string | null
  culturalContext: string | null
  source: string | null
  sourceUrl: string | null
  createdAt: Date | null
}

export type HeritageTrailCountAggregateOutputType = {
  id: number
  city: number
  name: number
  description: number
  sites: number
  distance: number
  duration: number
  culturalContext: number
  source: number
  sourceUrl: number
  createdAt: number
  _all: number
}


export type HeritageTrailAvgAggregateInputType = {
  distance?: true
}

export type HeritageTrailSumAggregateInputType = {
  distance?: true
}

export type HeritageTrailMinAggregateInputType = {
  id?: true
  city?: true
  name?: true
  description?: true
  sites?: true
  distance?: true
  duration?: true
  culturalContext?: true
  source?: true
  sourceUrl?: true
  createdAt?: true
}

export type HeritageTrailMaxAggregateInputType = {
  id?: true
  city?: true
  name?: true
  description?: true
  sites?: true
  distance?: true
  duration?: true
  culturalContext?: true
  source?: true
  sourceUrl?: true
  createdAt?: true
}

export type HeritageTrailCountAggregateInputType = {
  id?: true
  city?: true
  name?: true
  description?: true
  sites?: true
  distance?: true
  duration?: true
  culturalContext?: true
  source?: true
  sourceUrl?: true
  createdAt?: true
  _all?: true
}

export type HeritageTrailAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which HeritageTrail to aggregate.
   */
  where?: Prisma.HeritageTrailWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of HeritageTrails to fetch.
   */
  orderBy?: Prisma.HeritageTrailOrderByWithRelationInput | Prisma.HeritageTrailOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.HeritageTrailWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` HeritageTrails from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` HeritageTrails.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned HeritageTrails
  **/
  _count?: true | HeritageTrailCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: HeritageTrailAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: HeritageTrailSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: HeritageTrailMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: HeritageTrailMaxAggregateInputType
}

export type GetHeritageTrailAggregateType<T extends HeritageTrailAggregateArgs> = {
      [P in keyof T & keyof AggregateHeritageTrail]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateHeritageTrail[P]>
    : Prisma.GetScalarType<T[P], AggregateHeritageTrail[P]>
}




export type HeritageTrailGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.HeritageTrailWhereInput
  orderBy?: Prisma.HeritageTrailOrderByWithAggregationInput | Prisma.HeritageTrailOrderByWithAggregationInput[]
  by: Prisma.HeritageTrailScalarFieldEnum[] | Prisma.HeritageTrailScalarFieldEnum
  having?: Prisma.HeritageTrailScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: HeritageTrailCountAggregateInputType | true
  _avg?: HeritageTrailAvgAggregateInputType
  _sum?: HeritageTrailSumAggregateInputType
  _min?: HeritageTrailMinAggregateInputType
  _max?: HeritageTrailMaxAggregateInputType
}

export type HeritageTrailGroupByOutputType = {
  id: string
  city: string
  name: string
  description: string
  sites: string
  distance: number | null
  duration: string | null
  culturalContext: string | null
  source: string
  sourceUrl: string | null
  createdAt: Date
  _count: HeritageTrailCountAggregateOutputType | null
  _avg: HeritageTrailAvgAggregateOutputType | null
  _sum: HeritageTrailSumAggregateOutputType | null
  _min: HeritageTrailMinAggregateOutputType | null
  _max: HeritageTrailMaxAggregateOutputType | null
}

type GetHeritageTrailGroupByPayload<T extends HeritageTrailGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<HeritageTrailGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof HeritageTrailGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], HeritageTrailGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], HeritageTrailGroupByOutputType[P]>
      }
    >
  >



export type HeritageTrailWhereInput = {
  AND?: Prisma.HeritageTrailWhereInput | Prisma.HeritageTrailWhereInput[]
  OR?: Prisma.HeritageTrailWhereInput[]
  NOT?: Prisma.HeritageTrailWhereInput | Prisma.HeritageTrailWhereInput[]
  id?: Prisma.StringFilter<"HeritageTrail"> | string
  city?: Prisma.StringFilter<"HeritageTrail"> | string
  name?: Prisma.StringFilter<"HeritageTrail"> | string
  description?: Prisma.StringFilter<"HeritageTrail"> | string
  sites?: Prisma.StringFilter<"HeritageTrail"> | string
  distance?: Prisma.FloatNullableFilter<"HeritageTrail"> | number | null
  duration?: Prisma.StringNullableFilter<"HeritageTrail"> | string | null
  culturalContext?: Prisma.StringNullableFilter<"HeritageTrail"> | string | null
  source?: Prisma.StringFilter<"HeritageTrail"> | string
  sourceUrl?: Prisma.StringNullableFilter<"HeritageTrail"> | string | null
  createdAt?: Prisma.DateTimeFilter<"HeritageTrail"> | Date | string
}

export type HeritageTrailOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  city?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  sites?: Prisma.SortOrder
  distance?: Prisma.SortOrderInput | Prisma.SortOrder
  duration?: Prisma.SortOrderInput | Prisma.SortOrder
  culturalContext?: Prisma.SortOrderInput | Prisma.SortOrder
  source?: Prisma.SortOrder
  sourceUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type HeritageTrailWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.HeritageTrailWhereInput | Prisma.HeritageTrailWhereInput[]
  OR?: Prisma.HeritageTrailWhereInput[]
  NOT?: Prisma.HeritageTrailWhereInput | Prisma.HeritageTrailWhereInput[]
  city?: Prisma.StringFilter<"HeritageTrail"> | string
  name?: Prisma.StringFilter<"HeritageTrail"> | string
  description?: Prisma.StringFilter<"HeritageTrail"> | string
  sites?: Prisma.StringFilter<"HeritageTrail"> | string
  distance?: Prisma.FloatNullableFilter<"HeritageTrail"> | number | null
  duration?: Prisma.StringNullableFilter<"HeritageTrail"> | string | null
  culturalContext?: Prisma.StringNullableFilter<"HeritageTrail"> | string | null
  source?: Prisma.StringFilter<"HeritageTrail"> | string
  sourceUrl?: Prisma.StringNullableFilter<"HeritageTrail"> | string | null
  createdAt?: Prisma.DateTimeFilter<"HeritageTrail"> | Date | string
}, "id">

export type HeritageTrailOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  city?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  sites?: Prisma.SortOrder
  distance?: Prisma.SortOrderInput | Prisma.SortOrder
  duration?: Prisma.SortOrderInput | Prisma.SortOrder
  culturalContext?: Prisma.SortOrderInput | Prisma.SortOrder
  source?: Prisma.SortOrder
  sourceUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.HeritageTrailCountOrderByAggregateInput
  _avg?: Prisma.HeritageTrailAvgOrderByAggregateInput
  _max?: Prisma.HeritageTrailMaxOrderByAggregateInput
  _min?: Prisma.HeritageTrailMinOrderByAggregateInput
  _sum?: Prisma.HeritageTrailSumOrderByAggregateInput
}

export type HeritageTrailScalarWhereWithAggregatesInput = {
  AND?: Prisma.HeritageTrailScalarWhereWithAggregatesInput | Prisma.HeritageTrailScalarWhereWithAggregatesInput[]
  OR?: Prisma.HeritageTrailScalarWhereWithAggregatesInput[]
  NOT?: Prisma.HeritageTrailScalarWhereWithAggregatesInput | Prisma.HeritageTrailScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"HeritageTrail"> | string
  city?: Prisma.StringWithAggregatesFilter<"HeritageTrail"> | string
  name?: Prisma.StringWithAggregatesFilter<"HeritageTrail"> | string
  description?: Prisma.StringWithAggregatesFilter<"HeritageTrail"> | string
  sites?: Prisma.StringWithAggregatesFilter<"HeritageTrail"> | string
  distance?: Prisma.FloatNullableWithAggregatesFilter<"HeritageTrail"> | number | null
  duration?: Prisma.StringNullableWithAggregatesFilter<"HeritageTrail"> | string | null
  culturalContext?: Prisma.StringNullableWithAggregatesFilter<"HeritageTrail"> | string | null
  source?: Prisma.StringWithAggregatesFilter<"HeritageTrail"> | string
  sourceUrl?: Prisma.StringNullableWithAggregatesFilter<"HeritageTrail"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"HeritageTrail"> | Date | string
}

export type HeritageTrailCreateInput = {
  id?: string
  city: string
  name: string
  description: string
  sites: string
  distance?: number | null
  duration?: string | null
  culturalContext?: string | null
  source?: string
  sourceUrl?: string | null
  createdAt?: Date | string
}

export type HeritageTrailUncheckedCreateInput = {
  id?: string
  city: string
  name: string
  description: string
  sites: string
  distance?: number | null
  duration?: string | null
  culturalContext?: string | null
  source?: string
  sourceUrl?: string | null
  createdAt?: Date | string
}

export type HeritageTrailUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  sites?: Prisma.StringFieldUpdateOperationsInput | string
  distance?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  duration?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  culturalContext?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.StringFieldUpdateOperationsInput | string
  sourceUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type HeritageTrailUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  sites?: Prisma.StringFieldUpdateOperationsInput | string
  distance?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  duration?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  culturalContext?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.StringFieldUpdateOperationsInput | string
  sourceUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type HeritageTrailCreateManyInput = {
  id?: string
  city: string
  name: string
  description: string
  sites: string
  distance?: number | null
  duration?: string | null
  culturalContext?: string | null
  source?: string
  sourceUrl?: string | null
  createdAt?: Date | string
}

export type HeritageTrailUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  sites?: Prisma.StringFieldUpdateOperationsInput | string
  distance?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  duration?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  culturalContext?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.StringFieldUpdateOperationsInput | string
  sourceUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type HeritageTrailUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  sites?: Prisma.StringFieldUpdateOperationsInput | string
  distance?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  duration?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  culturalContext?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.StringFieldUpdateOperationsInput | string
  sourceUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type HeritageTrailCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  city?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  sites?: Prisma.SortOrder
  distance?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  culturalContext?: Prisma.SortOrder
  source?: Prisma.SortOrder
  sourceUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type HeritageTrailAvgOrderByAggregateInput = {
  distance?: Prisma.SortOrder
}

export type HeritageTrailMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  city?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  sites?: Prisma.SortOrder
  distance?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  culturalContext?: Prisma.SortOrder
  source?: Prisma.SortOrder
  sourceUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type HeritageTrailMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  city?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  sites?: Prisma.SortOrder
  distance?: Prisma.SortOrder
  duration?: Prisma.SortOrder
  culturalContext?: Prisma.SortOrder
  source?: Prisma.SortOrder
  sourceUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type HeritageTrailSumOrderByAggregateInput = {
  distance?: Prisma.SortOrder
}



export type HeritageTrailSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  city?: boolean
  name?: boolean
  description?: boolean
  sites?: boolean
  distance?: boolean
  duration?: boolean
  culturalContext?: boolean
  source?: boolean
  sourceUrl?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["heritageTrail"]>

export type HeritageTrailSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  city?: boolean
  name?: boolean
  description?: boolean
  sites?: boolean
  distance?: boolean
  duration?: boolean
  culturalContext?: boolean
  source?: boolean
  sourceUrl?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["heritageTrail"]>

export type HeritageTrailSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  city?: boolean
  name?: boolean
  description?: boolean
  sites?: boolean
  distance?: boolean
  duration?: boolean
  culturalContext?: boolean
  source?: boolean
  sourceUrl?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["heritageTrail"]>

export type HeritageTrailSelectScalar = {
  id?: boolean
  city?: boolean
  name?: boolean
  description?: boolean
  sites?: boolean
  distance?: boolean
  duration?: boolean
  culturalContext?: boolean
  source?: boolean
  sourceUrl?: boolean
  createdAt?: boolean
}

export type HeritageTrailOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "city" | "name" | "description" | "sites" | "distance" | "duration" | "culturalContext" | "source" | "sourceUrl" | "createdAt", ExtArgs["result"]["heritageTrail"]>

export type $HeritageTrailPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "HeritageTrail"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    city: string
    name: string
    description: string
    sites: string
    distance: number | null
    duration: string | null
    culturalContext: string | null
    source: string
    sourceUrl: string | null
    createdAt: Date
  }, ExtArgs["result"]["heritageTrail"]>
  composites: {}
}

export type HeritageTrailGetPayload<S extends boolean | null | undefined | HeritageTrailDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$HeritageTrailPayload, S>

export type HeritageTrailCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<HeritageTrailFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: HeritageTrailCountAggregateInputType | true
  }

export interface HeritageTrailDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['HeritageTrail'], meta: { name: 'HeritageTrail' } }
  /**
   * Find zero or one HeritageTrail that matches the filter.
   * @param {HeritageTrailFindUniqueArgs} args - Arguments to find a HeritageTrail
   * @example
   * // Get one HeritageTrail
   * const heritageTrail = await prisma.heritageTrail.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends HeritageTrailFindUniqueArgs>(args: Prisma.SelectSubset<T, HeritageTrailFindUniqueArgs<ExtArgs>>): Prisma.Prisma__HeritageTrailClient<runtime.Types.Result.GetResult<Prisma.$HeritageTrailPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one HeritageTrail that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {HeritageTrailFindUniqueOrThrowArgs} args - Arguments to find a HeritageTrail
   * @example
   * // Get one HeritageTrail
   * const heritageTrail = await prisma.heritageTrail.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends HeritageTrailFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, HeritageTrailFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__HeritageTrailClient<runtime.Types.Result.GetResult<Prisma.$HeritageTrailPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first HeritageTrail that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HeritageTrailFindFirstArgs} args - Arguments to find a HeritageTrail
   * @example
   * // Get one HeritageTrail
   * const heritageTrail = await prisma.heritageTrail.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends HeritageTrailFindFirstArgs>(args?: Prisma.SelectSubset<T, HeritageTrailFindFirstArgs<ExtArgs>>): Prisma.Prisma__HeritageTrailClient<runtime.Types.Result.GetResult<Prisma.$HeritageTrailPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first HeritageTrail that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HeritageTrailFindFirstOrThrowArgs} args - Arguments to find a HeritageTrail
   * @example
   * // Get one HeritageTrail
   * const heritageTrail = await prisma.heritageTrail.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends HeritageTrailFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, HeritageTrailFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__HeritageTrailClient<runtime.Types.Result.GetResult<Prisma.$HeritageTrailPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more HeritageTrails that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HeritageTrailFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all HeritageTrails
   * const heritageTrails = await prisma.heritageTrail.findMany()
   * 
   * // Get first 10 HeritageTrails
   * const heritageTrails = await prisma.heritageTrail.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const heritageTrailWithIdOnly = await prisma.heritageTrail.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends HeritageTrailFindManyArgs>(args?: Prisma.SelectSubset<T, HeritageTrailFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HeritageTrailPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a HeritageTrail.
   * @param {HeritageTrailCreateArgs} args - Arguments to create a HeritageTrail.
   * @example
   * // Create one HeritageTrail
   * const HeritageTrail = await prisma.heritageTrail.create({
   *   data: {
   *     // ... data to create a HeritageTrail
   *   }
   * })
   * 
   */
  create<T extends HeritageTrailCreateArgs>(args: Prisma.SelectSubset<T, HeritageTrailCreateArgs<ExtArgs>>): Prisma.Prisma__HeritageTrailClient<runtime.Types.Result.GetResult<Prisma.$HeritageTrailPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many HeritageTrails.
   * @param {HeritageTrailCreateManyArgs} args - Arguments to create many HeritageTrails.
   * @example
   * // Create many HeritageTrails
   * const heritageTrail = await prisma.heritageTrail.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends HeritageTrailCreateManyArgs>(args?: Prisma.SelectSubset<T, HeritageTrailCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many HeritageTrails and returns the data saved in the database.
   * @param {HeritageTrailCreateManyAndReturnArgs} args - Arguments to create many HeritageTrails.
   * @example
   * // Create many HeritageTrails
   * const heritageTrail = await prisma.heritageTrail.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many HeritageTrails and only return the `id`
   * const heritageTrailWithIdOnly = await prisma.heritageTrail.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends HeritageTrailCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, HeritageTrailCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HeritageTrailPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a HeritageTrail.
   * @param {HeritageTrailDeleteArgs} args - Arguments to delete one HeritageTrail.
   * @example
   * // Delete one HeritageTrail
   * const HeritageTrail = await prisma.heritageTrail.delete({
   *   where: {
   *     // ... filter to delete one HeritageTrail
   *   }
   * })
   * 
   */
  delete<T extends HeritageTrailDeleteArgs>(args: Prisma.SelectSubset<T, HeritageTrailDeleteArgs<ExtArgs>>): Prisma.Prisma__HeritageTrailClient<runtime.Types.Result.GetResult<Prisma.$HeritageTrailPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one HeritageTrail.
   * @param {HeritageTrailUpdateArgs} args - Arguments to update one HeritageTrail.
   * @example
   * // Update one HeritageTrail
   * const heritageTrail = await prisma.heritageTrail.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends HeritageTrailUpdateArgs>(args: Prisma.SelectSubset<T, HeritageTrailUpdateArgs<ExtArgs>>): Prisma.Prisma__HeritageTrailClient<runtime.Types.Result.GetResult<Prisma.$HeritageTrailPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more HeritageTrails.
   * @param {HeritageTrailDeleteManyArgs} args - Arguments to filter HeritageTrails to delete.
   * @example
   * // Delete a few HeritageTrails
   * const { count } = await prisma.heritageTrail.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends HeritageTrailDeleteManyArgs>(args?: Prisma.SelectSubset<T, HeritageTrailDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more HeritageTrails.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HeritageTrailUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many HeritageTrails
   * const heritageTrail = await prisma.heritageTrail.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends HeritageTrailUpdateManyArgs>(args: Prisma.SelectSubset<T, HeritageTrailUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more HeritageTrails and returns the data updated in the database.
   * @param {HeritageTrailUpdateManyAndReturnArgs} args - Arguments to update many HeritageTrails.
   * @example
   * // Update many HeritageTrails
   * const heritageTrail = await prisma.heritageTrail.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more HeritageTrails and only return the `id`
   * const heritageTrailWithIdOnly = await prisma.heritageTrail.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends HeritageTrailUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, HeritageTrailUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HeritageTrailPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one HeritageTrail.
   * @param {HeritageTrailUpsertArgs} args - Arguments to update or create a HeritageTrail.
   * @example
   * // Update or create a HeritageTrail
   * const heritageTrail = await prisma.heritageTrail.upsert({
   *   create: {
   *     // ... data to create a HeritageTrail
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the HeritageTrail we want to update
   *   }
   * })
   */
  upsert<T extends HeritageTrailUpsertArgs>(args: Prisma.SelectSubset<T, HeritageTrailUpsertArgs<ExtArgs>>): Prisma.Prisma__HeritageTrailClient<runtime.Types.Result.GetResult<Prisma.$HeritageTrailPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of HeritageTrails.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HeritageTrailCountArgs} args - Arguments to filter HeritageTrails to count.
   * @example
   * // Count the number of HeritageTrails
   * const count = await prisma.heritageTrail.count({
   *   where: {
   *     // ... the filter for the HeritageTrails we want to count
   *   }
   * })
  **/
  count<T extends HeritageTrailCountArgs>(
    args?: Prisma.Subset<T, HeritageTrailCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], HeritageTrailCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a HeritageTrail.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HeritageTrailAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends HeritageTrailAggregateArgs>(args: Prisma.Subset<T, HeritageTrailAggregateArgs>): Prisma.PrismaPromise<GetHeritageTrailAggregateType<T>>

  /**
   * Group by HeritageTrail.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HeritageTrailGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends HeritageTrailGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: HeritageTrailGroupByArgs['orderBy'] }
      : { orderBy?: HeritageTrailGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, HeritageTrailGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetHeritageTrailGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the HeritageTrail model
 */
readonly fields: HeritageTrailFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for HeritageTrail.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__HeritageTrailClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the HeritageTrail model
 */
export interface HeritageTrailFieldRefs {
  readonly id: Prisma.FieldRef<"HeritageTrail", 'String'>
  readonly city: Prisma.FieldRef<"HeritageTrail", 'String'>
  readonly name: Prisma.FieldRef<"HeritageTrail", 'String'>
  readonly description: Prisma.FieldRef<"HeritageTrail", 'String'>
  readonly sites: Prisma.FieldRef<"HeritageTrail", 'String'>
  readonly distance: Prisma.FieldRef<"HeritageTrail", 'Float'>
  readonly duration: Prisma.FieldRef<"HeritageTrail", 'String'>
  readonly culturalContext: Prisma.FieldRef<"HeritageTrail", 'String'>
  readonly source: Prisma.FieldRef<"HeritageTrail", 'String'>
  readonly sourceUrl: Prisma.FieldRef<"HeritageTrail", 'String'>
  readonly createdAt: Prisma.FieldRef<"HeritageTrail", 'DateTime'>
}
    

// Custom InputTypes
/**
 * HeritageTrail findUnique
 */
export type HeritageTrailFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HeritageTrail
   */
  select?: Prisma.HeritageTrailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HeritageTrail
   */
  omit?: Prisma.HeritageTrailOmit<ExtArgs> | null
  /**
   * Filter, which HeritageTrail to fetch.
   */
  where: Prisma.HeritageTrailWhereUniqueInput
}

/**
 * HeritageTrail findUniqueOrThrow
 */
export type HeritageTrailFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HeritageTrail
   */
  select?: Prisma.HeritageTrailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HeritageTrail
   */
  omit?: Prisma.HeritageTrailOmit<ExtArgs> | null
  /**
   * Filter, which HeritageTrail to fetch.
   */
  where: Prisma.HeritageTrailWhereUniqueInput
}

/**
 * HeritageTrail findFirst
 */
export type HeritageTrailFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HeritageTrail
   */
  select?: Prisma.HeritageTrailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HeritageTrail
   */
  omit?: Prisma.HeritageTrailOmit<ExtArgs> | null
  /**
   * Filter, which HeritageTrail to fetch.
   */
  where?: Prisma.HeritageTrailWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of HeritageTrails to fetch.
   */
  orderBy?: Prisma.HeritageTrailOrderByWithRelationInput | Prisma.HeritageTrailOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for HeritageTrails.
   */
  cursor?: Prisma.HeritageTrailWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` HeritageTrails from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` HeritageTrails.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of HeritageTrails.
   */
  distinct?: Prisma.HeritageTrailScalarFieldEnum | Prisma.HeritageTrailScalarFieldEnum[]
}

/**
 * HeritageTrail findFirstOrThrow
 */
export type HeritageTrailFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HeritageTrail
   */
  select?: Prisma.HeritageTrailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HeritageTrail
   */
  omit?: Prisma.HeritageTrailOmit<ExtArgs> | null
  /**
   * Filter, which HeritageTrail to fetch.
   */
  where?: Prisma.HeritageTrailWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of HeritageTrails to fetch.
   */
  orderBy?: Prisma.HeritageTrailOrderByWithRelationInput | Prisma.HeritageTrailOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for HeritageTrails.
   */
  cursor?: Prisma.HeritageTrailWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` HeritageTrails from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` HeritageTrails.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of HeritageTrails.
   */
  distinct?: Prisma.HeritageTrailScalarFieldEnum | Prisma.HeritageTrailScalarFieldEnum[]
}

/**
 * HeritageTrail findMany
 */
export type HeritageTrailFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HeritageTrail
   */
  select?: Prisma.HeritageTrailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HeritageTrail
   */
  omit?: Prisma.HeritageTrailOmit<ExtArgs> | null
  /**
   * Filter, which HeritageTrails to fetch.
   */
  where?: Prisma.HeritageTrailWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of HeritageTrails to fetch.
   */
  orderBy?: Prisma.HeritageTrailOrderByWithRelationInput | Prisma.HeritageTrailOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing HeritageTrails.
   */
  cursor?: Prisma.HeritageTrailWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` HeritageTrails from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` HeritageTrails.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of HeritageTrails.
   */
  distinct?: Prisma.HeritageTrailScalarFieldEnum | Prisma.HeritageTrailScalarFieldEnum[]
}

/**
 * HeritageTrail create
 */
export type HeritageTrailCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HeritageTrail
   */
  select?: Prisma.HeritageTrailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HeritageTrail
   */
  omit?: Prisma.HeritageTrailOmit<ExtArgs> | null
  /**
   * The data needed to create a HeritageTrail.
   */
  data: Prisma.XOR<Prisma.HeritageTrailCreateInput, Prisma.HeritageTrailUncheckedCreateInput>
}

/**
 * HeritageTrail createMany
 */
export type HeritageTrailCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many HeritageTrails.
   */
  data: Prisma.HeritageTrailCreateManyInput | Prisma.HeritageTrailCreateManyInput[]
}

/**
 * HeritageTrail createManyAndReturn
 */
export type HeritageTrailCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HeritageTrail
   */
  select?: Prisma.HeritageTrailSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the HeritageTrail
   */
  omit?: Prisma.HeritageTrailOmit<ExtArgs> | null
  /**
   * The data used to create many HeritageTrails.
   */
  data: Prisma.HeritageTrailCreateManyInput | Prisma.HeritageTrailCreateManyInput[]
}

/**
 * HeritageTrail update
 */
export type HeritageTrailUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HeritageTrail
   */
  select?: Prisma.HeritageTrailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HeritageTrail
   */
  omit?: Prisma.HeritageTrailOmit<ExtArgs> | null
  /**
   * The data needed to update a HeritageTrail.
   */
  data: Prisma.XOR<Prisma.HeritageTrailUpdateInput, Prisma.HeritageTrailUncheckedUpdateInput>
  /**
   * Choose, which HeritageTrail to update.
   */
  where: Prisma.HeritageTrailWhereUniqueInput
}

/**
 * HeritageTrail updateMany
 */
export type HeritageTrailUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update HeritageTrails.
   */
  data: Prisma.XOR<Prisma.HeritageTrailUpdateManyMutationInput, Prisma.HeritageTrailUncheckedUpdateManyInput>
  /**
   * Filter which HeritageTrails to update
   */
  where?: Prisma.HeritageTrailWhereInput
  /**
   * Limit how many HeritageTrails to update.
   */
  limit?: number
}

/**
 * HeritageTrail updateManyAndReturn
 */
export type HeritageTrailUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HeritageTrail
   */
  select?: Prisma.HeritageTrailSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the HeritageTrail
   */
  omit?: Prisma.HeritageTrailOmit<ExtArgs> | null
  /**
   * The data used to update HeritageTrails.
   */
  data: Prisma.XOR<Prisma.HeritageTrailUpdateManyMutationInput, Prisma.HeritageTrailUncheckedUpdateManyInput>
  /**
   * Filter which HeritageTrails to update
   */
  where?: Prisma.HeritageTrailWhereInput
  /**
   * Limit how many HeritageTrails to update.
   */
  limit?: number
}

/**
 * HeritageTrail upsert
 */
export type HeritageTrailUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HeritageTrail
   */
  select?: Prisma.HeritageTrailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HeritageTrail
   */
  omit?: Prisma.HeritageTrailOmit<ExtArgs> | null
  /**
   * The filter to search for the HeritageTrail to update in case it exists.
   */
  where: Prisma.HeritageTrailWhereUniqueInput
  /**
   * In case the HeritageTrail found by the `where` argument doesn't exist, create a new HeritageTrail with this data.
   */
  create: Prisma.XOR<Prisma.HeritageTrailCreateInput, Prisma.HeritageTrailUncheckedCreateInput>
  /**
   * In case the HeritageTrail was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.HeritageTrailUpdateInput, Prisma.HeritageTrailUncheckedUpdateInput>
}

/**
 * HeritageTrail delete
 */
export type HeritageTrailDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HeritageTrail
   */
  select?: Prisma.HeritageTrailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HeritageTrail
   */
  omit?: Prisma.HeritageTrailOmit<ExtArgs> | null
  /**
   * Filter which HeritageTrail to delete.
   */
  where: Prisma.HeritageTrailWhereUniqueInput
}

/**
 * HeritageTrail deleteMany
 */
export type HeritageTrailDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which HeritageTrails to delete
   */
  where?: Prisma.HeritageTrailWhereInput
  /**
   * Limit how many HeritageTrails to delete.
   */
  limit?: number
}

/**
 * HeritageTrail without action
 */
export type HeritageTrailDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HeritageTrail
   */
  select?: Prisma.HeritageTrailSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HeritageTrail
   */
  omit?: Prisma.HeritageTrailOmit<ExtArgs> | null
}
