
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Place` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Place
 * 
 */
export type PlaceModel = runtime.Types.Result.DefaultSelection<Prisma.$PlacePayload>

export type AggregatePlace = {
  _count: PlaceCountAggregateOutputType | null
  _avg: PlaceAvgAggregateOutputType | null
  _sum: PlaceSumAggregateOutputType | null
  _min: PlaceMinAggregateOutputType | null
  _max: PlaceMaxAggregateOutputType | null
}

export type PlaceAvgAggregateOutputType = {
  latitude: number | null
  longitude: number | null
  distance: number | null
  estimatedCost: number | null
  rating: number | null
}

export type PlaceSumAggregateOutputType = {
  latitude: number | null
  longitude: number | null
  distance: number | null
  estimatedCost: number | null
  rating: number | null
}

export type PlaceMinAggregateOutputType = {
  id: string | null
  name: string | null
  category: string | null
  description: string | null
  city: string | null
  latitude: number | null
  longitude: number | null
  address: string | null
  distance: number | null
  openingHours: string | null
  priceRange: string | null
  estimatedCost: number | null
  currency: string | null
  rating: number | null
  accessibility: string | null
  culturalValue: string | null
  source: string | null
  sourceUrl: string | null
  imageUrl: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PlaceMaxAggregateOutputType = {
  id: string | null
  name: string | null
  category: string | null
  description: string | null
  city: string | null
  latitude: number | null
  longitude: number | null
  address: string | null
  distance: number | null
  openingHours: string | null
  priceRange: string | null
  estimatedCost: number | null
  currency: string | null
  rating: number | null
  accessibility: string | null
  culturalValue: string | null
  source: string | null
  sourceUrl: string | null
  imageUrl: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PlaceCountAggregateOutputType = {
  id: number
  name: number
  category: number
  description: number
  city: number
  latitude: number
  longitude: number
  address: number
  distance: number
  openingHours: number
  priceRange: number
  estimatedCost: number
  currency: number
  rating: number
  accessibility: number
  culturalValue: number
  source: number
  sourceUrl: number
  imageUrl: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PlaceAvgAggregateInputType = {
  latitude?: true
  longitude?: true
  distance?: true
  estimatedCost?: true
  rating?: true
}

export type PlaceSumAggregateInputType = {
  latitude?: true
  longitude?: true
  distance?: true
  estimatedCost?: true
  rating?: true
}

export type PlaceMinAggregateInputType = {
  id?: true
  name?: true
  category?: true
  description?: true
  city?: true
  latitude?: true
  longitude?: true
  address?: true
  distance?: true
  openingHours?: true
  priceRange?: true
  estimatedCost?: true
  currency?: true
  rating?: true
  accessibility?: true
  culturalValue?: true
  source?: true
  sourceUrl?: true
  imageUrl?: true
  createdAt?: true
  updatedAt?: true
}

export type PlaceMaxAggregateInputType = {
  id?: true
  name?: true
  category?: true
  description?: true
  city?: true
  latitude?: true
  longitude?: true
  address?: true
  distance?: true
  openingHours?: true
  priceRange?: true
  estimatedCost?: true
  currency?: true
  rating?: true
  accessibility?: true
  culturalValue?: true
  source?: true
  sourceUrl?: true
  imageUrl?: true
  createdAt?: true
  updatedAt?: true
}

export type PlaceCountAggregateInputType = {
  id?: true
  name?: true
  category?: true
  description?: true
  city?: true
  latitude?: true
  longitude?: true
  address?: true
  distance?: true
  openingHours?: true
  priceRange?: true
  estimatedCost?: true
  currency?: true
  rating?: true
  accessibility?: true
  culturalValue?: true
  source?: true
  sourceUrl?: true
  imageUrl?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PlaceAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Place to aggregate.
   */
  where?: Prisma.PlaceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Places to fetch.
   */
  orderBy?: Prisma.PlaceOrderByWithRelationInput | Prisma.PlaceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PlaceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Places from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Places.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Places
  **/
  _count?: true | PlaceCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PlaceAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PlaceSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PlaceMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PlaceMaxAggregateInputType
}

export type GetPlaceAggregateType<T extends PlaceAggregateArgs> = {
      [P in keyof T & keyof AggregatePlace]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePlace[P]>
    : Prisma.GetScalarType<T[P], AggregatePlace[P]>
}




export type PlaceGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PlaceWhereInput
  orderBy?: Prisma.PlaceOrderByWithAggregationInput | Prisma.PlaceOrderByWithAggregationInput[]
  by: Prisma.PlaceScalarFieldEnum[] | Prisma.PlaceScalarFieldEnum
  having?: Prisma.PlaceScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PlaceCountAggregateInputType | true
  _avg?: PlaceAvgAggregateInputType
  _sum?: PlaceSumAggregateInputType
  _min?: PlaceMinAggregateInputType
  _max?: PlaceMaxAggregateInputType
}

export type PlaceGroupByOutputType = {
  id: string
  name: string
  category: string
  description: string | null
  city: string
  latitude: number
  longitude: number
  address: string | null
  distance: number | null
  openingHours: string | null
  priceRange: string | null
  estimatedCost: number | null
  currency: string
  rating: number | null
  accessibility: string | null
  culturalValue: string | null
  source: string
  sourceUrl: string | null
  imageUrl: string | null
  createdAt: Date
  updatedAt: Date
  _count: PlaceCountAggregateOutputType | null
  _avg: PlaceAvgAggregateOutputType | null
  _sum: PlaceSumAggregateOutputType | null
  _min: PlaceMinAggregateOutputType | null
  _max: PlaceMaxAggregateOutputType | null
}

type GetPlaceGroupByPayload<T extends PlaceGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PlaceGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PlaceGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PlaceGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PlaceGroupByOutputType[P]>
      }
    >
  >



export type PlaceWhereInput = {
  AND?: Prisma.PlaceWhereInput | Prisma.PlaceWhereInput[]
  OR?: Prisma.PlaceWhereInput[]
  NOT?: Prisma.PlaceWhereInput | Prisma.PlaceWhereInput[]
  id?: Prisma.StringFilter<"Place"> | string
  name?: Prisma.StringFilter<"Place"> | string
  category?: Prisma.StringFilter<"Place"> | string
  description?: Prisma.StringNullableFilter<"Place"> | string | null
  city?: Prisma.StringFilter<"Place"> | string
  latitude?: Prisma.FloatFilter<"Place"> | number
  longitude?: Prisma.FloatFilter<"Place"> | number
  address?: Prisma.StringNullableFilter<"Place"> | string | null
  distance?: Prisma.FloatNullableFilter<"Place"> | number | null
  openingHours?: Prisma.StringNullableFilter<"Place"> | string | null
  priceRange?: Prisma.StringNullableFilter<"Place"> | string | null
  estimatedCost?: Prisma.FloatNullableFilter<"Place"> | number | null
  currency?: Prisma.StringFilter<"Place"> | string
  rating?: Prisma.FloatNullableFilter<"Place"> | number | null
  accessibility?: Prisma.StringNullableFilter<"Place"> | string | null
  culturalValue?: Prisma.StringNullableFilter<"Place"> | string | null
  source?: Prisma.StringFilter<"Place"> | string
  sourceUrl?: Prisma.StringNullableFilter<"Place"> | string | null
  imageUrl?: Prisma.StringNullableFilter<"Place"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Place"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Place"> | Date | string
}

export type PlaceOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  city?: Prisma.SortOrder
  latitude?: Prisma.SortOrder
  longitude?: Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  distance?: Prisma.SortOrderInput | Prisma.SortOrder
  openingHours?: Prisma.SortOrderInput | Prisma.SortOrder
  priceRange?: Prisma.SortOrderInput | Prisma.SortOrder
  estimatedCost?: Prisma.SortOrderInput | Prisma.SortOrder
  currency?: Prisma.SortOrder
  rating?: Prisma.SortOrderInput | Prisma.SortOrder
  accessibility?: Prisma.SortOrderInput | Prisma.SortOrder
  culturalValue?: Prisma.SortOrderInput | Prisma.SortOrder
  source?: Prisma.SortOrder
  sourceUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  imageUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PlaceWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PlaceWhereInput | Prisma.PlaceWhereInput[]
  OR?: Prisma.PlaceWhereInput[]
  NOT?: Prisma.PlaceWhereInput | Prisma.PlaceWhereInput[]
  name?: Prisma.StringFilter<"Place"> | string
  category?: Prisma.StringFilter<"Place"> | string
  description?: Prisma.StringNullableFilter<"Place"> | string | null
  city?: Prisma.StringFilter<"Place"> | string
  latitude?: Prisma.FloatFilter<"Place"> | number
  longitude?: Prisma.FloatFilter<"Place"> | number
  address?: Prisma.StringNullableFilter<"Place"> | string | null
  distance?: Prisma.FloatNullableFilter<"Place"> | number | null
  openingHours?: Prisma.StringNullableFilter<"Place"> | string | null
  priceRange?: Prisma.StringNullableFilter<"Place"> | string | null
  estimatedCost?: Prisma.FloatNullableFilter<"Place"> | number | null
  currency?: Prisma.StringFilter<"Place"> | string
  rating?: Prisma.FloatNullableFilter<"Place"> | number | null
  accessibility?: Prisma.StringNullableFilter<"Place"> | string | null
  culturalValue?: Prisma.StringNullableFilter<"Place"> | string | null
  source?: Prisma.StringFilter<"Place"> | string
  sourceUrl?: Prisma.StringNullableFilter<"Place"> | string | null
  imageUrl?: Prisma.StringNullableFilter<"Place"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Place"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Place"> | Date | string
}, "id">

export type PlaceOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  city?: Prisma.SortOrder
  latitude?: Prisma.SortOrder
  longitude?: Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  distance?: Prisma.SortOrderInput | Prisma.SortOrder
  openingHours?: Prisma.SortOrderInput | Prisma.SortOrder
  priceRange?: Prisma.SortOrderInput | Prisma.SortOrder
  estimatedCost?: Prisma.SortOrderInput | Prisma.SortOrder
  currency?: Prisma.SortOrder
  rating?: Prisma.SortOrderInput | Prisma.SortOrder
  accessibility?: Prisma.SortOrderInput | Prisma.SortOrder
  culturalValue?: Prisma.SortOrderInput | Prisma.SortOrder
  source?: Prisma.SortOrder
  sourceUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  imageUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PlaceCountOrderByAggregateInput
  _avg?: Prisma.PlaceAvgOrderByAggregateInput
  _max?: Prisma.PlaceMaxOrderByAggregateInput
  _min?: Prisma.PlaceMinOrderByAggregateInput
  _sum?: Prisma.PlaceSumOrderByAggregateInput
}

export type PlaceScalarWhereWithAggregatesInput = {
  AND?: Prisma.PlaceScalarWhereWithAggregatesInput | Prisma.PlaceScalarWhereWithAggregatesInput[]
  OR?: Prisma.PlaceScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PlaceScalarWhereWithAggregatesInput | Prisma.PlaceScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Place"> | string
  name?: Prisma.StringWithAggregatesFilter<"Place"> | string
  category?: Prisma.StringWithAggregatesFilter<"Place"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"Place"> | string | null
  city?: Prisma.StringWithAggregatesFilter<"Place"> | string
  latitude?: Prisma.FloatWithAggregatesFilter<"Place"> | number
  longitude?: Prisma.FloatWithAggregatesFilter<"Place"> | number
  address?: Prisma.StringNullableWithAggregatesFilter<"Place"> | string | null
  distance?: Prisma.FloatNullableWithAggregatesFilter<"Place"> | number | null
  openingHours?: Prisma.StringNullableWithAggregatesFilter<"Place"> | string | null
  priceRange?: Prisma.StringNullableWithAggregatesFilter<"Place"> | string | null
  estimatedCost?: Prisma.FloatNullableWithAggregatesFilter<"Place"> | number | null
  currency?: Prisma.StringWithAggregatesFilter<"Place"> | string
  rating?: Prisma.FloatNullableWithAggregatesFilter<"Place"> | number | null
  accessibility?: Prisma.StringNullableWithAggregatesFilter<"Place"> | string | null
  culturalValue?: Prisma.StringNullableWithAggregatesFilter<"Place"> | string | null
  source?: Prisma.StringWithAggregatesFilter<"Place"> | string
  sourceUrl?: Prisma.StringNullableWithAggregatesFilter<"Place"> | string | null
  imageUrl?: Prisma.StringNullableWithAggregatesFilter<"Place"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Place"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Place"> | Date | string
}

export type PlaceCreateInput = {
  id?: string
  name: string
  category: string
  description?: string | null
  city: string
  latitude: number
  longitude: number
  address?: string | null
  distance?: number | null
  openingHours?: string | null
  priceRange?: string | null
  estimatedCost?: number | null
  currency?: string
  rating?: number | null
  accessibility?: string | null
  culturalValue?: string | null
  source: string
  sourceUrl?: string | null
  imageUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PlaceUncheckedCreateInput = {
  id?: string
  name: string
  category: string
  description?: string | null
  city: string
  latitude: number
  longitude: number
  address?: string | null
  distance?: number | null
  openingHours?: string | null
  priceRange?: string | null
  estimatedCost?: number | null
  currency?: string
  rating?: number | null
  accessibility?: string | null
  culturalValue?: string | null
  source: string
  sourceUrl?: string | null
  imageUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PlaceUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.StringFieldUpdateOperationsInput | string
  latitude?: Prisma.FloatFieldUpdateOperationsInput | number
  longitude?: Prisma.FloatFieldUpdateOperationsInput | number
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  distance?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  openingHours?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  priceRange?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  estimatedCost?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  accessibility?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  culturalValue?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.StringFieldUpdateOperationsInput | string
  sourceUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlaceUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.StringFieldUpdateOperationsInput | string
  latitude?: Prisma.FloatFieldUpdateOperationsInput | number
  longitude?: Prisma.FloatFieldUpdateOperationsInput | number
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  distance?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  openingHours?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  priceRange?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  estimatedCost?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  accessibility?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  culturalValue?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.StringFieldUpdateOperationsInput | string
  sourceUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlaceCreateManyInput = {
  id?: string
  name: string
  category: string
  description?: string | null
  city: string
  latitude: number
  longitude: number
  address?: string | null
  distance?: number | null
  openingHours?: string | null
  priceRange?: string | null
  estimatedCost?: number | null
  currency?: string
  rating?: number | null
  accessibility?: string | null
  culturalValue?: string | null
  source: string
  sourceUrl?: string | null
  imageUrl?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PlaceUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.StringFieldUpdateOperationsInput | string
  latitude?: Prisma.FloatFieldUpdateOperationsInput | number
  longitude?: Prisma.FloatFieldUpdateOperationsInput | number
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  distance?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  openingHours?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  priceRange?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  estimatedCost?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  accessibility?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  culturalValue?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.StringFieldUpdateOperationsInput | string
  sourceUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlaceUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  city?: Prisma.StringFieldUpdateOperationsInput | string
  latitude?: Prisma.FloatFieldUpdateOperationsInput | number
  longitude?: Prisma.FloatFieldUpdateOperationsInput | number
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  distance?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  openingHours?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  priceRange?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  estimatedCost?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  rating?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  accessibility?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  culturalValue?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.StringFieldUpdateOperationsInput | string
  sourceUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imageUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PlaceCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category?: Prisma.SortOrder
  description?: Prisma.SortOrder
  city?: Prisma.SortOrder
  latitude?: Prisma.SortOrder
  longitude?: Prisma.SortOrder
  address?: Prisma.SortOrder
  distance?: Prisma.SortOrder
  openingHours?: Prisma.SortOrder
  priceRange?: Prisma.SortOrder
  estimatedCost?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  accessibility?: Prisma.SortOrder
  culturalValue?: Prisma.SortOrder
  source?: Prisma.SortOrder
  sourceUrl?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PlaceAvgOrderByAggregateInput = {
  latitude?: Prisma.SortOrder
  longitude?: Prisma.SortOrder
  distance?: Prisma.SortOrder
  estimatedCost?: Prisma.SortOrder
  rating?: Prisma.SortOrder
}

export type PlaceMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category?: Prisma.SortOrder
  description?: Prisma.SortOrder
  city?: Prisma.SortOrder
  latitude?: Prisma.SortOrder
  longitude?: Prisma.SortOrder
  address?: Prisma.SortOrder
  distance?: Prisma.SortOrder
  openingHours?: Prisma.SortOrder
  priceRange?: Prisma.SortOrder
  estimatedCost?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  accessibility?: Prisma.SortOrder
  culturalValue?: Prisma.SortOrder
  source?: Prisma.SortOrder
  sourceUrl?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PlaceMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  category?: Prisma.SortOrder
  description?: Prisma.SortOrder
  city?: Prisma.SortOrder
  latitude?: Prisma.SortOrder
  longitude?: Prisma.SortOrder
  address?: Prisma.SortOrder
  distance?: Prisma.SortOrder
  openingHours?: Prisma.SortOrder
  priceRange?: Prisma.SortOrder
  estimatedCost?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  rating?: Prisma.SortOrder
  accessibility?: Prisma.SortOrder
  culturalValue?: Prisma.SortOrder
  source?: Prisma.SortOrder
  sourceUrl?: Prisma.SortOrder
  imageUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PlaceSumOrderByAggregateInput = {
  latitude?: Prisma.SortOrder
  longitude?: Prisma.SortOrder
  distance?: Prisma.SortOrder
  estimatedCost?: Prisma.SortOrder
  rating?: Prisma.SortOrder
}



export type PlaceSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  category?: boolean
  description?: boolean
  city?: boolean
  latitude?: boolean
  longitude?: boolean
  address?: boolean
  distance?: boolean
  openingHours?: boolean
  priceRange?: boolean
  estimatedCost?: boolean
  currency?: boolean
  rating?: boolean
  accessibility?: boolean
  culturalValue?: boolean
  source?: boolean
  sourceUrl?: boolean
  imageUrl?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["place"]>

export type PlaceSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  category?: boolean
  description?: boolean
  city?: boolean
  latitude?: boolean
  longitude?: boolean
  address?: boolean
  distance?: boolean
  openingHours?: boolean
  priceRange?: boolean
  estimatedCost?: boolean
  currency?: boolean
  rating?: boolean
  accessibility?: boolean
  culturalValue?: boolean
  source?: boolean
  sourceUrl?: boolean
  imageUrl?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["place"]>

export type PlaceSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  category?: boolean
  description?: boolean
  city?: boolean
  latitude?: boolean
  longitude?: boolean
  address?: boolean
  distance?: boolean
  openingHours?: boolean
  priceRange?: boolean
  estimatedCost?: boolean
  currency?: boolean
  rating?: boolean
  accessibility?: boolean
  culturalValue?: boolean
  source?: boolean
  sourceUrl?: boolean
  imageUrl?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["place"]>

export type PlaceSelectScalar = {
  id?: boolean
  name?: boolean
  category?: boolean
  description?: boolean
  city?: boolean
  latitude?: boolean
  longitude?: boolean
  address?: boolean
  distance?: boolean
  openingHours?: boolean
  priceRange?: boolean
  estimatedCost?: boolean
  currency?: boolean
  rating?: boolean
  accessibility?: boolean
  culturalValue?: boolean
  source?: boolean
  sourceUrl?: boolean
  imageUrl?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PlaceOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "category" | "description" | "city" | "latitude" | "longitude" | "address" | "distance" | "openingHours" | "priceRange" | "estimatedCost" | "currency" | "rating" | "accessibility" | "culturalValue" | "source" | "sourceUrl" | "imageUrl" | "createdAt" | "updatedAt", ExtArgs["result"]["place"]>

export type $PlacePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Place"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    category: string
    description: string | null
    city: string
    latitude: number
    longitude: number
    address: string | null
    distance: number | null
    openingHours: string | null
    priceRange: string | null
    estimatedCost: number | null
    currency: string
    rating: number | null
    accessibility: string | null
    culturalValue: string | null
    source: string
    sourceUrl: string | null
    imageUrl: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["place"]>
  composites: {}
}

export type PlaceGetPayload<S extends boolean | null | undefined | PlaceDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PlacePayload, S>

export type PlaceCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PlaceFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PlaceCountAggregateInputType | true
  }

export interface PlaceDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Place'], meta: { name: 'Place' } }
  /**
   * Find zero or one Place that matches the filter.
   * @param {PlaceFindUniqueArgs} args - Arguments to find a Place
   * @example
   * // Get one Place
   * const place = await prisma.place.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PlaceFindUniqueArgs>(args: Prisma.SelectSubset<T, PlaceFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PlaceClient<runtime.Types.Result.GetResult<Prisma.$PlacePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Place that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PlaceFindUniqueOrThrowArgs} args - Arguments to find a Place
   * @example
   * // Get one Place
   * const place = await prisma.place.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PlaceFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PlaceFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PlaceClient<runtime.Types.Result.GetResult<Prisma.$PlacePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Place that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaceFindFirstArgs} args - Arguments to find a Place
   * @example
   * // Get one Place
   * const place = await prisma.place.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PlaceFindFirstArgs>(args?: Prisma.SelectSubset<T, PlaceFindFirstArgs<ExtArgs>>): Prisma.Prisma__PlaceClient<runtime.Types.Result.GetResult<Prisma.$PlacePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Place that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaceFindFirstOrThrowArgs} args - Arguments to find a Place
   * @example
   * // Get one Place
   * const place = await prisma.place.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PlaceFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PlaceFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PlaceClient<runtime.Types.Result.GetResult<Prisma.$PlacePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Places that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaceFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Places
   * const places = await prisma.place.findMany()
   * 
   * // Get first 10 Places
   * const places = await prisma.place.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const placeWithIdOnly = await prisma.place.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PlaceFindManyArgs>(args?: Prisma.SelectSubset<T, PlaceFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlacePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Place.
   * @param {PlaceCreateArgs} args - Arguments to create a Place.
   * @example
   * // Create one Place
   * const Place = await prisma.place.create({
   *   data: {
   *     // ... data to create a Place
   *   }
   * })
   * 
   */
  create<T extends PlaceCreateArgs>(args: Prisma.SelectSubset<T, PlaceCreateArgs<ExtArgs>>): Prisma.Prisma__PlaceClient<runtime.Types.Result.GetResult<Prisma.$PlacePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Places.
   * @param {PlaceCreateManyArgs} args - Arguments to create many Places.
   * @example
   * // Create many Places
   * const place = await prisma.place.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PlaceCreateManyArgs>(args?: Prisma.SelectSubset<T, PlaceCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Places and returns the data saved in the database.
   * @param {PlaceCreateManyAndReturnArgs} args - Arguments to create many Places.
   * @example
   * // Create many Places
   * const place = await prisma.place.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Places and only return the `id`
   * const placeWithIdOnly = await prisma.place.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PlaceCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PlaceCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlacePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Place.
   * @param {PlaceDeleteArgs} args - Arguments to delete one Place.
   * @example
   * // Delete one Place
   * const Place = await prisma.place.delete({
   *   where: {
   *     // ... filter to delete one Place
   *   }
   * })
   * 
   */
  delete<T extends PlaceDeleteArgs>(args: Prisma.SelectSubset<T, PlaceDeleteArgs<ExtArgs>>): Prisma.Prisma__PlaceClient<runtime.Types.Result.GetResult<Prisma.$PlacePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Place.
   * @param {PlaceUpdateArgs} args - Arguments to update one Place.
   * @example
   * // Update one Place
   * const place = await prisma.place.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PlaceUpdateArgs>(args: Prisma.SelectSubset<T, PlaceUpdateArgs<ExtArgs>>): Prisma.Prisma__PlaceClient<runtime.Types.Result.GetResult<Prisma.$PlacePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Places.
   * @param {PlaceDeleteManyArgs} args - Arguments to filter Places to delete.
   * @example
   * // Delete a few Places
   * const { count } = await prisma.place.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PlaceDeleteManyArgs>(args?: Prisma.SelectSubset<T, PlaceDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Places.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaceUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Places
   * const place = await prisma.place.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PlaceUpdateManyArgs>(args: Prisma.SelectSubset<T, PlaceUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Places and returns the data updated in the database.
   * @param {PlaceUpdateManyAndReturnArgs} args - Arguments to update many Places.
   * @example
   * // Update many Places
   * const place = await prisma.place.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Places and only return the `id`
   * const placeWithIdOnly = await prisma.place.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PlaceUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PlaceUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PlacePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Place.
   * @param {PlaceUpsertArgs} args - Arguments to update or create a Place.
   * @example
   * // Update or create a Place
   * const place = await prisma.place.upsert({
   *   create: {
   *     // ... data to create a Place
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Place we want to update
   *   }
   * })
   */
  upsert<T extends PlaceUpsertArgs>(args: Prisma.SelectSubset<T, PlaceUpsertArgs<ExtArgs>>): Prisma.Prisma__PlaceClient<runtime.Types.Result.GetResult<Prisma.$PlacePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Places.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaceCountArgs} args - Arguments to filter Places to count.
   * @example
   * // Count the number of Places
   * const count = await prisma.place.count({
   *   where: {
   *     // ... the filter for the Places we want to count
   *   }
   * })
  **/
  count<T extends PlaceCountArgs>(
    args?: Prisma.Subset<T, PlaceCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PlaceCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Place.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaceAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PlaceAggregateArgs>(args: Prisma.Subset<T, PlaceAggregateArgs>): Prisma.PrismaPromise<GetPlaceAggregateType<T>>

  /**
   * Group by Place.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PlaceGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PlaceGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PlaceGroupByArgs['orderBy'] }
      : { orderBy?: PlaceGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PlaceGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPlaceGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Place model
 */
readonly fields: PlaceFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Place.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PlaceClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Place model
 */
export interface PlaceFieldRefs {
  readonly id: Prisma.FieldRef<"Place", 'String'>
  readonly name: Prisma.FieldRef<"Place", 'String'>
  readonly category: Prisma.FieldRef<"Place", 'String'>
  readonly description: Prisma.FieldRef<"Place", 'String'>
  readonly city: Prisma.FieldRef<"Place", 'String'>
  readonly latitude: Prisma.FieldRef<"Place", 'Float'>
  readonly longitude: Prisma.FieldRef<"Place", 'Float'>
  readonly address: Prisma.FieldRef<"Place", 'String'>
  readonly distance: Prisma.FieldRef<"Place", 'Float'>
  readonly openingHours: Prisma.FieldRef<"Place", 'String'>
  readonly priceRange: Prisma.FieldRef<"Place", 'String'>
  readonly estimatedCost: Prisma.FieldRef<"Place", 'Float'>
  readonly currency: Prisma.FieldRef<"Place", 'String'>
  readonly rating: Prisma.FieldRef<"Place", 'Float'>
  readonly accessibility: Prisma.FieldRef<"Place", 'String'>
  readonly culturalValue: Prisma.FieldRef<"Place", 'String'>
  readonly source: Prisma.FieldRef<"Place", 'String'>
  readonly sourceUrl: Prisma.FieldRef<"Place", 'String'>
  readonly imageUrl: Prisma.FieldRef<"Place", 'String'>
  readonly createdAt: Prisma.FieldRef<"Place", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Place", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Place findUnique
 */
export type PlaceFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Place
   */
  select?: Prisma.PlaceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Place
   */
  omit?: Prisma.PlaceOmit<ExtArgs> | null
  /**
   * Filter, which Place to fetch.
   */
  where: Prisma.PlaceWhereUniqueInput
}

/**
 * Place findUniqueOrThrow
 */
export type PlaceFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Place
   */
  select?: Prisma.PlaceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Place
   */
  omit?: Prisma.PlaceOmit<ExtArgs> | null
  /**
   * Filter, which Place to fetch.
   */
  where: Prisma.PlaceWhereUniqueInput
}

/**
 * Place findFirst
 */
export type PlaceFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Place
   */
  select?: Prisma.PlaceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Place
   */
  omit?: Prisma.PlaceOmit<ExtArgs> | null
  /**
   * Filter, which Place to fetch.
   */
  where?: Prisma.PlaceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Places to fetch.
   */
  orderBy?: Prisma.PlaceOrderByWithRelationInput | Prisma.PlaceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Places.
   */
  cursor?: Prisma.PlaceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Places from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Places.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Places.
   */
  distinct?: Prisma.PlaceScalarFieldEnum | Prisma.PlaceScalarFieldEnum[]
}

/**
 * Place findFirstOrThrow
 */
export type PlaceFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Place
   */
  select?: Prisma.PlaceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Place
   */
  omit?: Prisma.PlaceOmit<ExtArgs> | null
  /**
   * Filter, which Place to fetch.
   */
  where?: Prisma.PlaceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Places to fetch.
   */
  orderBy?: Prisma.PlaceOrderByWithRelationInput | Prisma.PlaceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Places.
   */
  cursor?: Prisma.PlaceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Places from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Places.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Places.
   */
  distinct?: Prisma.PlaceScalarFieldEnum | Prisma.PlaceScalarFieldEnum[]
}

/**
 * Place findMany
 */
export type PlaceFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Place
   */
  select?: Prisma.PlaceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Place
   */
  omit?: Prisma.PlaceOmit<ExtArgs> | null
  /**
   * Filter, which Places to fetch.
   */
  where?: Prisma.PlaceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Places to fetch.
   */
  orderBy?: Prisma.PlaceOrderByWithRelationInput | Prisma.PlaceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Places.
   */
  cursor?: Prisma.PlaceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Places from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Places.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Places.
   */
  distinct?: Prisma.PlaceScalarFieldEnum | Prisma.PlaceScalarFieldEnum[]
}

/**
 * Place create
 */
export type PlaceCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Place
   */
  select?: Prisma.PlaceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Place
   */
  omit?: Prisma.PlaceOmit<ExtArgs> | null
  /**
   * The data needed to create a Place.
   */
  data: Prisma.XOR<Prisma.PlaceCreateInput, Prisma.PlaceUncheckedCreateInput>
}

/**
 * Place createMany
 */
export type PlaceCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Places.
   */
  data: Prisma.PlaceCreateManyInput | Prisma.PlaceCreateManyInput[]
}

/**
 * Place createManyAndReturn
 */
export type PlaceCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Place
   */
  select?: Prisma.PlaceSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Place
   */
  omit?: Prisma.PlaceOmit<ExtArgs> | null
  /**
   * The data used to create many Places.
   */
  data: Prisma.PlaceCreateManyInput | Prisma.PlaceCreateManyInput[]
}

/**
 * Place update
 */
export type PlaceUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Place
   */
  select?: Prisma.PlaceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Place
   */
  omit?: Prisma.PlaceOmit<ExtArgs> | null
  /**
   * The data needed to update a Place.
   */
  data: Prisma.XOR<Prisma.PlaceUpdateInput, Prisma.PlaceUncheckedUpdateInput>
  /**
   * Choose, which Place to update.
   */
  where: Prisma.PlaceWhereUniqueInput
}

/**
 * Place updateMany
 */
export type PlaceUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Places.
   */
  data: Prisma.XOR<Prisma.PlaceUpdateManyMutationInput, Prisma.PlaceUncheckedUpdateManyInput>
  /**
   * Filter which Places to update
   */
  where?: Prisma.PlaceWhereInput
  /**
   * Limit how many Places to update.
   */
  limit?: number
}

/**
 * Place updateManyAndReturn
 */
export type PlaceUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Place
   */
  select?: Prisma.PlaceSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Place
   */
  omit?: Prisma.PlaceOmit<ExtArgs> | null
  /**
   * The data used to update Places.
   */
  data: Prisma.XOR<Prisma.PlaceUpdateManyMutationInput, Prisma.PlaceUncheckedUpdateManyInput>
  /**
   * Filter which Places to update
   */
  where?: Prisma.PlaceWhereInput
  /**
   * Limit how many Places to update.
   */
  limit?: number
}

/**
 * Place upsert
 */
export type PlaceUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Place
   */
  select?: Prisma.PlaceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Place
   */
  omit?: Prisma.PlaceOmit<ExtArgs> | null
  /**
   * The filter to search for the Place to update in case it exists.
   */
  where: Prisma.PlaceWhereUniqueInput
  /**
   * In case the Place found by the `where` argument doesn't exist, create a new Place with this data.
   */
  create: Prisma.XOR<Prisma.PlaceCreateInput, Prisma.PlaceUncheckedCreateInput>
  /**
   * In case the Place was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PlaceUpdateInput, Prisma.PlaceUncheckedUpdateInput>
}

/**
 * Place delete
 */
export type PlaceDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Place
   */
  select?: Prisma.PlaceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Place
   */
  omit?: Prisma.PlaceOmit<ExtArgs> | null
  /**
   * Filter which Place to delete.
   */
  where: Prisma.PlaceWhereUniqueInput
}

/**
 * Place deleteMany
 */
export type PlaceDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Places to delete
   */
  where?: Prisma.PlaceWhereInput
  /**
   * Limit how many Places to delete.
   */
  limit?: number
}

/**
 * Place without action
 */
export type PlaceDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Place
   */
  select?: Prisma.PlaceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Place
   */
  omit?: Prisma.PlaceOmit<ExtArgs> | null
}
