
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  User: 'User',
  CityMission: 'CityMission',
  Place: 'Place',
  CommunityReport: 'CommunityReport',
  HeritageTrail: 'HeritageTrail',
  RouteRecommendation: 'RouteRecommendation'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const UserScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type UserScalarFieldEnum = (typeof UserScalarFieldEnum)[keyof typeof UserScalarFieldEnum]


export const CityMissionScalarFieldEnum = {
  id: 'id',
  city: 'city',
  startLocation: 'startLocation',
  destination: 'destination',
  interests: 'interests',
  budget: 'budget',
  currency: 'currency',
  duration: 'duration',
  transport: 'transport',
  accessibility: 'accessibility',
  priorities: 'priorities',
  latitude: 'latitude',
  longitude: 'longitude',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CityMissionScalarFieldEnum = (typeof CityMissionScalarFieldEnum)[keyof typeof CityMissionScalarFieldEnum]


export const PlaceScalarFieldEnum = {
  id: 'id',
  name: 'name',
  category: 'category',
  description: 'description',
  city: 'city',
  latitude: 'latitude',
  longitude: 'longitude',
  address: 'address',
  distance: 'distance',
  openingHours: 'openingHours',
  priceRange: 'priceRange',
  estimatedCost: 'estimatedCost',
  currency: 'currency',
  rating: 'rating',
  accessibility: 'accessibility',
  culturalValue: 'culturalValue',
  source: 'source',
  sourceUrl: 'sourceUrl',
  imageUrl: 'imageUrl',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PlaceScalarFieldEnum = (typeof PlaceScalarFieldEnum)[keyof typeof PlaceScalarFieldEnum]


export const CommunityReportScalarFieldEnum = {
  id: 'id',
  city: 'city',
  category: 'category',
  description: 'description',
  latitude: 'latitude',
  longitude: 'longitude',
  address: 'address',
  reportTime: 'reportTime',
  status: 'status',
  corroborations: 'corroborations',
  imageUrl: 'imageUrl',
  audioUrl: 'audioUrl',
  submittedBy: 'submittedBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CommunityReportScalarFieldEnum = (typeof CommunityReportScalarFieldEnum)[keyof typeof CommunityReportScalarFieldEnum]


export const HeritageTrailScalarFieldEnum = {
  id: 'id',
  city: 'city',
  name: 'name',
  description: 'description',
  sites: 'sites',
  distance: 'distance',
  duration: 'duration',
  culturalContext: 'culturalContext',
  source: 'source',
  sourceUrl: 'sourceUrl',
  createdAt: 'createdAt'
} as const

export type HeritageTrailScalarFieldEnum = (typeof HeritageTrailScalarFieldEnum)[keyof typeof HeritageTrailScalarFieldEnum]


export const RouteRecommendationScalarFieldEnum = {
  id: 'id',
  city: 'city',
  from: 'from',
  to: 'to',
  transport: 'transport',
  distance: 'distance',
  estimatedTime: 'estimatedTime',
  reportCount: 'reportCount',
  concerns: 'concerns',
  source: 'source',
  sourceUrl: 'sourceUrl',
  createdAt: 'createdAt'
} as const

export type RouteRecommendationScalarFieldEnum = (typeof RouteRecommendationScalarFieldEnum)[keyof typeof RouteRecommendationScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

