
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `RouteRecommendation` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model RouteRecommendation
 * 
 */
export type RouteRecommendationModel = runtime.Types.Result.DefaultSelection<Prisma.$RouteRecommendationPayload>

export type AggregateRouteRecommendation = {
  _count: RouteRecommendationCountAggregateOutputType | null
  _avg: RouteRecommendationAvgAggregateOutputType | null
  _sum: RouteRecommendationSumAggregateOutputType | null
  _min: RouteRecommendationMinAggregateOutputType | null
  _max: RouteRecommendationMaxAggregateOutputType | null
}

export type RouteRecommendationAvgAggregateOutputType = {
  distance: number | null
  reportCount: number | null
}

export type RouteRecommendationSumAggregateOutputType = {
  distance: number | null
  reportCount: number | null
}

export type RouteRecommendationMinAggregateOutputType = {
  id: string | null
  city: string | null
  from: string | null
  to: string | null
  transport: string | null
  distance: number | null
  estimatedTime: string | null
  reportCount: number | null
  concerns: string | null
  source: string | null
  sourceUrl: string | null
  createdAt: Date | null
}

export type RouteRecommendationMaxAggregateOutputType = {
  id: string | null
  city: string | null
  from: string | null
  to: string | null
  transport: string | null
  distance: number | null
  estimatedTime: string | null
  reportCount: number | null
  concerns: string | null
  source: string | null
  sourceUrl: string | null
  createdAt: Date | null
}

export type RouteRecommendationCountAggregateOutputType = {
  id: number
  city: number
  from: number
  to: number
  transport: number
  distance: number
  estimatedTime: number
  reportCount: number
  concerns: number
  source: number
  sourceUrl: number
  createdAt: number
  _all: number
}


export type RouteRecommendationAvgAggregateInputType = {
  distance?: true
  reportCount?: true
}

export type RouteRecommendationSumAggregateInputType = {
  distance?: true
  reportCount?: true
}

export type RouteRecommendationMinAggregateInputType = {
  id?: true
  city?: true
  from?: true
  to?: true
  transport?: true
  distance?: true
  estimatedTime?: true
  reportCount?: true
  concerns?: true
  source?: true
  sourceUrl?: true
  createdAt?: true
}

export type RouteRecommendationMaxAggregateInputType = {
  id?: true
  city?: true
  from?: true
  to?: true
  transport?: true
  distance?: true
  estimatedTime?: true
  reportCount?: true
  concerns?: true
  source?: true
  sourceUrl?: true
  createdAt?: true
}

export type RouteRecommendationCountAggregateInputType = {
  id?: true
  city?: true
  from?: true
  to?: true
  transport?: true
  distance?: true
  estimatedTime?: true
  reportCount?: true
  concerns?: true
  source?: true
  sourceUrl?: true
  createdAt?: true
  _all?: true
}

export type RouteRecommendationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RouteRecommendation to aggregate.
   */
  where?: Prisma.RouteRecommendationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RouteRecommendations to fetch.
   */
  orderBy?: Prisma.RouteRecommendationOrderByWithRelationInput | Prisma.RouteRecommendationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RouteRecommendationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RouteRecommendations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RouteRecommendations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned RouteRecommendations
  **/
  _count?: true | RouteRecommendationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: RouteRecommendationAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: RouteRecommendationSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RouteRecommendationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RouteRecommendationMaxAggregateInputType
}

export type GetRouteRecommendationAggregateType<T extends RouteRecommendationAggregateArgs> = {
      [P in keyof T & keyof AggregateRouteRecommendation]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRouteRecommendation[P]>
    : Prisma.GetScalarType<T[P], AggregateRouteRecommendation[P]>
}




export type RouteRecommendationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RouteRecommendationWhereInput
  orderBy?: Prisma.RouteRecommendationOrderByWithAggregationInput | Prisma.RouteRecommendationOrderByWithAggregationInput[]
  by: Prisma.RouteRecommendationScalarFieldEnum[] | Prisma.RouteRecommendationScalarFieldEnum
  having?: Prisma.RouteRecommendationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RouteRecommendationCountAggregateInputType | true
  _avg?: RouteRecommendationAvgAggregateInputType
  _sum?: RouteRecommendationSumAggregateInputType
  _min?: RouteRecommendationMinAggregateInputType
  _max?: RouteRecommendationMaxAggregateInputType
}

export type RouteRecommendationGroupByOutputType = {
  id: string
  city: string
  from: string
  to: string
  transport: string
  distance: number | null
  estimatedTime: string | null
  reportCount: number
  concerns: string | null
  source: string
  sourceUrl: string | null
  createdAt: Date
  _count: RouteRecommendationCountAggregateOutputType | null
  _avg: RouteRecommendationAvgAggregateOutputType | null
  _sum: RouteRecommendationSumAggregateOutputType | null
  _min: RouteRecommendationMinAggregateOutputType | null
  _max: RouteRecommendationMaxAggregateOutputType | null
}

type GetRouteRecommendationGroupByPayload<T extends RouteRecommendationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RouteRecommendationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RouteRecommendationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RouteRecommendationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RouteRecommendationGroupByOutputType[P]>
      }
    >
  >



export type RouteRecommendationWhereInput = {
  AND?: Prisma.RouteRecommendationWhereInput | Prisma.RouteRecommendationWhereInput[]
  OR?: Prisma.RouteRecommendationWhereInput[]
  NOT?: Prisma.RouteRecommendationWhereInput | Prisma.RouteRecommendationWhereInput[]
  id?: Prisma.StringFilter<"RouteRecommendation"> | string
  city?: Prisma.StringFilter<"RouteRecommendation"> | string
  from?: Prisma.StringFilter<"RouteRecommendation"> | string
  to?: Prisma.StringFilter<"RouteRecommendation"> | string
  transport?: Prisma.StringFilter<"RouteRecommendation"> | string
  distance?: Prisma.FloatNullableFilter<"RouteRecommendation"> | number | null
  estimatedTime?: Prisma.StringNullableFilter<"RouteRecommendation"> | string | null
  reportCount?: Prisma.IntFilter<"RouteRecommendation"> | number
  concerns?: Prisma.StringNullableFilter<"RouteRecommendation"> | string | null
  source?: Prisma.StringFilter<"RouteRecommendation"> | string
  sourceUrl?: Prisma.StringNullableFilter<"RouteRecommendation"> | string | null
  createdAt?: Prisma.DateTimeFilter<"RouteRecommendation"> | Date | string
}

export type RouteRecommendationOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  city?: Prisma.SortOrder
  from?: Prisma.SortOrder
  to?: Prisma.SortOrder
  transport?: Prisma.SortOrder
  distance?: Prisma.SortOrderInput | Prisma.SortOrder
  estimatedTime?: Prisma.SortOrderInput | Prisma.SortOrder
  reportCount?: Prisma.SortOrder
  concerns?: Prisma.SortOrderInput | Prisma.SortOrder
  source?: Prisma.SortOrder
  sourceUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type RouteRecommendationWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.RouteRecommendationWhereInput | Prisma.RouteRecommendationWhereInput[]
  OR?: Prisma.RouteRecommendationWhereInput[]
  NOT?: Prisma.RouteRecommendationWhereInput | Prisma.RouteRecommendationWhereInput[]
  city?: Prisma.StringFilter<"RouteRecommendation"> | string
  from?: Prisma.StringFilter<"RouteRecommendation"> | string
  to?: Prisma.StringFilter<"RouteRecommendation"> | string
  transport?: Prisma.StringFilter<"RouteRecommendation"> | string
  distance?: Prisma.FloatNullableFilter<"RouteRecommendation"> | number | null
  estimatedTime?: Prisma.StringNullableFilter<"RouteRecommendation"> | string | null
  reportCount?: Prisma.IntFilter<"RouteRecommendation"> | number
  concerns?: Prisma.StringNullableFilter<"RouteRecommendation"> | string | null
  source?: Prisma.StringFilter<"RouteRecommendation"> | string
  sourceUrl?: Prisma.StringNullableFilter<"RouteRecommendation"> | string | null
  createdAt?: Prisma.DateTimeFilter<"RouteRecommendation"> | Date | string
}, "id">

export type RouteRecommendationOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  city?: Prisma.SortOrder
  from?: Prisma.SortOrder
  to?: Prisma.SortOrder
  transport?: Prisma.SortOrder
  distance?: Prisma.SortOrderInput | Prisma.SortOrder
  estimatedTime?: Prisma.SortOrderInput | Prisma.SortOrder
  reportCount?: Prisma.SortOrder
  concerns?: Prisma.SortOrderInput | Prisma.SortOrder
  source?: Prisma.SortOrder
  sourceUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.RouteRecommendationCountOrderByAggregateInput
  _avg?: Prisma.RouteRecommendationAvgOrderByAggregateInput
  _max?: Prisma.RouteRecommendationMaxOrderByAggregateInput
  _min?: Prisma.RouteRecommendationMinOrderByAggregateInput
  _sum?: Prisma.RouteRecommendationSumOrderByAggregateInput
}

export type RouteRecommendationScalarWhereWithAggregatesInput = {
  AND?: Prisma.RouteRecommendationScalarWhereWithAggregatesInput | Prisma.RouteRecommendationScalarWhereWithAggregatesInput[]
  OR?: Prisma.RouteRecommendationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RouteRecommendationScalarWhereWithAggregatesInput | Prisma.RouteRecommendationScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"RouteRecommendation"> | string
  city?: Prisma.StringWithAggregatesFilter<"RouteRecommendation"> | string
  from?: Prisma.StringWithAggregatesFilter<"RouteRecommendation"> | string
  to?: Prisma.StringWithAggregatesFilter<"RouteRecommendation"> | string
  transport?: Prisma.StringWithAggregatesFilter<"RouteRecommendation"> | string
  distance?: Prisma.FloatNullableWithAggregatesFilter<"RouteRecommendation"> | number | null
  estimatedTime?: Prisma.StringNullableWithAggregatesFilter<"RouteRecommendation"> | string | null
  reportCount?: Prisma.IntWithAggregatesFilter<"RouteRecommendation"> | number
  concerns?: Prisma.StringNullableWithAggregatesFilter<"RouteRecommendation"> | string | null
  source?: Prisma.StringWithAggregatesFilter<"RouteRecommendation"> | string
  sourceUrl?: Prisma.StringNullableWithAggregatesFilter<"RouteRecommendation"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"RouteRecommendation"> | Date | string
}

export type RouteRecommendationCreateInput = {
  id?: string
  city: string
  from: string
  to: string
  transport: string
  distance?: number | null
  estimatedTime?: string | null
  reportCount?: number
  concerns?: string | null
  source?: string
  sourceUrl?: string | null
  createdAt?: Date | string
}

export type RouteRecommendationUncheckedCreateInput = {
  id?: string
  city: string
  from: string
  to: string
  transport: string
  distance?: number | null
  estimatedTime?: string | null
  reportCount?: number
  concerns?: string | null
  source?: string
  sourceUrl?: string | null
  createdAt?: Date | string
}

export type RouteRecommendationUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  from?: Prisma.StringFieldUpdateOperationsInput | string
  to?: Prisma.StringFieldUpdateOperationsInput | string
  transport?: Prisma.StringFieldUpdateOperationsInput | string
  distance?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  estimatedTime?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reportCount?: Prisma.IntFieldUpdateOperationsInput | number
  concerns?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.StringFieldUpdateOperationsInput | string
  sourceUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RouteRecommendationUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  from?: Prisma.StringFieldUpdateOperationsInput | string
  to?: Prisma.StringFieldUpdateOperationsInput | string
  transport?: Prisma.StringFieldUpdateOperationsInput | string
  distance?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  estimatedTime?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reportCount?: Prisma.IntFieldUpdateOperationsInput | number
  concerns?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.StringFieldUpdateOperationsInput | string
  sourceUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RouteRecommendationCreateManyInput = {
  id?: string
  city: string
  from: string
  to: string
  transport: string
  distance?: number | null
  estimatedTime?: string | null
  reportCount?: number
  concerns?: string | null
  source?: string
  sourceUrl?: string | null
  createdAt?: Date | string
}

export type RouteRecommendationUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  from?: Prisma.StringFieldUpdateOperationsInput | string
  to?: Prisma.StringFieldUpdateOperationsInput | string
  transport?: Prisma.StringFieldUpdateOperationsInput | string
  distance?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  estimatedTime?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reportCount?: Prisma.IntFieldUpdateOperationsInput | number
  concerns?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.StringFieldUpdateOperationsInput | string
  sourceUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RouteRecommendationUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  city?: Prisma.StringFieldUpdateOperationsInput | string
  from?: Prisma.StringFieldUpdateOperationsInput | string
  to?: Prisma.StringFieldUpdateOperationsInput | string
  transport?: Prisma.StringFieldUpdateOperationsInput | string
  distance?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  estimatedTime?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reportCount?: Prisma.IntFieldUpdateOperationsInput | number
  concerns?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  source?: Prisma.StringFieldUpdateOperationsInput | string
  sourceUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RouteRecommendationCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  city?: Prisma.SortOrder
  from?: Prisma.SortOrder
  to?: Prisma.SortOrder
  transport?: Prisma.SortOrder
  distance?: Prisma.SortOrder
  estimatedTime?: Prisma.SortOrder
  reportCount?: Prisma.SortOrder
  concerns?: Prisma.SortOrder
  source?: Prisma.SortOrder
  sourceUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type RouteRecommendationAvgOrderByAggregateInput = {
  distance?: Prisma.SortOrder
  reportCount?: Prisma.SortOrder
}

export type RouteRecommendationMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  city?: Prisma.SortOrder
  from?: Prisma.SortOrder
  to?: Prisma.SortOrder
  transport?: Prisma.SortOrder
  distance?: Prisma.SortOrder
  estimatedTime?: Prisma.SortOrder
  reportCount?: Prisma.SortOrder
  concerns?: Prisma.SortOrder
  source?: Prisma.SortOrder
  sourceUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type RouteRecommendationMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  city?: Prisma.SortOrder
  from?: Prisma.SortOrder
  to?: Prisma.SortOrder
  transport?: Prisma.SortOrder
  distance?: Prisma.SortOrder
  estimatedTime?: Prisma.SortOrder
  reportCount?: Prisma.SortOrder
  concerns?: Prisma.SortOrder
  source?: Prisma.SortOrder
  sourceUrl?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type RouteRecommendationSumOrderByAggregateInput = {
  distance?: Prisma.SortOrder
  reportCount?: Prisma.SortOrder
}



export type RouteRecommendationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  city?: boolean
  from?: boolean
  to?: boolean
  transport?: boolean
  distance?: boolean
  estimatedTime?: boolean
  reportCount?: boolean
  concerns?: boolean
  source?: boolean
  sourceUrl?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["routeRecommendation"]>

export type RouteRecommendationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  city?: boolean
  from?: boolean
  to?: boolean
  transport?: boolean
  distance?: boolean
  estimatedTime?: boolean
  reportCount?: boolean
  concerns?: boolean
  source?: boolean
  sourceUrl?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["routeRecommendation"]>

export type RouteRecommendationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  city?: boolean
  from?: boolean
  to?: boolean
  transport?: boolean
  distance?: boolean
  estimatedTime?: boolean
  reportCount?: boolean
  concerns?: boolean
  source?: boolean
  sourceUrl?: boolean
  createdAt?: boolean
}, ExtArgs["result"]["routeRecommendation"]>

export type RouteRecommendationSelectScalar = {
  id?: boolean
  city?: boolean
  from?: boolean
  to?: boolean
  transport?: boolean
  distance?: boolean
  estimatedTime?: boolean
  reportCount?: boolean
  concerns?: boolean
  source?: boolean
  sourceUrl?: boolean
  createdAt?: boolean
}

export type RouteRecommendationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "city" | "from" | "to" | "transport" | "distance" | "estimatedTime" | "reportCount" | "concerns" | "source" | "sourceUrl" | "createdAt", ExtArgs["result"]["routeRecommendation"]>

export type $RouteRecommendationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "RouteRecommendation"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    city: string
    from: string
    to: string
    transport: string
    distance: number | null
    estimatedTime: string | null
    reportCount: number
    concerns: string | null
    source: string
    sourceUrl: string | null
    createdAt: Date
  }, ExtArgs["result"]["routeRecommendation"]>
  composites: {}
}

export type RouteRecommendationGetPayload<S extends boolean | null | undefined | RouteRecommendationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RouteRecommendationPayload, S>

export type RouteRecommendationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RouteRecommendationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RouteRecommendationCountAggregateInputType | true
  }

export interface RouteRecommendationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['RouteRecommendation'], meta: { name: 'RouteRecommendation' } }
  /**
   * Find zero or one RouteRecommendation that matches the filter.
   * @param {RouteRecommendationFindUniqueArgs} args - Arguments to find a RouteRecommendation
   * @example
   * // Get one RouteRecommendation
   * const routeRecommendation = await prisma.routeRecommendation.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RouteRecommendationFindUniqueArgs>(args: Prisma.SelectSubset<T, RouteRecommendationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RouteRecommendationClient<runtime.Types.Result.GetResult<Prisma.$RouteRecommendationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one RouteRecommendation that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RouteRecommendationFindUniqueOrThrowArgs} args - Arguments to find a RouteRecommendation
   * @example
   * // Get one RouteRecommendation
   * const routeRecommendation = await prisma.routeRecommendation.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RouteRecommendationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RouteRecommendationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RouteRecommendationClient<runtime.Types.Result.GetResult<Prisma.$RouteRecommendationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RouteRecommendation that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RouteRecommendationFindFirstArgs} args - Arguments to find a RouteRecommendation
   * @example
   * // Get one RouteRecommendation
   * const routeRecommendation = await prisma.routeRecommendation.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RouteRecommendationFindFirstArgs>(args?: Prisma.SelectSubset<T, RouteRecommendationFindFirstArgs<ExtArgs>>): Prisma.Prisma__RouteRecommendationClient<runtime.Types.Result.GetResult<Prisma.$RouteRecommendationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RouteRecommendation that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RouteRecommendationFindFirstOrThrowArgs} args - Arguments to find a RouteRecommendation
   * @example
   * // Get one RouteRecommendation
   * const routeRecommendation = await prisma.routeRecommendation.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RouteRecommendationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RouteRecommendationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RouteRecommendationClient<runtime.Types.Result.GetResult<Prisma.$RouteRecommendationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RouteRecommendations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RouteRecommendationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RouteRecommendations
   * const routeRecommendations = await prisma.routeRecommendation.findMany()
   * 
   * // Get first 10 RouteRecommendations
   * const routeRecommendations = await prisma.routeRecommendation.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const routeRecommendationWithIdOnly = await prisma.routeRecommendation.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends RouteRecommendationFindManyArgs>(args?: Prisma.SelectSubset<T, RouteRecommendationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RouteRecommendationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a RouteRecommendation.
   * @param {RouteRecommendationCreateArgs} args - Arguments to create a RouteRecommendation.
   * @example
   * // Create one RouteRecommendation
   * const RouteRecommendation = await prisma.routeRecommendation.create({
   *   data: {
   *     // ... data to create a RouteRecommendation
   *   }
   * })
   * 
   */
  create<T extends RouteRecommendationCreateArgs>(args: Prisma.SelectSubset<T, RouteRecommendationCreateArgs<ExtArgs>>): Prisma.Prisma__RouteRecommendationClient<runtime.Types.Result.GetResult<Prisma.$RouteRecommendationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many RouteRecommendations.
   * @param {RouteRecommendationCreateManyArgs} args - Arguments to create many RouteRecommendations.
   * @example
   * // Create many RouteRecommendations
   * const routeRecommendation = await prisma.routeRecommendation.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RouteRecommendationCreateManyArgs>(args?: Prisma.SelectSubset<T, RouteRecommendationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many RouteRecommendations and returns the data saved in the database.
   * @param {RouteRecommendationCreateManyAndReturnArgs} args - Arguments to create many RouteRecommendations.
   * @example
   * // Create many RouteRecommendations
   * const routeRecommendation = await prisma.routeRecommendation.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many RouteRecommendations and only return the `id`
   * const routeRecommendationWithIdOnly = await prisma.routeRecommendation.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RouteRecommendationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RouteRecommendationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RouteRecommendationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a RouteRecommendation.
   * @param {RouteRecommendationDeleteArgs} args - Arguments to delete one RouteRecommendation.
   * @example
   * // Delete one RouteRecommendation
   * const RouteRecommendation = await prisma.routeRecommendation.delete({
   *   where: {
   *     // ... filter to delete one RouteRecommendation
   *   }
   * })
   * 
   */
  delete<T extends RouteRecommendationDeleteArgs>(args: Prisma.SelectSubset<T, RouteRecommendationDeleteArgs<ExtArgs>>): Prisma.Prisma__RouteRecommendationClient<runtime.Types.Result.GetResult<Prisma.$RouteRecommendationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one RouteRecommendation.
   * @param {RouteRecommendationUpdateArgs} args - Arguments to update one RouteRecommendation.
   * @example
   * // Update one RouteRecommendation
   * const routeRecommendation = await prisma.routeRecommendation.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RouteRecommendationUpdateArgs>(args: Prisma.SelectSubset<T, RouteRecommendationUpdateArgs<ExtArgs>>): Prisma.Prisma__RouteRecommendationClient<runtime.Types.Result.GetResult<Prisma.$RouteRecommendationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more RouteRecommendations.
   * @param {RouteRecommendationDeleteManyArgs} args - Arguments to filter RouteRecommendations to delete.
   * @example
   * // Delete a few RouteRecommendations
   * const { count } = await prisma.routeRecommendation.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RouteRecommendationDeleteManyArgs>(args?: Prisma.SelectSubset<T, RouteRecommendationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RouteRecommendations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RouteRecommendationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RouteRecommendations
   * const routeRecommendation = await prisma.routeRecommendation.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RouteRecommendationUpdateManyArgs>(args: Prisma.SelectSubset<T, RouteRecommendationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RouteRecommendations and returns the data updated in the database.
   * @param {RouteRecommendationUpdateManyAndReturnArgs} args - Arguments to update many RouteRecommendations.
   * @example
   * // Update many RouteRecommendations
   * const routeRecommendation = await prisma.routeRecommendation.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more RouteRecommendations and only return the `id`
   * const routeRecommendationWithIdOnly = await prisma.routeRecommendation.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RouteRecommendationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RouteRecommendationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RouteRecommendationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one RouteRecommendation.
   * @param {RouteRecommendationUpsertArgs} args - Arguments to update or create a RouteRecommendation.
   * @example
   * // Update or create a RouteRecommendation
   * const routeRecommendation = await prisma.routeRecommendation.upsert({
   *   create: {
   *     // ... data to create a RouteRecommendation
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RouteRecommendation we want to update
   *   }
   * })
   */
  upsert<T extends RouteRecommendationUpsertArgs>(args: Prisma.SelectSubset<T, RouteRecommendationUpsertArgs<ExtArgs>>): Prisma.Prisma__RouteRecommendationClient<runtime.Types.Result.GetResult<Prisma.$RouteRecommendationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of RouteRecommendations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RouteRecommendationCountArgs} args - Arguments to filter RouteRecommendations to count.
   * @example
   * // Count the number of RouteRecommendations
   * const count = await prisma.routeRecommendation.count({
   *   where: {
   *     // ... the filter for the RouteRecommendations we want to count
   *   }
   * })
  **/
  count<T extends RouteRecommendationCountArgs>(
    args?: Prisma.Subset<T, RouteRecommendationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RouteRecommendationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RouteRecommendation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RouteRecommendationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RouteRecommendationAggregateArgs>(args: Prisma.Subset<T, RouteRecommendationAggregateArgs>): Prisma.PrismaPromise<GetRouteRecommendationAggregateType<T>>

  /**
   * Group by RouteRecommendation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RouteRecommendationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RouteRecommendationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RouteRecommendationGroupByArgs['orderBy'] }
      : { orderBy?: RouteRecommendationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RouteRecommendationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRouteRecommendationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the RouteRecommendation model
 */
readonly fields: RouteRecommendationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RouteRecommendation.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RouteRecommendationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the RouteRecommendation model
 */
export interface RouteRecommendationFieldRefs {
  readonly id: Prisma.FieldRef<"RouteRecommendation", 'String'>
  readonly city: Prisma.FieldRef<"RouteRecommendation", 'String'>
  readonly from: Prisma.FieldRef<"RouteRecommendation", 'String'>
  readonly to: Prisma.FieldRef<"RouteRecommendation", 'String'>
  readonly transport: Prisma.FieldRef<"RouteRecommendation", 'String'>
  readonly distance: Prisma.FieldRef<"RouteRecommendation", 'Float'>
  readonly estimatedTime: Prisma.FieldRef<"RouteRecommendation", 'String'>
  readonly reportCount: Prisma.FieldRef<"RouteRecommendation", 'Int'>
  readonly concerns: Prisma.FieldRef<"RouteRecommendation", 'String'>
  readonly source: Prisma.FieldRef<"RouteRecommendation", 'String'>
  readonly sourceUrl: Prisma.FieldRef<"RouteRecommendation", 'String'>
  readonly createdAt: Prisma.FieldRef<"RouteRecommendation", 'DateTime'>
}
    

// Custom InputTypes
/**
 * RouteRecommendation findUnique
 */
export type RouteRecommendationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RouteRecommendation
   */
  select?: Prisma.RouteRecommendationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RouteRecommendation
   */
  omit?: Prisma.RouteRecommendationOmit<ExtArgs> | null
  /**
   * Filter, which RouteRecommendation to fetch.
   */
  where: Prisma.RouteRecommendationWhereUniqueInput
}

/**
 * RouteRecommendation findUniqueOrThrow
 */
export type RouteRecommendationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RouteRecommendation
   */
  select?: Prisma.RouteRecommendationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RouteRecommendation
   */
  omit?: Prisma.RouteRecommendationOmit<ExtArgs> | null
  /**
   * Filter, which RouteRecommendation to fetch.
   */
  where: Prisma.RouteRecommendationWhereUniqueInput
}

/**
 * RouteRecommendation findFirst
 */
export type RouteRecommendationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RouteRecommendation
   */
  select?: Prisma.RouteRecommendationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RouteRecommendation
   */
  omit?: Prisma.RouteRecommendationOmit<ExtArgs> | null
  /**
   * Filter, which RouteRecommendation to fetch.
   */
  where?: Prisma.RouteRecommendationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RouteRecommendations to fetch.
   */
  orderBy?: Prisma.RouteRecommendationOrderByWithRelationInput | Prisma.RouteRecommendationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RouteRecommendations.
   */
  cursor?: Prisma.RouteRecommendationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RouteRecommendations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RouteRecommendations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RouteRecommendations.
   */
  distinct?: Prisma.RouteRecommendationScalarFieldEnum | Prisma.RouteRecommendationScalarFieldEnum[]
}

/**
 * RouteRecommendation findFirstOrThrow
 */
export type RouteRecommendationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RouteRecommendation
   */
  select?: Prisma.RouteRecommendationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RouteRecommendation
   */
  omit?: Prisma.RouteRecommendationOmit<ExtArgs> | null
  /**
   * Filter, which RouteRecommendation to fetch.
   */
  where?: Prisma.RouteRecommendationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RouteRecommendations to fetch.
   */
  orderBy?: Prisma.RouteRecommendationOrderByWithRelationInput | Prisma.RouteRecommendationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RouteRecommendations.
   */
  cursor?: Prisma.RouteRecommendationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RouteRecommendations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RouteRecommendations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RouteRecommendations.
   */
  distinct?: Prisma.RouteRecommendationScalarFieldEnum | Prisma.RouteRecommendationScalarFieldEnum[]
}

/**
 * RouteRecommendation findMany
 */
export type RouteRecommendationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RouteRecommendation
   */
  select?: Prisma.RouteRecommendationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RouteRecommendation
   */
  omit?: Prisma.RouteRecommendationOmit<ExtArgs> | null
  /**
   * Filter, which RouteRecommendations to fetch.
   */
  where?: Prisma.RouteRecommendationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RouteRecommendations to fetch.
   */
  orderBy?: Prisma.RouteRecommendationOrderByWithRelationInput | Prisma.RouteRecommendationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing RouteRecommendations.
   */
  cursor?: Prisma.RouteRecommendationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RouteRecommendations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RouteRecommendations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RouteRecommendations.
   */
  distinct?: Prisma.RouteRecommendationScalarFieldEnum | Prisma.RouteRecommendationScalarFieldEnum[]
}

/**
 * RouteRecommendation create
 */
export type RouteRecommendationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RouteRecommendation
   */
  select?: Prisma.RouteRecommendationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RouteRecommendation
   */
  omit?: Prisma.RouteRecommendationOmit<ExtArgs> | null
  /**
   * The data needed to create a RouteRecommendation.
   */
  data: Prisma.XOR<Prisma.RouteRecommendationCreateInput, Prisma.RouteRecommendationUncheckedCreateInput>
}

/**
 * RouteRecommendation createMany
 */
export type RouteRecommendationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many RouteRecommendations.
   */
  data: Prisma.RouteRecommendationCreateManyInput | Prisma.RouteRecommendationCreateManyInput[]
}

/**
 * RouteRecommendation createManyAndReturn
 */
export type RouteRecommendationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RouteRecommendation
   */
  select?: Prisma.RouteRecommendationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RouteRecommendation
   */
  omit?: Prisma.RouteRecommendationOmit<ExtArgs> | null
  /**
   * The data used to create many RouteRecommendations.
   */
  data: Prisma.RouteRecommendationCreateManyInput | Prisma.RouteRecommendationCreateManyInput[]
}

/**
 * RouteRecommendation update
 */
export type RouteRecommendationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RouteRecommendation
   */
  select?: Prisma.RouteRecommendationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RouteRecommendation
   */
  omit?: Prisma.RouteRecommendationOmit<ExtArgs> | null
  /**
   * The data needed to update a RouteRecommendation.
   */
  data: Prisma.XOR<Prisma.RouteRecommendationUpdateInput, Prisma.RouteRecommendationUncheckedUpdateInput>
  /**
   * Choose, which RouteRecommendation to update.
   */
  where: Prisma.RouteRecommendationWhereUniqueInput
}

/**
 * RouteRecommendation updateMany
 */
export type RouteRecommendationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update RouteRecommendations.
   */
  data: Prisma.XOR<Prisma.RouteRecommendationUpdateManyMutationInput, Prisma.RouteRecommendationUncheckedUpdateManyInput>
  /**
   * Filter which RouteRecommendations to update
   */
  where?: Prisma.RouteRecommendationWhereInput
  /**
   * Limit how many RouteRecommendations to update.
   */
  limit?: number
}

/**
 * RouteRecommendation updateManyAndReturn
 */
export type RouteRecommendationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RouteRecommendation
   */
  select?: Prisma.RouteRecommendationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RouteRecommendation
   */
  omit?: Prisma.RouteRecommendationOmit<ExtArgs> | null
  /**
   * The data used to update RouteRecommendations.
   */
  data: Prisma.XOR<Prisma.RouteRecommendationUpdateManyMutationInput, Prisma.RouteRecommendationUncheckedUpdateManyInput>
  /**
   * Filter which RouteRecommendations to update
   */
  where?: Prisma.RouteRecommendationWhereInput
  /**
   * Limit how many RouteRecommendations to update.
   */
  limit?: number
}

/**
 * RouteRecommendation upsert
 */
export type RouteRecommendationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RouteRecommendation
   */
  select?: Prisma.RouteRecommendationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RouteRecommendation
   */
  omit?: Prisma.RouteRecommendationOmit<ExtArgs> | null
  /**
   * The filter to search for the RouteRecommendation to update in case it exists.
   */
  where: Prisma.RouteRecommendationWhereUniqueInput
  /**
   * In case the RouteRecommendation found by the `where` argument doesn't exist, create a new RouteRecommendation with this data.
   */
  create: Prisma.XOR<Prisma.RouteRecommendationCreateInput, Prisma.RouteRecommendationUncheckedCreateInput>
  /**
   * In case the RouteRecommendation was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RouteRecommendationUpdateInput, Prisma.RouteRecommendationUncheckedUpdateInput>
}

/**
 * RouteRecommendation delete
 */
export type RouteRecommendationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RouteRecommendation
   */
  select?: Prisma.RouteRecommendationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RouteRecommendation
   */
  omit?: Prisma.RouteRecommendationOmit<ExtArgs> | null
  /**
   * Filter which RouteRecommendation to delete.
   */
  where: Prisma.RouteRecommendationWhereUniqueInput
}

/**
 * RouteRecommendation deleteMany
 */
export type RouteRecommendationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RouteRecommendations to delete
   */
  where?: Prisma.RouteRecommendationWhereInput
  /**
   * Limit how many RouteRecommendations to delete.
   */
  limit?: number
}

/**
 * RouteRecommendation without action
 */
export type RouteRecommendationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RouteRecommendation
   */
  select?: Prisma.RouteRecommendationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RouteRecommendation
   */
  omit?: Prisma.RouteRecommendationOmit<ExtArgs> | null
}
