// SPDX-License-Identifier: MIT
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Auto-generated Routes Index
 *
 * Generated by @shogo-ai/sdk - DO NOT EDIT DIRECTLY
 */

import { Hono } from "hono"
import { PrismaClient } from "./prisma/client"

// Route imports
import { createUserRoutes, setPrisma as setPrismaUser, setUserHooks } from "./user.routes"
import { createCityMissionRoutes, setPrisma as setPrismaCityMission, setCityMissionHooks } from "./city-mission.routes"
import { createPlaceRoutes, setPrisma as setPrismaPlace, setPlaceHooks } from "./place.routes"
import { createCommunityReportRoutes, setPrisma as setPrismaCommunityReport, setCommunityReportHooks } from "./community-report.routes"
import { createHeritageTrailRoutes, setPrisma as setPrismaHeritageTrail, setHeritageTrailHooks } from "./heritage-trail.routes"
import { createRouteRecommendationRoutes, setPrisma as setPrismaRouteRecommendation, setRouteRecommendationHooks } from "./route-recommendation.routes"

// Hook imports
import { userHooks } from "./user.hooks"
import { cityMissionHooks } from "./city-mission.hooks"
import { placeHooks } from "./place.hooks"
import { communityReportHooks } from "./community-report.hooks"
import { heritageTrailHooks } from "./heritage-trail.hooks"
import { routeRecommendationHooks } from "./route-recommendation.hooks"

// Re-export route creators and setters
export {
  createUserRoutes,
  setPrismaUser,
  setUserHooks,
  createCityMissionRoutes,
  setPrismaCityMission,
  setCityMissionHooks,
  createPlaceRoutes,
  setPrismaPlace,
  setPlaceHooks,
  createCommunityReportRoutes,
  setPrismaCommunityReport,
  setCommunityReportHooks,
  createHeritageTrailRoutes,
  setPrismaHeritageTrail,
  setHeritageTrailHooks,
  createRouteRecommendationRoutes,
  setPrismaRouteRecommendation,
  setRouteRecommendationHooks
}

// Re-export hooks (model-specific)
export {
  userHooks,
  cityMissionHooks,
  placeHooks,
  communityReportHooks,
  heritageTrailHooks,
  routeRecommendationHooks
}

// Re-export hook types
export type { UserHooks } from "./user.hooks"
export type { CityMissionHooks } from "./city-mission.hooks"
export type { PlaceHooks } from "./place.hooks"
export type { CommunityReportHooks } from "./community-report.hooks"
export type { HeritageTrailHooks } from "./heritage-trail.hooks"
export type { RouteRecommendationHooks } from "./route-recommendation.hooks"

/**
 * Create all routes and mount them on a single Hono app
 */
export function createAllRoutes(prisma: PrismaClient): Hono {
  const app = new Hono()

  // Set Prisma client for all routes
  setPrismaUser(prisma)
  setPrismaCityMission(prisma)
  setPrismaPlace(prisma)
  setPrismaCommunityReport(prisma)
  setPrismaHeritageTrail(prisma)
  setPrismaRouteRecommendation(prisma)

  // Set hooks for all routes
  setUserHooks(userHooks)
  setCityMissionHooks(cityMissionHooks)
  setPlaceHooks(placeHooks)
  setCommunityReportHooks(communityReportHooks)
  setHeritageTrailHooks(heritageTrailHooks)
  setRouteRecommendationHooks(routeRecommendationHooks)

  // Mount routes
  app.route("/users", createUserRoutes())
  app.route("/city-missions", createCityMissionRoutes())
  app.route("/places", createPlaceRoutes())
  app.route("/community-reports", createCommunityReportRoutes())
  app.route("/heritage-trails", createHeritageTrailRoutes())
  app.route("/route-recommendations", createRouteRecommendationRoutes())

  return app
}
