// SPDX-License-Identifier: MIT
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Auto-generated Client Functions
 *
 * Fetch-based CRUD operations that call the Hono REST API.
 * No server-side imports — safe for browser bundles.
 * Generated by `shogo generate` - DO NOT EDIT
 */

import type {
  UserType,
  UserCreateInput,
  UserUpdateInput,
  CityMissionType,
  CityMissionCreateInput,
  CityMissionUpdateInput,
  PlaceType,
  PlaceCreateInput,
  PlaceUpdateInput,
  CommunityReportType,
  CommunityReportCreateInput,
  CommunityReportUpdateInput,
  HeritageTrailType,
  HeritageTrailCreateInput,
  HeritageTrailUpdateInput,
  RouteRecommendationType,
  RouteRecommendationCreateInput,
  RouteRecommendationUpdateInput,
} from './types'

/** Get the API base URL */
function getApiBase(): string {
  if (typeof window !== 'undefined') {
    return window.location.origin
  }
  return process.env.API_URL || 'http://localhost:3001'
}

// ============================================================================
// User Client Functions
// ============================================================================

/**
 * List all User records
 */
export async function getUserList(args: { data: { userId?: string; where?: Record<string, unknown> } }): Promise<UserType[]> {
  const params = new URLSearchParams()
  if (args.data.userId) params.set('userId', args.data.userId)
  if (args.data.where) {
    for (const [key, value] of Object.entries(args.data.where)) {
      if (value !== undefined && value !== null) params.set(key, String(value))
    }
  }
  const qs = params.toString()
  const url = `${getApiBase()}/api/users${qs ? `?${qs}` : ''}`
  const response = await fetch(url)
  if (!response.ok) {
    const err = await response.json().catch(() => ({ error: { message: response.statusText } }))
    throw new Error(err.error?.message || 'Failed to list User')
  }
  const json = await response.json()
  return (json.items || []) as UserType[]
}

/**
 * Get a single User by ID
 */
export async function getUserById(args: { data: { id: string; userId?: string } }): Promise<UserType> {
  const url = `${getApiBase()}/api/users/${args.data.id}`
  const response = await fetch(url)
  if (!response.ok) {
    const err = await response.json().catch(() => ({ error: { message: response.statusText } }))
    throw new Error(err.error?.message || 'User not found')
  }
  const json = await response.json()
  return json.data as UserType
}

/**
 * Create a new User
 */
export async function createUser(args: { data: { input: UserCreateInput; userId?: string } }): Promise<UserType> {
  const url = `${getApiBase()}/api/users`
  const response = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(args.data.input),
  })
  if (!response.ok) {
    const err = await response.json().catch(() => ({ error: { message: response.statusText } }))
    throw new Error(err.error?.message || 'Failed to create User')
  }
  const json = await response.json()
  return json.data as UserType
}

/**
 * Update an existing User
 */
export async function updateUser(args: { data: { id: string; input: UserUpdateInput; userId?: string } }): Promise<UserType> {
  const url = `${getApiBase()}/api/users/${args.data.id}`
  const response = await fetch(url, {
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(args.data.input),
  })
  if (!response.ok) {
    const err = await response.json().catch(() => ({ error: { message: response.statusText } }))
    throw new Error(err.error?.message || 'Failed to update User')
  }
  const json = await response.json()
  return json.data as UserType
}

/**
 * Delete a User
 */
export async function deleteUser(args: { data: { id: string; userId?: string } }): Promise<{ success: boolean }> {
  const url = `${getApiBase()}/api/users/${args.data.id}`
  const response = await fetch(url, {
    method: 'DELETE',
  })
  if (!response.ok) {
    const err = await response.json().catch(() => ({ error: { message: response.statusText } }))
    throw new Error(err.error?.message || 'Failed to delete User')
  }
  return { success: true }
}

// ============================================================================
// CityMission Client Functions
// ============================================================================

/**
 * List all CityMission records
 */
export async function getCityMissionList(args: { data: { userId?: string; where?: Record<string, unknown> } }): Promise<CityMissionType[]> {
  const params = new URLSearchParams()
  if (args.data.userId) params.set('userId', args.data.userId)
  if (args.data.where) {
    for (const [key, value] of Object.entries(args.data.where)) {
      if (value !== undefined && value !== null) params.set(key, String(value))
    }
  }
  const qs = params.toString()
  const url = `${getApiBase()}/api/city-missions${qs ? `?${qs}` : ''}`
  const response = await fetch(url)
  if (!response.ok) {
    const err = await response.json().catch(() => ({ error: { message: response.statusText } }))
    throw new Error(err.error?.message || 'Failed to list CityMission')
  }
  const json = await response.json()
  return (json.items || []) as CityMissionType[]
}

/**
 * Get a single CityMission by ID
 */
export async function getCityMissionById(args: { data: { id: string; userId?: string } }): Promise<CityMissionType> {
  const url = `${getApiBase()}/api/city-missions/${args.data.id}`
  const response = await fetch(url)
  if (!response.ok) {
    const err = await response.json().catch(() => ({ error: { message: response.statusText } }))
    throw new Error(err.error?.message || 'CityMission not found')
  }
  const json = await response.json()
  return json.data as CityMissionType
}

/**
 * Create a new CityMission
 */
export async function createCityMission(args: { data: { input: CityMissionCreateInput; userId?: string } }): Promise<CityMissionType> {
  const url = `${getApiBase()}/api/city-missions`
  const response = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(args.data.input),
  })
  if (!response.ok) {
    const err = await response.json().catch(() => ({ error: { message: response.statusText } }))
    throw new Error(err.error?.message || 'Failed to create CityMission')
  }
  const json = await response.json()
  return json.data as CityMissionType
}

/**
 * Update an existing CityMission
 */
export async function updateCityMission(args: { data: { id: string; input: CityMissionUpdateInput; userId?: string } }): Promise<CityMissionType> {
  const url = `${getApiBase()}/api/city-missions/${args.data.id}`
  const response = await fetch(url, {
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(args.data.input),
  })
  if (!response.ok) {
    const err = await response.json().catch(() => ({ error: { message: response.statusText } }))
    throw new Error(err.error?.message || 'Failed to update CityMission')
  }
  const json = await response.json()
  return json.data as CityMissionType
}

/**
 * Delete a CityMission
 */
export async function deleteCityMission(args: { data: { id: string; userId?: string } }): Promise<{ success: boolean }> {
  const url = `${getApiBase()}/api/city-missions/${args.data.id}`
  const response = await fetch(url, {
    method: 'DELETE',
  })
  if (!response.ok) {
    const err = await response.json().catch(() => ({ error: { message: response.statusText } }))
    throw new Error(err.error?.message || 'Failed to delete CityMission')
  }
  return { success: true }
}

// ============================================================================
// Place Client Functions
// ============================================================================

/**
 * List all Place records
 */
export async function getPlaceList(args: { data: { userId?: string; where?: Record<string, unknown> } }): Promise<PlaceType[]> {
  const params = new URLSearchParams()
  if (args.data.userId) params.set('userId', args.data.userId)
  if (args.data.where) {
    for (const [key, value] of Object.entries(args.data.where)) {
      if (value !== undefined && value !== null) params.set(key, String(value))
    }
  }
  const qs = params.toString()
  const url = `${getApiBase()}/api/places${qs ? `?${qs}` : ''}`
  const response = await fetch(url)
  if (!response.ok) {
    const err = await response.json().catch(() => ({ error: { message: response.statusText } }))
    throw new Error(err.error?.message || 'Failed to list Place')
  }
  const json = await response.json()
  return (json.items || []) as PlaceType[]
}

/**
 * Get a single Place by ID
 */
export async function getPlaceById(args: { data: { id: string; userId?: string } }): Promise<PlaceType> {
  const url = `${getApiBase()}/api/places/${args.data.id}`
  const response = await fetch(url)
  if (!response.ok) {
    const err = await response.json().catch(() => ({ error: { message: response.statusText } }))
    throw new Error(err.error?.message || 'Place not found')
  }
  const json = await response.json()
  return json.data as PlaceType
}

/**
 * Create a new Place
 */
export async function createPlace(args: { data: { input: PlaceCreateInput; userId?: string } }): Promise<PlaceType> {
  const url = `${getApiBase()}/api/places`
  const response = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(args.data.input),
  })
  if (!response.ok) {
    const err = await response.json().catch(() => ({ error: { message: response.statusText } }))
    throw new Error(err.error?.message || 'Failed to create Place')
  }
  const json = await response.json()
  return json.data as PlaceType
}

/**
 * Update an existing Place
 */
export async function updatePlace(args: { data: { id: string; input: PlaceUpdateInput; userId?: string } }): Promise<PlaceType> {
  const url = `${getApiBase()}/api/places/${args.data.id}`
  const response = await fetch(url, {
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(args.data.input),
  })
  if (!response.ok) {
    const err = await response.json().catch(() => ({ error: { message: response.statusText } }))
    throw new Error(err.error?.message || 'Failed to update Place')
  }
  const json = await response.json()
  return json.data as PlaceType
}

/**
 * Delete a Place
 */
export async function deletePlace(args: { data: { id: string; userId?: string } }): Promise<{ success: boolean }> {
  const url = `${getApiBase()}/api/places/${args.data.id}`
  const response = await fetch(url, {
    method: 'DELETE',
  })
  if (!response.ok) {
    const err = await response.json().catch(() => ({ error: { message: response.statusText } }))
    throw new Error(err.error?.message || 'Failed to delete Place')
  }
  return { success: true }
}

// ============================================================================
// CommunityReport Client Functions
// ============================================================================

/**
 * List all CommunityReport records
 */
export async function getCommunityReportList(args: { data: { userId?: string; where?: Record<string, unknown> } }): Promise<CommunityReportType[]> {
  const params = new URLSearchParams()
  if (args.data.userId) params.set('userId', args.data.userId)
  if (args.data.where) {
    for (const [key, value] of Object.entries(args.data.where)) {
      if (value !== undefined && value !== null) params.set(key, String(value))
    }
  }
  const qs = params.toString()
  const url = `${getApiBase()}/api/community-reports${qs ? `?${qs}` : ''}`
  const response = await fetch(url)
  if (!response.ok) {
    const err = await response.json().catch(() => ({ error: { message: response.statusText } }))
    throw new Error(err.error?.message || 'Failed to list CommunityReport')
  }
  const json = await response.json()
  return (json.items || []) as CommunityReportType[]
}

/**
 * Get a single CommunityReport by ID
 */
export async function getCommunityReportById(args: { data: { id: string; userId?: string } }): Promise<CommunityReportType> {
  const url = `${getApiBase()}/api/community-reports/${args.data.id}`
  const response = await fetch(url)
  if (!response.ok) {
    const err = await response.json().catch(() => ({ error: { message: response.statusText } }))
    throw new Error(err.error?.message || 'CommunityReport not found')
  }
  const json = await response.json()
  return json.data as CommunityReportType
}

/**
 * Create a new CommunityReport
 */
export async function createCommunityReport(args: { data: { input: CommunityReportCreateInput; userId?: string } }): Promise<CommunityReportType> {
  const url = `${getApiBase()}/api/community-reports`
  const response = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(args.data.input),
  })
  if (!response.ok) {
    const err = await response.json().catch(() => ({ error: { message: response.statusText } }))
    throw new Error(err.error?.message || 'Failed to create CommunityReport')
  }
  const json = await response.json()
  return json.data as CommunityReportType
}

/**
 * Update an existing CommunityReport
 */
export async function updateCommunityReport(args: { data: { id: string; input: CommunityReportUpdateInput; userId?: string } }): Promise<CommunityReportType> {
  const url = `${getApiBase()}/api/community-reports/${args.data.id}`
  const response = await fetch(url, {
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(args.data.input),
  })
  if (!response.ok) {
    const err = await response.json().catch(() => ({ error: { message: response.statusText } }))
    throw new Error(err.error?.message || 'Failed to update CommunityReport')
  }
  const json = await response.json()
  return json.data as CommunityReportType
}

/**
 * Delete a CommunityReport
 */
export async function deleteCommunityReport(args: { data: { id: string; userId?: string } }): Promise<{ success: boolean }> {
  const url = `${getApiBase()}/api/community-reports/${args.data.id}`
  const response = await fetch(url, {
    method: 'DELETE',
  })
  if (!response.ok) {
    const err = await response.json().catch(() => ({ error: { message: response.statusText } }))
    throw new Error(err.error?.message || 'Failed to delete CommunityReport')
  }
  return { success: true }
}

// ============================================================================
// HeritageTrail Client Functions
// ============================================================================

/**
 * List all HeritageTrail records
 */
export async function getHeritageTrailList(args: { data: { userId?: string; where?: Record<string, unknown> } }): Promise<HeritageTrailType[]> {
  const params = new URLSearchParams()
  if (args.data.userId) params.set('userId', args.data.userId)
  if (args.data.where) {
    for (const [key, value] of Object.entries(args.data.where)) {
      if (value !== undefined && value !== null) params.set(key, String(value))
    }
  }
  const qs = params.toString()
  const url = `${getApiBase()}/api/heritage-trails${qs ? `?${qs}` : ''}`
  const response = await fetch(url)
  if (!response.ok) {
    const err = await response.json().catch(() => ({ error: { message: response.statusText } }))
    throw new Error(err.error?.message || 'Failed to list HeritageTrail')
  }
  const json = await response.json()
  return (json.items || []) as HeritageTrailType[]
}

/**
 * Get a single HeritageTrail by ID
 */
export async function getHeritageTrailById(args: { data: { id: string; userId?: string } }): Promise<HeritageTrailType> {
  const url = `${getApiBase()}/api/heritage-trails/${args.data.id}`
  const response = await fetch(url)
  if (!response.ok) {
    const err = await response.json().catch(() => ({ error: { message: response.statusText } }))
    throw new Error(err.error?.message || 'HeritageTrail not found')
  }
  const json = await response.json()
  return json.data as HeritageTrailType
}

/**
 * Create a new HeritageTrail
 */
export async function createHeritageTrail(args: { data: { input: HeritageTrailCreateInput; userId?: string } }): Promise<HeritageTrailType> {
  const url = `${getApiBase()}/api/heritage-trails`
  const response = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(args.data.input),
  })
  if (!response.ok) {
    const err = await response.json().catch(() => ({ error: { message: response.statusText } }))
    throw new Error(err.error?.message || 'Failed to create HeritageTrail')
  }
  const json = await response.json()
  return json.data as HeritageTrailType
}

/**
 * Update an existing HeritageTrail
 */
export async function updateHeritageTrail(args: { data: { id: string; input: HeritageTrailUpdateInput; userId?: string } }): Promise<HeritageTrailType> {
  const url = `${getApiBase()}/api/heritage-trails/${args.data.id}`
  const response = await fetch(url, {
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(args.data.input),
  })
  if (!response.ok) {
    const err = await response.json().catch(() => ({ error: { message: response.statusText } }))
    throw new Error(err.error?.message || 'Failed to update HeritageTrail')
  }
  const json = await response.json()
  return json.data as HeritageTrailType
}

/**
 * Delete a HeritageTrail
 */
export async function deleteHeritageTrail(args: { data: { id: string; userId?: string } }): Promise<{ success: boolean }> {
  const url = `${getApiBase()}/api/heritage-trails/${args.data.id}`
  const response = await fetch(url, {
    method: 'DELETE',
  })
  if (!response.ok) {
    const err = await response.json().catch(() => ({ error: { message: response.statusText } }))
    throw new Error(err.error?.message || 'Failed to delete HeritageTrail')
  }
  return { success: true }
}

// ============================================================================
// RouteRecommendation Client Functions
// ============================================================================

/**
 * List all RouteRecommendation records
 */
export async function getRouteRecommendationList(args: { data: { userId?: string; where?: Record<string, unknown> } }): Promise<RouteRecommendationType[]> {
  const params = new URLSearchParams()
  if (args.data.userId) params.set('userId', args.data.userId)
  if (args.data.where) {
    for (const [key, value] of Object.entries(args.data.where)) {
      if (value !== undefined && value !== null) params.set(key, String(value))
    }
  }
  const qs = params.toString()
  const url = `${getApiBase()}/api/route-recommendations${qs ? `?${qs}` : ''}`
  const response = await fetch(url)
  if (!response.ok) {
    const err = await response.json().catch(() => ({ error: { message: response.statusText } }))
    throw new Error(err.error?.message || 'Failed to list RouteRecommendation')
  }
  const json = await response.json()
  return (json.items || []) as RouteRecommendationType[]
}

/**
 * Get a single RouteRecommendation by ID
 */
export async function getRouteRecommendationById(args: { data: { id: string; userId?: string } }): Promise<RouteRecommendationType> {
  const url = `${getApiBase()}/api/route-recommendations/${args.data.id}`
  const response = await fetch(url)
  if (!response.ok) {
    const err = await response.json().catch(() => ({ error: { message: response.statusText } }))
    throw new Error(err.error?.message || 'RouteRecommendation not found')
  }
  const json = await response.json()
  return json.data as RouteRecommendationType
}

/**
 * Create a new RouteRecommendation
 */
export async function createRouteRecommendation(args: { data: { input: RouteRecommendationCreateInput; userId?: string } }): Promise<RouteRecommendationType> {
  const url = `${getApiBase()}/api/route-recommendations`
  const response = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(args.data.input),
  })
  if (!response.ok) {
    const err = await response.json().catch(() => ({ error: { message: response.statusText } }))
    throw new Error(err.error?.message || 'Failed to create RouteRecommendation')
  }
  const json = await response.json()
  return json.data as RouteRecommendationType
}

/**
 * Update an existing RouteRecommendation
 */
export async function updateRouteRecommendation(args: { data: { id: string; input: RouteRecommendationUpdateInput; userId?: string } }): Promise<RouteRecommendationType> {
  const url = `${getApiBase()}/api/route-recommendations/${args.data.id}`
  const response = await fetch(url, {
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(args.data.input),
  })
  if (!response.ok) {
    const err = await response.json().catch(() => ({ error: { message: response.statusText } }))
    throw new Error(err.error?.message || 'Failed to update RouteRecommendation')
  }
  const json = await response.json()
  return json.data as RouteRecommendationType
}

/**
 * Delete a RouteRecommendation
 */
export async function deleteRouteRecommendation(args: { data: { id: string; userId?: string } }): Promise<{ success: boolean }> {
  const url = `${getApiBase()}/api/route-recommendations/${args.data.id}`
  const response = await fetch(url, {
    method: 'DELETE',
  })
  if (!response.ok) {
    const err = await response.json().catch(() => ({ error: { message: response.statusText } }))
    throw new Error(err.error?.message || 'Failed to delete RouteRecommendation')
  }
  return { success: true }
}
