// SPDX-License-Identifier: MIT
// Copyright (C) 2026 Shogo Technologies, Inc.
/**
 * Auto-generated Types
 *
 * TypeScript types for models and operations.
 * Generated by `shogo generate` - DO NOT EDIT
 */

// ============================================================================
// Model Types
// ============================================================================

export interface UserType {
  id: string
  email: string
  name?: string
  createdAt: Date
  updatedAt: Date
}

export interface CityMissionType {
  id: string
  city: string
  startLocation?: string
  destination?: string
  interests: string
  budget: number
  currency: string
  duration: string
  transport: string
  accessibility?: string
  priorities: string
  latitude?: number
  longitude?: number
  createdAt: Date
  updatedAt: Date
}

export interface PlaceType {
  id: string
  name: string
  category: string
  description?: string
  city: string
  latitude: number
  longitude: number
  address?: string
  distance?: number
  openingHours?: string
  priceRange?: string
  estimatedCost?: number
  currency: string
  rating?: number
  accessibility?: string
  culturalValue?: string
  source: string
  sourceUrl?: string
  imageUrl?: string
  createdAt: Date
  updatedAt: Date
}

export interface CommunityReportType {
  id: string
  city: string
  category: string
  description: string
  latitude: number
  longitude: number
  address?: string
  reportTime: Date
  status: string
  corroborations: number
  imageUrl?: string
  audioUrl?: string
  submittedBy: string
  createdAt: Date
  updatedAt: Date
}

export interface HeritageTrailType {
  id: string
  city: string
  name: string
  description: string
  sites: string
  distance?: number
  duration?: string
  culturalContext?: string
  source: string
  sourceUrl?: string
  createdAt: Date
}

export interface RouteRecommendationType {
  id: string
  city: string
  from: string
  to: string
  transport: string
  distance?: number
  estimatedTime?: string
  reportCount: number
  concerns?: string
  source: string
  sourceUrl?: string
  createdAt: Date
}

// ============================================================================
// Input Types
// ============================================================================

export interface UserCreateInput {
  email: string
  name?: string
}

export interface UserUpdateInput {
  email?: string
  name?: string
}

export interface CityMissionCreateInput {
  city: string
  startLocation?: string
  destination?: string
  interests: string
  budget: number
  currency?: string
  duration: string
  transport: string
  accessibility?: string
  priorities: string
  latitude?: number
  longitude?: number
}

export interface CityMissionUpdateInput {
  city?: string
  startLocation?: string
  destination?: string
  interests?: string
  budget?: number
  currency?: string
  duration?: string
  transport?: string
  accessibility?: string
  priorities?: string
  latitude?: number
  longitude?: number
}

export interface PlaceCreateInput {
  name: string
  category: string
  description?: string
  city: string
  latitude: number
  longitude: number
  address?: string
  distance?: number
  openingHours?: string
  priceRange?: string
  estimatedCost?: number
  currency?: string
  rating?: number
  accessibility?: string
  culturalValue?: string
  source: string
  sourceUrl?: string
  imageUrl?: string
}

export interface PlaceUpdateInput {
  name?: string
  category?: string
  description?: string
  city?: string
  latitude?: number
  longitude?: number
  address?: string
  distance?: number
  openingHours?: string
  priceRange?: string
  estimatedCost?: number
  currency?: string
  rating?: number
  accessibility?: string
  culturalValue?: string
  source?: string
  sourceUrl?: string
  imageUrl?: string
}

export interface CommunityReportCreateInput {
  city: string
  category: string
  description: string
  latitude: number
  longitude: number
  address?: string
  reportTime: Date
  status?: string
  corroborations?: number
  imageUrl?: string
  audioUrl?: string
  submittedBy?: string
}

export interface CommunityReportUpdateInput {
  city?: string
  category?: string
  description?: string
  latitude?: number
  longitude?: number
  address?: string
  reportTime?: Date
  status?: string
  corroborations?: number
  imageUrl?: string
  audioUrl?: string
  submittedBy?: string
}

export interface HeritageTrailCreateInput {
  city: string
  name: string
  description: string
  sites: string
  distance?: number
  duration?: string
  culturalContext?: string
  source?: string
  sourceUrl?: string
}

export interface HeritageTrailUpdateInput {
  city?: string
  name?: string
  description?: string
  sites?: string
  distance?: number
  duration?: string
  culturalContext?: string
  source?: string
  sourceUrl?: string
}

export interface RouteRecommendationCreateInput {
  city: string
  from: string
  to: string
  transport: string
  distance?: number
  estimatedTime?: string
  reportCount?: number
  concerns?: string
  source?: string
  sourceUrl?: string
}

export interface RouteRecommendationUpdateInput {
  city?: string
  from?: string
  to?: string
  transport?: string
  distance?: number
  estimatedTime?: string
  reportCount?: number
  concerns?: string
  source?: string
  sourceUrl?: string
}

// ============================================================================
// Hook Types
// ============================================================================

export interface HookContext {
  userId?: string
}

export interface ListHookResult {
  where?: Record<string, unknown>
}

export interface GetHookResult {
  deny?: boolean
}

export interface UpdateHookResult<T> {
  deny?: boolean
  input?: T
}

export interface DeleteHookResult {
  deny?: boolean
}

export interface ModelHooks<TCreate, TUpdate, TModel> {
  beforeList?: (ctx: HookContext) => Promise<ListHookResult | void>
  beforeGet?: (id: string, ctx: HookContext) => Promise<GetHookResult | void>
  beforeCreate?: (input: TCreate, ctx: HookContext) => Promise<TCreate>
  afterCreate?: (item: TModel, ctx: HookContext) => Promise<void>
  beforeUpdate?: (id: string, input: TUpdate, ctx: HookContext) => Promise<UpdateHookResult<TUpdate> | void>
  afterUpdate?: (item: TModel, ctx: HookContext) => Promise<void>
  beforeDelete?: (id: string, ctx: HookContext) => Promise<DeleteHookResult | void>
  afterDelete?: (id: string, ctx: HookContext) => Promise<void>
}

export interface ServerFunctionHooks {
  User?: ModelHooks<UserCreateInput, UserUpdateInput, UserType>
  CityMission?: ModelHooks<CityMissionCreateInput, CityMissionUpdateInput, CityMissionType>
  Place?: ModelHooks<PlaceCreateInput, PlaceUpdateInput, PlaceType>
  CommunityReport?: ModelHooks<CommunityReportCreateInput, CommunityReportUpdateInput, CommunityReportType>
  HeritageTrail?: ModelHooks<HeritageTrailCreateInput, HeritageTrailUpdateInput, HeritageTrailType>
  RouteRecommendation?: ModelHooks<RouteRecommendationCreateInput, RouteRecommendationUpdateInput, RouteRecommendationType>
}
